### ISSUE TITLE
roudi crash on raspberry pi4

### ISSUE THREAD

**Issue by yooouxin** [eclipse-iceoryx/iceoryx#1016]
When I running iox-roudi on raspberry pi 4,it report like this
```
Condition: m_head.is_lock_free() && "std::atomic<LoFFLi::Node> must be lock-free!"
```
How to fix this?

**Comment by elBoberido** [comment]
I think you build iceoryx on a 32 bit platform. While the PI4 has a 64 bit processor, the Raspberry Pi OS is 32 bit to be compatible with older PIs. You can try Ubuntu from https://www.raspberrypi.com/software/operating-systems/. It doesn't matter if Core, Server or Desktop

**Comment by mossmaurice** [comment]
@yooouxin Closing this issue, feel free to re-open if you have further questions.
