### ISSUE TITLE
Check for duplicate test IDs in CI

### ISSUE THREAD

**Issue by mossmaurice** [eclipse-iceoryx/iceoryx#1020]
## Brief feature description

The IDs used to identify unit test cases have to be unique.

## Detailed information

Add a CI check to verify the uniqueness.

**Comment by mossmaurice** [comment]
Implemented in [`pre-flight` check](https://github.com/eclipse-iceoryx/iceoryx/blob/master/.github/workflows/build-test.yml#L22-L27), closing.

**Comment by elBoberido** [comment]
Oh, there was an open issue for this? It was fixed with #1377 since there were some issues with the duplicate test IDs.
