### ISSUE TITLE
one subscriber  and  multi publishers,could not subscriber data correctly.

### ISSUE THREAD

**Issue by kangleorc** [eclipse-iceoryx/iceoryx#1021]
## Required information
process publisher:
![pub](https://user-images.githubusercontent.com/6835705/149635932-7b2ef118-8b3d-4750-8d5a-131f6a6ccca6.png)
 
process subscriber1:
 ![Feishu20220116-035528](https://user-images.githubusercontent.com/6835705/149635963-c4687bbd-8828-4663-882c-b88641f0b3ef.png)
process subscriber2:  same as subscriber1,just use different APP_NAME

**Operating system:**
 Ubuntu 21.04 LTS

**Compiler version:**
 GCC 10.3.0
  
**Observed result or behaviour:**
 ![Screenshot from 2022-01-16 03-39-54](https://user-images.githubusercontent.com/6835705/149635580-5c0d9cfc-0cd7-45c3-832d-6a5158b2cc61.png)

**Expected result or behaviour:**
when two subscriber processes  reply data,  the publisher porcess could get messge  without delay

**Conditions where it occurred / Performed steps:**
Describe how one can reproduce the bug.
step1: iox-roudi
step2: run process subscriber1 and subscriber2
step3: run process publisher

**Comment by kangleorc** [comment]
I modify the code base on iceoryx/iceoryx_examples/callbacks/ice_callbacks_publisher.cpp ,iceoryx/iceoryx_examples/callbacks/ice_callbacks_subscriber.cpp

**Comment by qclzdh** [comment]
One easy way to fix this is to clean the queue in the callback everytime:
For example change your process publisher to 
```
    while(subscriber->hasData()) {
        subscriber->take().and_then([subscriber](auto& sample) {
            std::cout << "received: " << sample->counter << std::endl;
        });
    }
```
then, you won't see that delay.

**Comment by kangleorc** [comment]
It works !  Thanks for help.
