### ISSUE TITLE
Introduce strict matching mode for historyCapacity

### ISSUE THREAD

**Issue by MatthiasKillat** [eclipse-iceoryx/iceoryx#1029]
## Brief feature description

Currently we allow matching of subscribers with HistoryRequest > HistoryCapacity of the publisher. Strictly speaking asking for a contract which can never be fulfilled (even if the publisher had that many samples before) and hence could be forbidden under certain conditions. This covers the special case of `HistoryRequest > HistoryCapacity = 0`.

## Detailed information

We will introduce a flag `requirePublisherHistorySupport` to define whether we want to strictly enforce `HistoryRequest <= HistoryCapacity`. If this flag is `true`, publishers and subscribers not satisfying the inequality will not be connected. 

By default it will be set to `false` which leads to the current behavior, i.e. does not break any existing systems.

## Use Case
Matching between Readers and Writers in Cyclone DDS where at least one of them has durability TRANSIENT LOCAL (out of TRANSIENT LOCAL and VOLATILE).

**Comment by MatthiasKillat** [comment]
@elBoberido Implementing this is actually more effort than anticipated due to convoluted building blocks. More precisely:

It is not possible to access the `historyCapacity` of the publisher (`PublisherPortRouDi`) directly to perform the check in `PortManager::sendToAllMatchingPublisherPorts`. Same with `SubscriberPortRouDi`. 

Note that specialized methods such as `getSubscriberTooSlowPolicy` exist, but I think we should add some way to get the whole otions struct (which is not explicitly stored). I would add a way to get the otpions struct. I need the history capacity and the to be introduced matching mode flag on publisher side and the history request on subscriber side (as well as the flag).

What do you think?

**Comment by elBoberido** [comment]
@MatthiasKillat after some thinking it might make more sense to have a specific flag/enum only for the history in order to have more control over the integration into DDS. Something like `mustAdvertiseHistory` or an enum like `HistoryRequestBehavior`
