### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ygqzwl** [eclipse-iceoryx/iceoryx#1031]
## Required information

**Operating system:**
E.g. Ubuntu 18.04 LTS

**Compiler version:**
E.g. GCC 7.4.0

**Observed result or behaviour:**
CMake Error at cmake/IceoryxPackageHelper.cmake:80 (install):
    install TARGETS given target "iceoryx_platform" which does not exist in
    this directory.
Call Stack (most recent call first):
    cmake/IceoryxPackageHelper.cmake:63 (install_target_directories_and_header)
    CMakeLists.txt:226

**Expected result or behaviour:**
build this protect

**Conditions where it occurred / Performed steps:**
non

**Comment by mossmaurice** [comment]
@ygqzwl Thanks for creating this issue! Could you please add the exact commands which you executed in order to reproduce this error? E.g. did you do

```
cmake -Bbuild -Hiceoryx_meta && cd build && make -j8
# or
./tools/iceoryx_build_test.sh build-all
```

[This page](https://iceoryx.io/v1.0.1/getting-started/installation/) could also be useful. Thanks!

**Comment by elBoberido** [comment]
@ygqzwl It would also be interesting if you build iceoryx before and this is something which happened only recently. It might be a fallout of #1013 but the CI runs fine. Out of the blue I would guess that maybe your cmake is too old. AFAIK on ubuntu 18.04 we require a newer cmake from the universe/multiverse repo.

**Comment by ygqzwl** [comment]
> @ygqzwl Thanks for creating this issue! Could you please add the exact commands which you executed in order to reproduce this error? E.g. did you do
> 
> ```
> cmake -Bbuild -Hiceoryx_meta && cd build && make -j8
> # or
> ./tools/iceoryx_build_test.sh build-all
> ```
> 
> [This page](https://iceoryx.io/v1.0.1/getting-started/installation/) could also be useful. Thanks!

I do this：
cmake -Bbuild -Hiceoryx_meta

and cmake version 3.10.2

**Comment by ygqzwl** [comment]
> @ygqzwl It would also be interesting if you build iceoryx before and this is something which happened only recently. It might be a fallout of #1013 but the CI runs fine. Out of the blue I would guess that maybe your cmake is too old. AFAIK on ubuntu 18.04 we require a newer cmake from the universe/multiverse repo.

Thank you very much for your reply, but I didn't compile it on QNX， and  cmake version 3.10.2

**Comment by elBoberido** [comment]
@ygqzwl it is not directly related to a QNX build, but the PR for that issue touched the platform libs and it might be possible that it broke something for you.

I just checked the CI and it seems the github ubuntu images for 18.04 have cmake 3.22 installed. This means we might have introduced newer cmake features without noticing it.

**Comment by elBoberido** [comment]
@ygqzwl it seems there is a `cmake-mozilla` package in the universe repo which provides cmake 3.16. Would that be an option for you?

**Comment by ygqzwl** [comment]
@elBoberido  Thank you very much.  cmake 3.16 can solve my compilation problem。
