### ISSUE TITLE
compile error:  std::result_of - deprecated in c++17 and removed in c++20

### ISSUE THREAD

**Issue by niclar** [eclipse-iceoryx/iceoryx#1076]
The use of std::result_of in the project prevents it from being built in C++20 projects;

e.g

iceoryx_hoofs/cxx/type_traits.hpp(66,56): error C2039: 'result_of': is not a member of 'std'

Would you consider replacing it with std::invoke_result or suitable wrappers ?

In the meantime for vc one can reintroduce the templates and get it to compile by defining _HAS_DEPRECATED_RESULT_OF

**Comment by elfenpiff** [comment]
@niclar Thanks for the hint! This should be easily fixable by us.

**Comment by elfenpiff** [comment]
@niclar I created a pull request fixing this issue. #1079 If you can't wait you can use it right away - I think it will be merged today.

**Comment by niclar** [comment]
Thanks @elfenpiff, np, I'll use the workaround until merged.

#1078 however, is a blocking error

**Comment by niclar** [comment]
@elfenpiff there are still usages left i.e;

iceoryx_hoofs/platform/win32_errorHandling.hpp(51,52): error C2760: syntax error: '&' was unexpected here; expected 'expression'

`template <typename Function, typename... Targs>
auto __Win32Call(const char* functionName, const char* file, const int line, const Function& f, Targs&&... args)
    -> Win32CallReturn<std::result_of_t<decltype(f)&(Targs...)>>`

**Comment by niclar** [comment]
thanks for fixing this

**Comment by elfenpiff** [comment]
@niclar happy to help? What are you building with iceoryx?
