### ISSUE TITLE
compile error: duration.inl - duration literals are not found

### ISSUE THREAD

**Issue by niclar** [eclipse-iceoryx/iceoryx#1078]
seems like the duration literals are not resolved during compilation of iceoryx_hoofs/internal/units/duration.inl in vs

e.g iceoryx_hoofs/internal/units/duration.inl(79,23): error C3861: '_ns': identifier not found

they are defined later in the header (inline namespace duration_literals)

**Comment by elfenpiff** [comment]
@niclar Again, thanks for the hint :D ... I am wondering why our CI did not catch this.

**Comment by niclar** [comment]
I'm running vs 2022 (Version 17.1.0 Preview 5.0)

**Comment by niclar** [comment]
Got it compile by using a wrapper in place of the user literals as;

      inline constexpr Duration to_ns(unsigned long long int value) noexcept
      {
         return operator"" _ns(value);
      }

template <typename T>
constexpr Duration Duration::fromNanoseconds(const T value) noexcept
{
    return to_ns(positiveValueOrClampToZero(value, __PRETTY_FUNCTION__));
}

**Comment by elfenpiff** [comment]
I think the problem lies in the `inline namespace duration_literals` which has some issues with msvc. Turning this inline namespace into a normal namespace should solve the problem. But I cannot verify this yet (my VS2022 installation takes some time ;) ).

**Comment by elfenpiff** [comment]
@niclar Would you be able to test #1080 for me? This should fix this problem in theory.

**Comment by niclar** [comment]
@elfenpiff it did not unfortunately. -So the issue is with the user define literal lookup specifically. 
My fix above, albeit ugly, fixes it though

**Comment by niclar** [comment]
@elfenpiff it did not unfortunately. -So the issue is with the user define literal lookup specifically. 
My fix above, albeit ugly, fixes it though

**Comment by niclar** [comment]
-- Building for: Visual Studio 17 2022
-- The C compiler identification is MSVC 19.31.31104.0
-- The CXX compiler identification is MSVC 19.31.31104.0

**Comment by elfenpiff** [comment]
@niclar It was my fault, I did not use the latest preview. But even now I cannot reproduce the error.

This is my msvc version: 19.31.31104.0

Can you please do the following:
1. stash your changes and use the current iceoryx master
2. Open a powershell
```
cd iceoryx
```
3. Check the current git hash you are using (just to make sure we both use the current master), mine is `9937240a0`:
```
git rev-parse --short HEAD
```
4. Remove the `build` folder if it exists
```
Remove-Item -recurse -force build
```
5. Regenerate the cmake configs
```
cmake -Bbuild -Hiceoryx_meta -DEXAMPLES=ON -DBUILD_TEST=ON
```
6. Build everything with
```
cmake --build build
```

When the build fails could you send me please the console output leading to this error or maybe the whole log?

**Comment by niclar** [comment]
I'm on 947a850e185951dbb8d1108c4e1347e5fa757119 but I see no later changes that would remedy this..

**Comment by niclar** [comment]
@elfenpiff can you build iceoryx/iceoryx_examples/singleprocess/single_process.cpp with that vs compiler ?

**Comment by elfenpiff** [comment]
@niclar I can compile it without any problem but the example just crashes.

I created an issue for that #1082 

But when I switch to your commit hash, remove the complete build folder I can still build everything successfully - including the `single_process.cpp` example.

**Comment by niclar** [comment]
@elfenpiff that is very strange, I'll update to latest HEAD...

**Comment by elfenpiff** [comment]
@niclar Thank you. I am not so familiar with the whole Windows C++ toolchain so if you have some hints for I would be thankful.

I just started this example in vscode with the "cppvsdbg" and this states that in `single_process.cpp:112` an exception is thrown, which is the beginning of main?!

But I have an idea what caused this, the stack size it should be 8Mb but the default on windows is 1Mb

**Comment by niclar** [comment]
@elenpiff  no worries. -Did you set c++20 generation in vs?   I.e  under "C++ Language Standard"    set it to  "Preview - Features from the Latest C++ Working Draft (/std:c++latest)"

**Comment by elfenpiff** [comment]
@niclar with `/std:c++latest` I am drowning in compiler errors right from the first file:
```
  file.cpp
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\include\iceoryx_hoofs/platform/win32_errorHandling.hpp(51,52
): error C2760: syntax error: '&' was unexpected here; expected 'expression' [C:\Users\me\Development\iceoryx\build\hoo
fs\platform\iceoryx_platform.vcxproj]
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\include\iceoryx_hoofs/platform/win32_errorHandling.hpp(51,52
): error C2187: syntax error: '&' was unexpected here [C:\Users\me\Development\iceoryx\build\hoofs\platform\iceoryx_pla
tform.vcxproj]
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\include\iceoryx_hoofs/platform/win32_errorHandling.hpp(51,1)
: error C2059: syntax error: '>' [C:\Users\me\Development\iceoryx\build\hoofs\platform\iceoryx_platform.vcxproj]
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\include\iceoryx_hoofs/platform/win32_errorHandling.hpp(51,63
): error C2988: unrecognizable template declaration/definition [C:\Users\me\Development\iceoryx\build\hoofs\platform\ic
eoryx_platform.vcxproj]
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\include\iceoryx_hoofs/platform/win32_errorHandling.hpp(51,63
): error C2059: syntax error: '>' [C:\Users\me\Development\iceoryx\build\hoofs\platform\iceoryx_platform.vcxproj]
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\include\iceoryx_hoofs/platform/win32_errorHandling.hpp(52,1)
: error C2143: syntax error: missing ';' before '{' [C:\Users\me\Development\iceoryx\build\hoofs\platform\iceoryx_platf
orm.vcxproj]
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\include\iceoryx_hoofs/platform/win32_errorHandling.hpp(52,1)
: error C2447: '{': missing function header (old-style formal list?) [C:\Users\me\Development\iceoryx\build\hoofs\platf
orm\iceoryx_platform.vcxproj]
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\source\file.cpp(25,9): error C3861: '__Win32Call': identifie
r not found [C:\Users\me\Development\iceoryx\build\hoofs\platform\iceoryx_platform.vcxproj]
  fnctl.cpp
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\include\iceoryx_hoofs/platform/win32_errorHandling.hpp(51,52
): error C2760: syntax error: '&' was unexpected here; expected 'expression' [C:\Users\me\Development\iceoryx\build\hoo
fs\platform\iceoryx_platform.vcxproj]
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\include\iceoryx_hoofs/platform/win32_errorHandling.hpp(51,52
): error C2187: syntax error: '&' was unexpected here [C:\Users\me\Development\iceoryx\build\hoofs\platform\iceoryx_pla
tform.vcxproj]
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\include\iceoryx_hoofs/platform/win32_errorHandling.hpp(51,1)
: error C2059: syntax error: '>' [C:\Users\me\Development\iceoryx\build\hoofs\platform\iceoryx_platform.vcxproj]
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\include\iceoryx_hoofs/platform/win32_errorHandling.hpp(51,63
): error C2988: unrecognizable template declaration/definition [C:\Users\me\Development\iceoryx\build\hoofs\platform\ic
eoryx_platform.vcxproj]
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\include\iceoryx_hoofs/platform/win32_errorHandling.hpp(51,63
): error C2059: syntax error: '>' [C:\Users\me\Development\iceoryx\build\hoofs\platform\iceoryx_platform.vcxproj]
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\include\iceoryx_hoofs/platform/win32_errorHandling.hpp(52,1)
: error C2143: syntax error: missing ';' before '{' [C:\Users\me\Development\iceoryx\build\hoofs\platform\iceoryx_platf
orm.vcxproj]
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\include\iceoryx_hoofs/platform/win32_errorHandling.hpp(52,1)
: error C2447: '{': missing function header (old-style formal list?) [C:\Users\me\Development\iceoryx\build\hoofs\platf
orm\iceoryx_platform.vcxproj]
C:\Users\me\Development\iceoryx\iceoryx_hoofs\platform\win\source\fnctl.cpp(23,1): error C3861: '__Win32Call': identifi
er not found [C:\Users\me\Development\iceoryx\build\hoofs\platform\iceoryx_platform.vcxproj]
  getopt.cpp
```

**Comment by niclar** [comment]
Yeah that's it.  You are getting that std::result_of_t error (https://github.com/eclipse-iceoryx/iceoryx/issues/1076 is not completed just yet) , ...ignore it by defining _HAS_DEPRECATED_RESULT_OF.

**Comment by elfenpiff** [comment]
@niclar Finally, I finally could reproduce your issue and found several new ones too (lucky me). But with #1085 the `result_of` should be gone once and for all, the duration is fixed and some other minor things.

**Comment by niclar** [comment]
thanks for fixing this
