### ISSUE TITLE
[release 1.0.0] Compile error on gcc 11.2 due to missing <limits> include

### ISSUE THREAD

**Issue by dkroenke** [eclipse-iceoryx/iceoryx#1092]
## Required information

**Operating system:**
E.g. Ubuntu 22.04 LTS

**Compiler version:**
E.g. GCC 11.2.0

**Observed result or behaviour:**
The ROS 2 buildfarm cannot build `iceoryx_utils` from the iceoryx 1.0.0 release on ROS Rolling.

Build log:
```
08:08:58 /tmp/binarydeb/ros-rolling-iceoryx-utils-1.0.0/include/iceoryx_utils/internal/relocatable_pointer/pointer_repository.hpp:52:45: error: ‘numeric_limits’ is not a member of ‘std’
08:08:58    52 |     static constexpr id_t INVALID_ID = std::numeric_limits<id_t>::max();
```

Links to failing builds:
https://build.ros2.org/job/Rbin_uJ64__iceoryx_utils__ubuntu_jammy_amd64__binary/3/
https://build.ros2.org/job/Rbin_ujv8_uJv8__iceoryx_utils__ubuntu_jammy_arm64__binary/3/

This problem applies also to cpptoml where the `<limits>` include is missing too. It is solved on master by adding a patch to cpptoml.

**Expected result or behaviour:**
iceoryx 1.0.0 should compile successfully on gcc 11.2

**Conditions where it occurred / Performed steps:**
Install gcc 11 and checkout `v1.0.0` tag of iceoryx to build.

Additionally a compiler warning from the `cxx::string` is thrown:

```
iceoryx_utils/include/iceoryx_utils/internal/cxx/string.inl:104:69: error: ‘size_t strnlen(const char*, size_t)’ specified bound 99 exceeds source size 37 [-Werror=stringop-overread]
  104 |     : string(TruncateToCapacity, other, strnlen(other, Capacity - 1))
```

**Discussion**

All these errors are already solved on master, so it would be necessary to backport the fixes on the release branch.

- Relates to https://github.com/ApexAI/iceoryx-release/issues/1

**Comment by elBoberido** [comment]
@dkroenke I'm wondering if we should have nightly builds on the actively supported release branches with the latest gcc and clang. What do you think?
