### ISSUE TITLE
1.0.1 or 1.0.2 release for ROS 2 Rolling

### ISSUE THREAD

**Issue by nuclearsandwich** [eclipse-iceoryx/iceoryx#1095]
We've just updated ROS 2 Rolling Ridley to target Ubuntu Jammy and iceoryx_utils is failing to build: https://build.ros2.org/job/Rbin_uJ64__iceoryx_utils__ubuntu_jammy_amd64__binary/

It looks like https://github.com/eclipse-iceoryx/iceoryx/commit/a5ad11f5c3704b5273eea3bd7ce5d0e8f95a466e would resolve the issue and is already in a tagged release, we just need someone to run bloom for it.

In order to unblock our builds I may bloom the release myself in a few ours. If I do I will update this issue.
Thanks!

**Comment by dkroenke** [comment]
@nuclearsandwich 
The release tag [v1.0.2](https://github.com/eclipse-iceoryx/iceoryx/tree/v1.0.2) should fix this issue. Additionally we needed to patch a dependency that faced the same problem.

A bloom release PR is already issued here: https://github.com/ros/rosdistro/pull/32137

**Comment by nuclearsandwich** [comment]
Thanks! That resolved the build issues :fireworks:
