### ISSUE TITLE
`cxx::function_ref`, `cxx::function` and `cxx::unique_ptr` should not be nullable

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1104]
## Brief feature description

The feature of a nullable `function_ref` and `function` can lead to a very easy misuse since one has to always check the `function`/`function_ref` if it is set before using it.

This causes:
* extra overhead
* increases the probability for undefined behavior/bugs

If one would like to have a nullable `function`/`function_ref` one can always wrap this into `cxx::optional` to make it clear that this is maybe null.

That this can happen very easily is demonstrated in the approved PR: https://github.com/eclipse-iceoryx/iceoryx/pull/1094#discussion_r805948235

ToDo:
 - [x] `function_ref`
 - [ ] `function`
 - [x] `unique_ptr`

**Comment by MatthiasKillat** [comment]
@elfenpiff Agree for `function_ref` (references should not be null and this is mainly for passing around, not storing), disagree for `function` as it is supposed to be stored and hence it is useful to be default constructible (which is only reasonable with being not callable, as done by std::function` as well).

This is similar to `nullopt` and I do not like to enforce wrapping it in an `optional` to achieve this (as usability suffers).

Please remove this requirement from the issue as it limits useful designs and deviates more from the STL unnecessarily.

**Comment by elBoberido** [comment]
@MatthiasKillat if `cxx::function` can be `null`, you always have to do a `if (functionVar) { functionVar(); }`, right? If you don't do it how can you be sure not to call an uninitialized `cxx::function`?

**Comment by mossmaurice** [comment]
@elfenpiff I'm unsure if we should pursue this goal. I completely understand your intentions behind and even agree on them. However, we aim for `iceoryx_hoofs` being an independent, stand-alone library. With libraries, users will have a variety of use-cases we are currently not thinking about. Hence, when developing a library, we need a different mindset and need to take special care. This is always a consideration between restriction and flexibility. IIRC this was also the reason on why we allowed a nullable `function_ref` in the first place as there where certain uses-cases which required a `function_ref` to be assigned during runtime.

Have a look at [Folly's implemenation](https://github.com/facebook/folly/blob/main/folly/Function.h) or at [GNU's](https://github.com/bminor/binutils-gdb/blob/master/gdbsupport/function-view.), both allow a nullable `function_ref`. We can take this discussion to our next developer meetup.

**Comment by elfenpiff** [comment]
@elBoberido @MatthiasKillat @mossmaurice what about the following approach. We create a generic free function which fits every interface and looks like:
```cpp
template<typename ReturnType, typename... Arguments>
ReturnType genericEmptyFunction(Arguments&&...) {}
```

This function is by default always set for `function` and `function_ref`. Therefore both types are default constructible and are always valid without having an `if` check overhead. So it is safe to call the callable operator and it can never crash.

But then I would also remove the `operator bool()` from `function`/`function_ref` since it is not nullable in the classical sense anymore. What do you think?

**Comment by elfenpiff** [comment]
@mossmaurice Having a nullable `function` is a big mistake and we do not have to pursue the STL goal of introducing undefined behavior or make the life of users more complex by introducing error handling overhead where it is not needed.

You are right, we aim for `iceoryx_hoofs` of being and independent, stand-alone library - !for safety critical systems!. Why should someone use `iceoryx_hoofs` in a non safety environment where the STL with a lot more features is at their disposal?

But here I have to remind you, that @MatthiasKillat @mossmaurice @elfenpiff reviewed #1094 and none of us experienced developers did catch this - I just caught it by accident when I performed my final review. Having nullable types is dangerous and this PR proofed it and we are working in a safety critical environment!

**Comment by elfenpiff** [comment]
@mossmaurice Here are the design goals of Folly (taken from the Readme)
* library of C++14 components designed with practicality and efficiency in mind.
* Performance concerns permeate much of Folly, sometimes leading to designs that are more idiosyncratic than they would otherwise be

It reads to me that constructs are may more error prone or harder to use to just get more performance out. This is not something we should take inspiration from for safety critical systems!
Our goals would be:
* safety first, this means very hard to misuse, easy to use
* performance second (important but not when it compromises the first goal)

**Comment by elfenpiff** [comment]
@elBoberido I totally agree with `GOTO` lets use `GOTO` everywhere.

**Comment by elBoberido** [comment]
reopen since `function` is still nullable
