### ISSUE TITLE
Remove global usage of `noexcept`  

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1113]
## Brief feature description

We have the ability to allow the user to throw exceptions in callbacks, `cxx::function` or `cxx::function_ref` but noexcept will cause always a `std::terminate`.
This is especially a problem in tests where we avoid fatal errors with `Expects` or the error handler. This is untestable since the errorhandler calls the custom handler and then continues - we require an exception here to make the code testable. 

## Detailed information

Think of testing this piece of code:
```cpp
void doStuff(someClass * ptr) {
  iox::cxx::Expects(ptr != nullptr);

  ptr->doStuff();
}
```

A test like
```cpp
auto handle =
    iox::ErrorHandler::setTemporaryErrorHandler([&](auto, auto, auto) { wasErrorHandlerCalled = true; });
doStuff(nullptr);
EXPECT_TRUE(wasErrorHandlerCalled);
```
will always end up with a segfault since the code in `doStuff` continues after the error handler call. But if we would allow exceptions we could throw an exception in the error handler and safely return to the test.
Then the test only has to verify that the exception was thrown and this indicates that we correctly used the error handler in `doStuff`.

**Comment by elBoberido** [comment]
@elfenpiff this is a duplicate of #1032

**Comment by elfenpiff** [comment]
@elBoberido I would rather think of it as a subtask of #1032 ... I will adjust it

**Comment by elfenpiff** [comment]
Adjusted #1032 with the details mentioned here.
