### ISSUE TITLE
Do not allow creation of publishers with internally used service descriptions

### ISSUE THREAD

**Issue by MatthiasKillat** [eclipse-iceoryx/iceoryx#1120]
## Brief feature description

We need to make sure that the user cannot create publisher ports with internally used service descriptions (like introspection and service registry).

## Detailed information

- use a black list of internally used ServiceDescriptions
- Upon port creation (factory method) check whether a publisher with ServiceDescription on the black list is requested and if so deny it with an error message

**Comment by mossmaurice** [comment]
@MatthiasKillat 
> We need to make sure that the user cannot create publisher ports with internally used service descriptions (like introspection and service registry).

Why do you want to have this hard restriction? I can think of several uses cases where the "internal" topics are used inside frameworks (e.g. `rmw_iceoryx`). How could a user integrating iceoryx in a framework access to topics?

**Comment by elBoberido** [comment]
@mossmaurice this is not restricting the consumption but the production of data. It wouldn't be a good idea that `rmw_iceoryx` publishes with the same service descriptions like the introspection or service discovery
