### ISSUE TITLE
Unique Test IDs are not added to `TIMING_TEST_F`

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1125]
## Brief feature description

In our test code base the unique test IDs for `TIMING_TEST_F` are missing.

**Comment by elfenpiff** [comment]
FYI @mossmaurice

**Comment by dongilchang** [comment]
@mossmaurice The macro is a macro that I didn't expect and considered. I should add a new feature to handle this macro. If it is not urgent, Can you wait for the task that recognizes the macro and add the test id is done?

**Comment by mossmaurice** [comment]
@dongilchang Thanks :pray: It can wait, no urgency.
