### ISSUE TITLE
Adjust `MAX_NUMBER_OF_NOTIFIERS_PER_CONDITION_VARIABLE` to 256

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1144]
## Brief feature description

When a user would like to attach a large number of subscriber/clients/servers to a listener or waitset the number of `MAX_NUMBER_OF_NOTIFIERS_PER_CONDITION_VARIABLE` has to be increased. This should be configurable via a cmake switch like `IOX_MAX_PUBLISHERS`.

Furthermore the variables:
* `MAX_NUMBER_OF_ATTACHMENTS_PER_WAITSET`
* `MAX_NUMBER_OF_EVENTS_PER_LISTENER`

are tightly coupled (identical) to the notifiers per condition variable. It would make sense to remove those two and use in the listener and waitset only `MAX_NUMBER_OF_NOTIFIERS_PER_CONDITION_VARIABLE`.

**Comment by elfenpiff** [comment]
* user sets as cmake switch `MAX_NUMBER_OF_NOTIFIERS_PER_CONDITION_VARIABLE`
* couple `MAX_NUMBER_OF_ATTACHMENTS_PER_WAITSET` and `MAX_NUMBER_OF_EVENTS_PER_LISTENER` to them
* remove `static_assert`

for CMake switch
* add to `iceoryx_posh_deployment.hpp.in`
* set default value of 256 to `iceoryx_posh_deployment.cmake`

**Comment by dkroenke** [comment]
@elfenpiff Please rename the title of this issue since we do not let `MAX_NUMBER_OF_NOTIFIERS_PER_CONDITION_VARIABLE` be configurable over cmake and hardcode it to 256
