### ISSUE TITLE
Integrate Request-Response into DDS gateway

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx#1145]
## Brief feature description

Currently the DDS gateway only supports the publish-subscribe messaging patter

## Detailed information

In order to support all iceoryx messaging pattern, the generic gateway class as well as the DDS gateway need to be extended.

**Comment by mossmaurice** [comment]
Moved to https://github.com/eclipse-iceoryx/iceoryx-gateway-dds/issues/2
