### ISSUE TITLE
terminate slow subscribers

### ISSUE THREAD

**Issue by niclar** [eclipse-iceoryx/iceoryx#1174]
Hi, what's the recommended way of terminating slow subscribers in iceoryx ?

**Comment by niclar** [comment]
An exhausted subscriber queue would indicate a slow subscriber, no ?   
-So instead of blocking or purge old entries, in some cases I'd like to have the option to terminate or even better, get a callback

**Comment by elBoberido** [comment]
@niclar currently that's only possible by polling `hasMissedData` on the subscriber. I'm not sure if this could be added as trigger to the `Listener`. @elfenpiff you are more familiar with the `Listener`/`WaitSet`. Is this possible out of the box?

**Comment by niclar** [comment]
Thanks @elBoberido I'll poll for now.

**Comment by elBoberido** [comment]
@niclar I guess the issue can be closed for now?

**Comment by niclar** [comment]
@elBoberido yeah lets do that. Its nothing major..
