### ISSUE TITLE
CI job for linux aarch64

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1208]
## Brief feature description

Some classes and variables have a different size on aarch64. This can cause segfaults in the c binding or may lead to different behavior in the C++ world.
Furthermore aarch64 has a different memory model then a x86 cpu. This can lead to bugs caused by memory synchronization failures. Therefore, it is essential to have a native aarch64 CI target.

**Comment by elBoberido** [comment]
Done with #2071
