### ISSUE TITLE
RouDi on Windows does not kill application when terminated

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1226]
## Required information

**Operating system:**
Windows

The function to kill application in windows is implemented as stub. This lets application run even when RouDi is terminated. Implement the kill function would solve the issue.

**Comment by elBoberido** [comment]
@elfenpiff this is already a task item of #846

**Comment by elfenpiff** [comment]
I linked them together. I totally overlooked this but I think a small issue is not so wrong.

**Comment by dkroenke** [comment]
Closing since it is already addressed in https://github.com/eclipse-iceoryx/iceoryx/issues/846
