### ISSUE TITLE
HandleTranslator in Windows must be thread safe

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1264]
## Required information

**Operating system:**
Windows

**Compiler version:**
Every compiler

**Observed result or behaviour:**
Spurious failures in the CI and in Windows can be caused by opening/closes constructs concurrently which are using underlying file handles.
Normally, one can open files concurrently without problem but in windows the `HandleTranslator` is used to provide an uniform access to file handles. This construct is not threadsafe - this has to be changed.

**Comment by elBoberido** [comment]
can this be closed?

**Comment by elfenpiff** [comment]
It is only merged to the release branch and not to the master branch which is as well affected. Should we keep this open until `release_2.0` is merged to master @dkroenke ?
