### ISSUE TITLE
Don't exclude implementations of public classes in Doxygen

### ISSUE THREAD

**Issue by mossmaurice** [eclipse-iceoryx/iceoryx#1293]
## Brief problem description

Due to

```
set(DOXYGEN_EXCLUDE_PATTERNS "*/internal/*")
set(DOXYGEN_EXCLUDE_SYMBOLS "internal::*")
```

in `doc/aspice_swe3_4/CMakeLists.txt` most part of the public user API is not visible e.g. [`popo::Publisher`](https://iceoryx.io/v2.0.0/API-reference/posh/Classes/classiox_1_1popo_1_1Publisher/)

![image](https://user-images.githubusercontent.com/8661268/158805271-3cc55a97-7d83-423b-a692-fbb65f5202ca.png)

### Tasks

1. Re-write regular expression so that implementations of `popo::Publisher`, `popo::Subscriber` are not excluded
2. Add `set(DOXYGEN_INLINE_INHERITED_MEMB YES)` so that inherited methods and members are displayed

**Comment by elBoberido** [comment]
@mossmaurice I had an inspiration. What do you think about having and `impl` or similar folder, e.g.
```
include
   |- iceoryx_posh
      |- popo
      |   |- impl
      |      |- subscriber_base.hpp
      |      |- subscriber_impl.hpp
      |- subscriber.hpp
```
We need maybe a better name, but I guess you know what I mean.
With this we would still hide the `internal` header and could get the documentation from the base class.

**Comment by elBoberido** [comment]
@mossmaurice this was fixed with #1315 from the workaround on the release branch. It's different than the proposal above but still works. Are you in favor of a different solution or are you fine with the workaround?

**Comment by mossmaurice** [comment]
@elBoberido The workaround is ok for me long term. However, we should document this somewhere not to forget if e.g. new files are added. I suppose the `CONTRIBUTING.md` would be a good place. Can you add a few senteces there?

**Comment by dkroenke** [comment]
@mossmaurice @elBoberido Is here still something to do or not?
