### ISSUE TITLE
[Question] Does 2.0.0 run under windows? 

### ISSUE THREAD

**Issue by dotChris90** [eclipse-iceoryx/iceoryx#1300]
## Required information

**Operating system:**
Windows 10

**Compiler version:**
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29914 for x86

**Observed result or behaviour:**

First of all : it simple would like to know if iceoryx/2.0.0 is usable for windows 10.

I just tired to bring version 2.0.0 into conan-center and it looks already good for Linux, MacOS, x86_64 and ARM. 
But the tests for Windows fails. that i.e. to Build successful but tests usage fails. 

The build of iceoryx via conan is 100% following the manual steps - so the exported libs are taken from cmake install command. 
After build the libs and header files are present in package - all fine - but the usage of them breaks. The test usage is taken examples from iceoryx repo and i just would like to understand if i have to search on conan side or if currently 2.0.0 is not official supported by windows. 

The CMakeLists is --> https://github.com/dotChris90/conan-center-index/blob/Add_2_0_0/recipes/iceoryx/all/test_package/CMakeLists.txt
The C++ files --> https://github.com/dotChris90/conan-center-index/blob/Add_2_0_0/recipes/iceoryx/all/test_package/icedelivery/iox_publisher.cpp

My question is more - if I missing some compiler, linker flags for Windows - if 2.0.0 have Visual Studio compiler restrictions (currently just took the compiler i took from 1.0.1 last year). 

The compiler error details are :

https://c3i.jfrog.io/c3i/misc/logs/pr/9779/10-configs/windows-visual_studio/iceoryx/2.0.0//502aa5853f33cfa6c8105f29cbc76d64200b1ba4-test.txt

like " error C2279: exception specification cannot appear in a typedef declaration" or several others. 

**Expected result or behaviour:**
i expected no errors :D or i missed sth in release documents. 

**Conditions where it occurred / Performed steps:**
I would like to know if examples working for windows compiler and windows 10. that's all :D

**Comment by elBoberido** [comment]
@dotChris90 I'm not quite sure why you get this error. Our CI uses MSVC 19.29.30140.0. This is the latest build on the CI https://github.com/eclipse-iceoryx/iceoryx/runs/5603020731?check_suite_focus=true. Check out the output from `Run ./tools/ci/build-test-windows.ps1`

It might be related to #1076 which replaced `std::result_of` with `std::invoke_result`.

Maybe MSVC doesn't use the correct C++ version for some reasons.

**Comment by dotChris90** [comment]
@elBoberido thanks for C++ version hint. interesting is - iceoryx works with C++ 14 for linux and Mac but C++ 17 must be present for Windows - at least on my side. strange. but it worked thanks

**Comment by elBoberido** [comment]
@dotChris90 there were some issues with the C++14 support on MSVC but I cannot tell you exactly what. @elfenpiff knows more about the details.

**Comment by dotChris90** [comment]
@elBoberido its ok for me to know the reason. I already changed cmake file So Windows compiler take 17 and rest 14. That was already a working solution for me. Thanks 👍 i will close the Ticket when Conan center CI build finish. Local Windows is already working for me

**Comment by elBoberido** [comment]
@dotChris90 the weird thing is that we actually set the C++ version on Windows via target properties to C++17

**Comment by dotChris90** [comment]
@elBoberido yes and because 1.0.1 worked With 14 on Windows in my test I Set explicit to 14. So I guess here i can say it was my mistake . Because my cmake file which consume / using iceoryx Set Standard to 14. That's why iceoryx build worked but my test failed.

**Comment by dotChris90** [comment]
Close issue. CI build successful. Happy weekend and thanks
