### ISSUE TITLE
HEADER_VERSION error

### ISSUE THREAD

**Issue by sgf201** [eclipse-iceoryx/iceoryx#1305]
## Required information

**Operating system:**
Ubuntu 16.04 LTS

**Compiler version:**
GCC 5.4

**Observed result or behaviour:**
roudi running

**Expected result or behaviour:**
some error?

![image](https://user-images.githubusercontent.com/5253415/160335998-b57e7166-633e-4692-acc0-38f8ec8b0c2b.png)
 Received chunk with CHUNK_HEADER_VERSION '0' but expected '1'! Dropping chunk!
2022-03-28 14:02:29.521 [Warning]: ICEORYX error! POPO__CHUNK_QUEUE_POPPER_CHUNK_WITH_INCOMPATIBLE_CHUNK_HEADER_VERSION

**Comment by elBoberido** [comment]
@sgf201 do you have more information? This looks like two applications are build with different iceroyx versions, the sender did don initialize the chunk or someone overwrote the chunk-header.

**Comment by sgf201** [comment]
> 



> @sgf201 do you have more information? This looks like two applications are build with different iceroyx versions, the sender did don initialize the chunk or someone overwrote the chunk-header.

" build with different iceroyx versions" I am sure that all bins are build in same project.
 "the sender did don initialize the chunk or someone overwrote the chunk-header."  I loan the chunk ,then memcpy data to it and then send it by cyclonedds,  Is there other initialization needed?    and   "overwrote the chunk-header"  happens in any normal situation?

**Comment by sgf201** [comment]
> @sgf201 theoretically a loaned chunk should have a valid chunk-header so there are not many possibilities to end with this kind of error. I already mentioned the different iceoryx versions but that is also quite unlikely. Overwriting is more likely. Assuming you get the chunk-payload pointer, you would not be able to overwrite the chunk-header of the current chunk but the memory layout is like this
> 
> ```
> +------------+-------------+------------+-------------+------------+-------------+
> |chunk-header|chunk-payload|chunk-header|chunk-payload|chunk-header|chunk-payload|
> +------------+-------------+------------+-------------+------------+-------------+
> ```
> 
> One possible issue might be to override the chunk-header of the next chunk. Could you please double check if memcpy does not copy beyond the chunk limits? What version of cyclonedds are you using.
> 
> @MatthiasKillat since you are more familiar with cyclonedds maybe you also have some ideas.

![image](https://user-images.githubusercontent.com/5253415/160843880-44e8aceb-efb8-4b72-a085-14ce7b613d0b.png)
@elBoberido Do you mean that I write the header after the thunk I used now?

**Comment by elBoberido** [comment]
@sgf201 do you still have this issue?

**Comment by mossmaurice** [comment]
@sgf201 Closing this issue, feel free to re-open if you have further questions.
