### ISSUE TITLE
roudi crash and "Transport endpoint is not connect"

### ISSUE THREAD

**Issue by sgf201** [eclipse-iceoryx/iceoryx#1306]
## Required information

**Operating system:**
Ubuntu 16.04 LTS

**Compiler version:**
GCC 5.4

**Observed result or behaviour:**
ctrl+c to stop a program with children which are forked out 

**Expected result or behaviour:**
exit nomally

**Conditions where it occurred / Performed steps:**
runnint then press ctrl+c

![image](https://user-images.githubusercontent.com/5253415/160336541-89018709-99a6-4478-9e2b-ba4581f77c6d.png)

**Comment by sgf201** [comment]
https://github.com/eclipse-cyclonedds/cyclonedds/issues/1105
I am trying to use cyclonedds to replace another comm component ,the target APP 's fixed flow is：

main（）
{
init dds
do something;
dds read or write;
if(xxx)
{
if(fork()==0)
{
init dds;
while(1)
do something
dds read or write;
}
else
{
;;
}
}

}
I apply the patch https://github.com/eboasson/cyclonedds/commit/eff7e8208ea5c02dda72f206e5561748961b8334

**Comment by elBoberido** [comment]
@sgf201 that patch is only related to Cyclone DDS and doesn't handle anything iceoryx related. It would be a non-trivial task to enable forking after `initRuntime`. I guess that happens in the `init dds` call. Would it be feasible to fork before calling `init dds`?

**Comment by sgf201** [comment]
> @sgf201 that patch is only related to Cyclone DDS and doesn't handle anything iceoryx related. It would be a non-trivial task to enable forking after calling `initRuntime`. I guess that happens in the `init dds` call. Would it be feasible to fork before calling `init dds`?

the code frame is unchangeable.I can not move all fork before init dds.

on the other side, which kind of situation will cause the crashing of roudi,  thanks a lot

**Comment by elBoberido** [comment]
@sgf201 does roudi crash or the application?

There are a few issues:
- roudi needs to keep track of the running applications in order to clean up after the application shuts down. The registering happens with the `initRuntime` call
- in case there already resources used (pulisher, subscriber, listener, waitset, etc.) these will be corrupted when used in multiple applications
- in case there are already chunks loaned/received, forking will lead to double frees and kill the application

These are just a few issues from the top of my head

**Comment by elBoberido** [comment]
@sgf201 do you have a backtrace?

I guess the forked application corrupts some data which roudi expects to be valid until the application which called `initRuntime` shuts down.

**Comment by sgf201** [comment]
> @sgf201 do you have a backtrace?
> 
> I guess the forked application corrupts some data which roudi expects to be valid until the application which called `initRuntime` shuts down.

what does the corrupts mean? could you explain this more detailed，I thought roudi holdall the chunk，so app is hard to corrupts roudi‘s data

**Comment by elBoberido** [comment]
@sgf201 at first you need to check where the core dumps are stored
```
cat /proc/sys/kernel/core_pattern
```
If the output is something like
```
/lib/systemd/systemd-coredump %P %u %g %s %t 9223372036854775808 %h
```
then `coredumpctl -l` can be used to get a list of core files and `coredumpctl gdb 42691` to let gdb create a backtrace for process with PID 42691.
If the output is different, then a core file will be saved at the location of the output. You can then use `gdb --core path/to/core/file path/to/executable` to create the backtrace.

**Comment by elBoberido** [comment]
@sgf201 any updates? Do you still have crashes?

**Comment by mossmaurice** [comment]
@sgf201 Closing this issue, feel free to re-open if you have further questions.
