### ISSUE TITLE
Refactor Logger

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx#1345]
## Brief feature description

Log messages cannot be forwarded to another logging framework. To make this possible, the logger must be refactored.

## Detailed information

When iceoryx is used with another framework it is not possible to forward log messages to the native logger of the framework.

The logger shall be refactored to be able to to switch the backend at compile time or at runtime.

## Tasks

- [ ] Design document
- [x] Implement/refactor logger
- [x] Create a custom logger to print the log only for failed tests

**Comment by elfenpiff** [comment]
@elBoberido What do you think about dividing this issue in multiple sub issues? This issue is kept to keep track of the overall feature progress and every task gets its own issue which is linked in the task todo list here.

Then we can manage discussions at the right place and prevent comment cluttering in the main issue.

**Comment by elBoberido** [comment]
@elfenpiff I'm a bit torn on this. For me the design document, implementation and tests belong together in one issue. Integration might be a different issue.

The question is also how this is handled when someone does not use subtasks? Is this person then not allowed to have multiple PRs for the same issue? Do we enforce to have subtasks? What happens when someone notices that it might be better to split the implementation in multiple PRs after the implementation started? What happens when the implementation started with a small refactoring and the it turned out to make sense to have the refactoring as separate PR?

There is in general also not much discussions going on in the issue itself but on the PRs.

From my point of view the only problem this would solve is that issues are closed when a PR is merged. Everything else should be handled by the developer working on the feature and as little as possible should be enforced.

Regarding this feature, I'd like to have the design document, implementation and tests on the same issue. The remaining tasks shouldn't could then be moved to a separate issue but currently I don't feel that it would improve my workflow or save me time and it also does not have a negative impact on the reviewer.
