### ISSUE TITLE
Update Cyclone DDS maintainer

### ISSUE THREAD

**Issue by poetinger** [eclipse-iceoryx/iceoryx#1352]
## Brief feature description

**ADLINK Technology Ltd** is now **ZettaScale Technology**, thus the table `Where is Eclipse iceoryx used?` should be updated to reflect this change.

## Detailed information

In the table `Where is Eclipse iceoryx used?`, it lists _Cyclone DDS_ as maintained by [ADLINK Technology Inc.](https://www.adlinktech.com/en/index.aspx), this should be changed to **ZettaScale Technology** (currently the webiste is located at: https://zettascale.tech/). This might apply to more references of **ADLINK** if they exist in the code-base.

**Comment by elBoberido** [comment]
@poetinger thanks for the hint. We are a bit hesitant to change the links since the ZettaScale homepage is still a work in progress.

**Comment by poetinger** [comment]
@elBoberido Good point, I can check here that this will remain the homepage. I will also open a PR with the change, and will update this after confirming the website.

**Comment by poetinger** [comment]
I do not yet have the ECA signed, so somebody can take this commit as needed. I will update this thread again when I hear a positive response that the homepage will remain as linked in the commit.

**Comment by poetinger** [comment]
@elBoberido  I have confirmed that the address included in this commit is the correct address and will be the be address henceforth.

**Comment by elBoberido** [comment]
@poetinger signing the ECA is done within a few minutes but if you don't want to sign it, I can do the changes to the links.
