### ISSUE TITLE
Request publisher received no valid publisher port from RouDi.

### ISSUE THREAD

**Issue by niclar** [eclipse-iceoryx/iceoryx#1354]
we are getting errors in one of our publishers, despite roudi, publisher & subscriber restarts;

2022-05-11 09:18:21.163 [ Error ]: Request publisher received no valid publisher port from RouDi.
Condition: t != nullptr in iox::cxx::not_null<iox::popo::PublisherPortData *const, void>::not_null(T) [T = iox::popo::PublisherPortData *const] is violated. (/mnt/c/src/thirdparty/vcpkg/installed/x64-linux/include/iceoryx/v2.0.0/iceoryx_hoofs/cxx/helplets.hpp:87)
2022-05-11 09:18:21.163 [ Error ]: ICEORYX error! EXPECTS_ENSURES_FAILED

( iceoryx  e759b4daec065edf96cd8c23cb258bbfd6602e5f  v2.0.0 built with -DIOX_MAX_PUBLISHERS=1024 
and libcxx,  Ubuntu clang version 14.0.1-++20220426083040+0e27d08cdeb3-1~exp1~20220426083051.129 )

uname  -a
Linux cts1 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Please advice

**Comment by sun421-cloud** [comment]
hello, I also encountered this problem, may I ask how you finally solved it？
