### ISSUE TITLE
Compile Error :  iceoryx_dds/Mempool.hpp: No such file or directory

### ISSUE THREAD

**Issue by quanqixian** [eclipse-iceoryx/iceoryx#1364]
## Compile Error

**Operating system:**
Ubuntu 18.04.4 

**Compiler version:**
gcc version 7.5.0

**iceoryx version:**
iceoryx-2.0.2

**Problem Description:**

I try build as:

Build with script

```
cd iceoryx
./tools/iceoryx_build_test.sh build-all
```

Build with CMake

```
cmake -Bbuild -Hiceoryx_meta -DBUILD_ALL=ON -DCMAKE_INSTALL_PREFIX=./install
```

Both errors occurred

```
iceoryx-2.0.2/iceoryx_dds/include/iceoryx_dds/dds/cyclone_data_reader.hpp:21:10: fatal error: iceoryx_dds/Mempool.hpp: No such file or directory
```

I would like to know how to solve this problem, thanks a lot

**Comment by dkroenke** [comment]
What could help is that the CMake files in iceoryx expect to have CMake version 3.16 or greater installed, otherwise the build fails. (Hint: Ubuntu 18 users can install `cmake-mozilla` package from the universe repository provided by Canonical)

**Comment by quanqixian** [comment]
> 

I compiled the code using cmake version is 3.23.1

```
$ cmake -version
cmake version 3.23.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by quanqixian** [comment]
> @quanqixian Could you post an anonymized build log of your iceoryx build? That would help to understand the issue.

This is the final terminal output when the error occurs, and [here](https://github.com/quanqixian/iceoryx_build_log/blob/main/README.md) is the full compilation output

```
[ 64%] Linking CXX executable ../iox-introspection-client
[ 64%] Built target iox-introspection-client
[ 64%] Building CXX object iceoryx_dds/CMakeFiles/iceoryx_dds.dir/source/iceoryx_dds/log/logging.cpp.o
[ 64%] Building CXX object iceoryx_dds/CMakeFiles/iceoryx_dds.dir/source/iceoryx_dds/dds/cyclone_context.cpp.o
[ 64%] Building CXX object iceoryx_dds/CMakeFiles/iceoryx_dds.dir/source/iceoryx_dds/dds/cyclone_data_reader.cpp.o
In file included from /home/quan/gitee/OpenSourceSoftware/iceoryx/iceoryx_dds/source/iceoryx_dds/dds/cyclone_data_reader.cpp:18:0:
/home/quan/gitee/OpenSourceSoftware/iceoryx/iceoryx_dds/include/iceoryx_dds/dds/cyclone_data_reader.hpp:21:10: fatal error: iceoryx_dds/Mempool.hpp: No such file or directory
 #include "iceoryx_dds/Mempool.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
iceoryx_dds/CMakeFiles/iceoryx_dds.dir/build.make:103: recipe for target 'iceoryx_dds/CMakeFiles/iceoryx_dds.dir/source/iceoryx_dds/dds/cyclone_data_reader.cpp.o' failed
make[2]: *** [iceoryx_dds/CMakeFiles/iceoryx_dds.dir/source/iceoryx_dds/dds/cyclone_data_reader.cpp.o] Error 1
CMakeFiles/Makefile2:1444: recipe for target 'iceoryx_dds/CMakeFiles/iceoryx_dds.dir/all' failed
make[1]: *** [iceoryx_dds/CMakeFiles/iceoryx_dds.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2
quan@iZ2zeeq1jai7e6qn7xqrnuZ:~/gitee/OpenSourceSoftware/iceoryx$ 
quan@iZ2zeeq1jai7e6qn7xqrnuZ:~/gitee/OpenSourceSoftware/iceoryx$ find ./ -name Mempool.hpp
quan@iZ2zeeq1jai7e6qn7xqrnuZ:~/gitee/OpenSourceSoftware/iceoryx$ 
```

**Comment by elfenpiff** [comment]
@quanqixian 

Could you please try the following when the error has occurred
```sh
cd build/iceoryx_dds
make mempool_header
ls # this should list now the missing Mempool.hpp
```

If the approach from above does not work can you please try the following:
```sh
cd iceoryx
rm -rf build
cmake -Bbuild -Hiceoryx_meta -DBUILD_ALL=ON -DUSE_CYCLONE_DDS=ON
cd build
make
```

Did one or both approaches work? If so we seem to have some bug in our `CMakeLists.txt`

**Comment by dkroenke** [comment]
@quanqixian @elfenpiff 

The behaviour can be reproduced by building `iceoryx_dds` with only one core on make.
Problem is that the `custom_command` for generating the Mempool.hpp was not tied directly as dependency to the iceoryx_dds library. It was accidently working because when compiling on multiple cores (e.g. `make -j`) the generator was always earlier done before the compilation of iceoryx_dds start.

Adding `add_dependencies(iceoryx_dds mempool_header)` will force CMake to execute the mempool_header generation command first before compilation of iceoryx_ddds. Please test if that works for you.

**Comment by quanqixian** [comment]
> @quanqixian
> 
> Could you please try the following when the error has occurred
> 
> ```shell
> cd build/iceoryx_dds
> make mempool_header
> ls # this should list now the missing Mempool.hpp
> ```
> 
> If the approach from above does not work can you please try the following:
> 
> ```shell
> cd iceoryx
> rm -rf build
> cmake -Bbuild -Hiceoryx_meta -DBUILD_ALL=ON -DUSE_CYCLONE_DDS=ON
> cd build
> make
> ```
> 
> Did one or both approaches work? If so we seem to have some bug in our `CMakeLists.txt`

I tried both ways,
The first way successfully completed the compilation,
The second way still occurs this compilation error,
thank you for your reply.

**Comment by quanqixian** [comment]
> @quanqixian @elfenpiff
> 
> The behaviour can be reproduced by building `iceoryx_dds` with only one core on make and is not platform-specific. Problem is that the `custom_command` for generating the Mempool.hpp was not tied directly as dependency to the iceoryx_dds library. It was accidently working because when compiling on multiple cores (e.g. `make -j`) the generator was always earlier done before the compilation of iceoryx_dds start.
> 
> Adding `add_dependencies(iceoryx_dds mempool_header)` will force CMake to execute the mempool_header generation command first before compilation of iceoryx_ddds. Please test if that works for you.

Yes, as you said, I'm compiling on a single-core computer.
I tried your solution and the build completed successfully. 
thank you for your reply.
