### ISSUE TITLE
CMake config assumes relative `CMAKE_INSTALL_LIBDIR`

### ISSUE THREAD

**Issue by lopsided98** [eclipse-iceoryx/iceoryx#1393]
## Required information

**Operating system:**
Nix

**Compiler version:**
GCC 10.3.0

CMake allows the `CMAKE_INSTALL_*DIR` variables to be specified as absolute paths. This means they must not be concatenated with `CMAKE_INSTALL_PREFIX` in an attempt to form an absolute path. See here for more information: https://github.com/jtojnar/cmake-snips#assuming-cmake_install_dir-is-relative-path

`iceoryx_hoofs` [constructs `DESTINATION_CONFIGDIR` from `CMAKE_INSTALL_LIBDIR`](https://github.com/eclipse-iceoryx/iceoryx/blob/96de86cd21a0f9c090fda0685df32f9da34dad3b/iceoryx_hoofs/cmake/IceoryxPackageHelper.cmake#L38) and then concatenates it with `CMAKE_INSTALL_PREFIX` [in `Config.cmake.in`](https://github.com/eclipse-iceoryx/iceoryx/blob/96de86cd21a0f9c090fda0685df32f9da34dad3b/iceoryx_hoofs/cmake/Config.cmake.in). The same pattern occurs in `iceoryx_posh`.

This can be fixed by constructing `DESTINATION_CONFIGDIR` from `CMAKE_INSTALL_FULL_LIBDIR` and then getting rid of the concatenation in `Config.cmake.in`.

**Comment by lopsided98** [comment]
This happens with Nix/nixpkgs. Nix installs every package into an isolated directory, and we often want to split software into multiple packages (e.g. libraries, binaries and headers) to reduce installation size. Therefore, each of `CMAKE_INSTALL_*DIR` is specified as a different absolute path.

If you need an absolute path, you should use `CMAKE_INSTALL_FULL_*DIR`. Sometimes things like pkgconfig files need extra work to make them relocatable (ie. concat with prefix only if `CMAKE_INSTALL_*DIR` is relative), but that is not the case here.

**Comment by dkroenke** [comment]
Hey @lopsided98,
yes that sounds reasonable and a short test shows that the absolute path is correct like the previous one which is concatenated.
We would be happy if you bring 36f4917 as contribution to iceoryx. When you do this you can add an entry in the changelog: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md under the Bugfix section.
