### ISSUE TITLE
Slash in runtime names is interpreted as sub path

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1419]
## Required information

**Observed result or behaviour:**
It is impossible to create a runtime with an app name which has a slash since this is interpreted as path by some underlying constructs.

```cxx
iox::runtime::PoshRuntime::initRuntime("aaargh/aaaaaargh/whoopsie");
```

The problem is caused by multiple posix constructs:
* The `FileLock` which tries to create a file lock under `/tmp/aaargh/aaaaaargh/whoopsie.lock` but the sub folders are not existing
* The `UnixDomainSocket` which tries to create a unix domain socket in `/tmp/aaargh/aaaaaargh/whoopsie`
* The `NamedPipe` which tries to create a shared memory file handle also under such a subpath
* The `NamedSemaphore` in `NamedPipe` with the same issue.

**Solution:**

iceoryx restricts the runtime names to valid file names which the user can verify via `iox::cxx::isValidFileName` from `cxx/helplets.hpp`.

This wouldn't be exactly a public API change since application which non leading slashs in their name would only generate fatal errors in the corresponding posix wrappers when the path does not exist.
But if some smart user would create `mkdir -p /tmp/aaargh/aaaaaargh/` the application would run but since this is a very weird corner case I would dismiss it.

**Comment by elBoberido** [comment]
@elfenpiff is this really a breaking change? If I understand you correctly, this is already broken and we would now handle it more graceful
