### ISSUE TITLE
`GenericRAII` stores only a reference to cleanup function and renamed to `ScopeGuard`

### ISSUE THREAD

**Issue by MatthiasKillat** [eclipse-iceoryx/iceoryx#1450]
## Refactoring

1. Pass a cleanup function as function_ref instead of function (but store as function as is).
2. Rename into ScopeGuard

cf. https://stackoverflow.com/questions/31365013/what-is-scopeguard-in-c

**Comment by elBoberido** [comment]
@MatthiasKillat yes, the `ScopeGuard` terminology is already used by the C++ community
