### ISSUE TITLE
Roudi Environment independent from Googletest

### ISSUE THREAD

**Issue by dkroenke** [eclipse-iceoryx/iceoryx#1533]
## Brief feature description

Currently, the `iceoryx_posh_testing` library depends on `iceoryx_hoofs_testing` which depends itself on the GoogleTest library.
The RouDi environment is part of the posh testing library and offers a GTest "Binding" to make use of RouDi in GoogleTests: https://github.com/eclipse-iceoryx/iceoryx/blob/master/iceoryx_posh/testing/include/iceoryx_posh/testing/roudi_gtest.hpp

## Detailed information

The RouDi environment should maybe put into a separate library that is independent from GoogleTest to make it usable by other testing Frameworks.

**Comment by elBoberido** [comment]
This will be helpful for the Rust bindings and potentially also for other language bindings
