### ISSUE TITLE
SharedMemo: Unable to get MAC address for iceoryx

### ISSUE THREAD

**Issue by raizo27** [eclipse-iceoryx/iceoryx#1535]
## Required information

**Operating system:**
Ubuntu 20.04.4 LTS

**Compiler version:**
 GCC 7.4.0

**Observed result or behaviour:**
I wrote a minimum example to use iceoryx shared memory with Cyclone DDS c++. It works fine sometimes, but I sometimes observe below issue. I'm not sure why. Please let me know if you have seem this issue before, or you know how to solve it. Thanks.

> 2022-07-21 02:44:54.487 [Warning]: RouDi not found - waiting ...

> 2022-07-21 02:45:06.524 [Warning]: ... RouDi found.

>1658371506.530691 [0] SharedMemo: Unable to get MAC address for iceoryx

>=== [Publisher] Exception: Error Error - Could not create DomainParticipant.

>===============================================================================

>Context     : org::eclipse::cyclonedds::domain::DomainParticipantDelegate::DomainParticipantDelegate

>Node        : UnknownNode

**Comment by MatthiasKillat** [comment]
@raizo27 I did not look into the details yet, but the problem originates from CycloneDDS somewhere. It uses the MAC address to define a locator, which is essentially responsible to determine how to send the data. For iceoryx  it is more or less like this: if iceoryx is used and the same MAC address is determined, it will use shared memory.

Now apparently it sometimes fails to determine the MAC address but I do not know yet under which circumstances this may happen. When this happens it seems it will not proceed.

The required steps are to determine under which circumstances this may fail, ideally with a reproducible example. It is especially strange if it only fails sometimes (with the same setup).

@eboasson

**Comment by eboasson** [comment]
> I have not encountered this issue myself before.

Neither have I, but it can really only be a failure to find the selected network interface among the `AF_PACKET` capable interfaces. It would be interesting to know a bit more ...

Does it reproduce well enough that trying to catch it in [`rr`](https://rr-project.org) is worth it? That would at least allow setting a breakpoint in `ddsrt_eth_get_mac_addr` and then seeing what happened.

**Comment by mossmaurice** [comment]
@raizo27 As this seems an issue inside Cyclone DDS, let's move the discussion to https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/296. Feel free to re-open this issue if you have more questions.
