### ISSUE TITLE
Support Bazel build system (as alternative to CMake)

### ISSUE THREAD

**Issue by kwallner** [eclipse-iceoryx/iceoryx#1542]
## Brief feature description

Add support for building iceoryx with [Bazel](https://bazel.build/) build tool (as alternative build system to  [CMake](https://cmake.org/)).

## Detailed information

[Bazel](https://bazel.build/) provides advanced build features, supporting hermetic, reproducible and scalable builds. 

[Bazel](https://bazel.build/) could be added additionally - without breaking existing [CMake](https://cmake.org/) builds. 

Additional build files (`WORKSPACE.bazel` and `BUILD.bazel`) are needed as well as (maybe) some bazel rules (`.bzl`) located in a `bazel` subdirectory (like already existing `cmake` subdirectory).

**Comment by t0ny-peng** [comment]
I happen to run into this PR since I've been recently using Iceoryx in my own project. Happy to see you guys' name again!
