### ISSUE TITLE
`cxx::unique_ptr::get()` does not check for `nullptr` before access

### ISSUE THREAD

**Issue by mossmaurice** [eclipse-iceoryx/iceoryx#1571]
## Required information

**Operating system:**
Ubuntu 20.04.3 LTS

**Compiler version:**
GCC 8.4.0

**Observed result or behaviour:**
Accessing an empty `unique_ptr` leads to a crash

**Expected result or behaviour:**
Accessing an empty `unique_ptr` shall lead to a fatal error (defined behaviour)

**Conditions where it occurred / Performed steps:**
Call `unique_ptr::get()` on empty object

**Comment by elBoberido** [comment]
@mossmaurice can we make this a check for debug builds only?

When we refactor the release method to a static method like `static T* release(unique_ptr<T>t&& p)` clang-tidy would essentially find every occurrence where `unique_ptr` contains a `nullptr`.

**Comment by elBoberido** [comment]
Okay, then this would qualify to an `IOX_DEBUG_ASSERT` which @MatthiasKillat wants to implement? Of course only after we can ensure that there actually won't be a `nullptr` except for moved-from objects
