### ISSUE TITLE
The posix call `unlink` is directly used in `UnixDomainSocket`

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1622]
## Required information

The posix call `unlink` can fail but is nevertheless directly used in the `UnixDomainSocket`. We need to handle the all `unlink` errors and wrap it into the `posixCall`.

**Comment by mossmaurice** [comment]
@elfenpiff I think you mean this line, right?

https://github.com/eclipse-iceoryx/iceoryx/blob/2dd519cd0ba4368af6d497cab2356bb4b396c027/iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp#L181

**Comment by elfenpiff** [comment]
> @elfenpiff I think you mean this line, right?
> 
> https://github.com/eclipse-iceoryx/iceoryx/blob/2dd519cd0ba4368af6d497cab2356bb4b396c027/iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp#L181
> 
> cc @zmostafa

Yes

**Comment by zmostafa** [comment]
@elfenpiff Thanks for the clarification, I did the change in PR #1870 , heads-up that's my first PR and still getting familiar with the code base and the process.

Thanks @mossmaurice for your support.
