### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by deneschen** [eclipse-iceoryx/iceoryx#1624]
![image](https://user-images.githubusercontent.com/8281561/189566627-40e988a2-094f-492d-b761-82042c5271fb.png)

**Comment by 675816156** [comment]
@rotu @lygstate @clalancette @BH1SCW @

**Comment by elfenpiff** [comment]
@675816156 Thanks for finding the issue. If you like you can create a pull request and adjust the document.

**Comment by 675816156** [comment]
谢谢来信！您的邮件,陈俊已经收到。

**Comment by elfenpiff** [comment]
@675816156 Could you please use english (or C++ ;) ) in all your contributions since we would like the whole community to be able to follow up on every issue.

**Comment by 675816156** [comment]
jun in ubuntu in iceoryx on  typo [⇡] took 2s
❯ git push origin typo:typo-1624
remote: Permission to eclipse-iceoryx/iceoryx.git denied to 675816156.
fatal: unable to access 'https://github.com/eclipse-iceoryx/iceoryx.git/': The requested URL returned error: 403

I'm not allowed to commit?what's wrong with my account?

**Comment by 675816156** [comment]
@elfenpiff

**Comment by elfenpiff** [comment]
@675816156 This is correct. To contribute you have to fork iceoryx to your account, create a branch with `iox-ISSUE_NUMBER` as prefix like in your case `iox-1624-fix-typo` and create a pull request.

Furthermore, you have to sign the ECA. See this here: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#feature-request-and-bugs

We are looking forward to your pull request :smile:
