### ISSUE TITLE
Add -Wconversion for clang and tests

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx#163]
## Brief feature description

Enable`-Wconversion` for clang builds and tests.

## Detailed information

Currently `-Wconversion` is disabled for clang builds and tests since there are way to many warnings. This warnings needs to be fixed and the warning should be enabled for clang builds.

- [x] `-Wconversion` for clang builds
- [x] `-Wconversion` for tests

**Comment by dkroenke** [comment]
@elBoberido the basic job is done, do you want also to add the flag in the test code?

**Comment by elBoberido** [comment]
@dkroenke if it currently compiles without warnings, sure

**Comment by dkroenke** [comment]
@elBoberido These warnings are fixed when Clang-Tidy was introduced, we have no exclusion in our test code. Closing this foiw now.
