### ISSUE TITLE
Use `GTEST_SKIP` for disabled tests

### ISSUE THREAD

**Issue by dkroenke** [eclipse-iceoryx/iceoryx#1635]
## Brief feature description

In iceoryx we currently disable google tests by setting `DISABLED_` as prefix in the name of the test case.
A better option is to use: 
```
GTEST_SKIP() << "Some reason to skip this test with ticket number iceoryx/#10200";
```

- [ ] Update all disabled test cases with the macro
- [ ] Update documentation for Contributors

**Comment by elfenpiff** [comment]
This is a great idea. This is also the perfect solution to skip tests for certain platforms. For instance we could introduce a platform enum in the iceoryx_platform and check without macros if we are on a certain platform and then disable the test with `GTEST_SKIP()`.

This would be so much cleaner than the ifdef macros.
