### ISSUE TITLE
`acl_entry_t` leak in posix wrapper `AccessController`

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1646]
## Required information

In method `AccessController::createACLEntry` an `acl_entry_t` is created with `acl_create_entry` but never free'd with `acl_free` like it is described in https://linux.die.net/man/3/acl_create_entry

This leads to a memory leak.

**Comment by elBoberido** [comment]
@elfenpiff by looking at the code this does not seem to be an issue. `acl_create_entry` is called with the value from `acl_init` and that value is already freed with `acl_free`. From my understanding this is sufficient.

**Comment by elfenpiff** [comment]
@elBoberido I was mistaken here. `acl_free` gets the root acl entry has a pointer and releases everything that was attached to the root node, therefore also releasing all allocated acl entries.
