### ISSUE TITLE
Investigate whether includes can be optimized

### ISSUE THREAD

**Issue by neillangmead41** [eclipse-iceoryx/iceoryx#1704]
## Required information

**Operating system:**
E.g. Ubuntu 18.04 LTS

**Compiler version:**
E.g. GCC 7.4.0

**Observed result or behaviour:**
A clear and precise description of the observed result.

**Expected result or behaviour:**
What do you expect to happen?

**Conditions where it occurred / Performed steps:**
Describe how one can reproduce the bug.

**Comment by neillangmead41** [comment]
Are all #includes in iceoryx required? Some preprocessing analysis suggests not. The goal of this ticket is to try to identify and reduce the number of includes if possible. This will also impact metrics such as coupling, connectedness, relevant for FUSA work.

**Comment by elBoberido** [comment]
@mossmaurice was this intentionally closed?

**Comment by mossmaurice** [comment]
@elBoberido It closed by merging #1738. If @neillangmead41 has more includes to optimize we can re-open this issue.
