### ISSUE TITLE
Fix segfault in `iox_cheeky_app.cpp` in ice_access_control example

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1708]
## Required information

When a subscriber is created without any readable shared memory segment it segfaults. This should not segfault in the example since this could be a valid use case. We have to provide a sensible error code instead.

**Comment by mossmaurice** [comment]
@elfenpiff Isn't that a duplicate of #722?

**Comment by elfenpiff** [comment]
Yes it seems so
