### ISSUE TITLE
Refactor service description and remove class hash, scope and interface

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1715]
## Brief feature description

In the capro service description are still 3 members were it is unclear if they are currently in use or if they are ever gonna be useful. Check their relevance and remove them if necessary.

**Comment by FerdinandSpitzschnueffler** [comment]
@elfenpiff This is a duplicate of #1141.

**Comment by elfenpiff** [comment]
Yes it is!
