### ISSUE TITLE
Move macro code from `cxx/attributes.hpp` into `iceoryx_platform`

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1726]
## Brief feature description

Attributes like `IOX_NO_DISCARD` provide the same functionality even on platforms which do not support them natively or at least let the code compile without warning.
This functionality requires platform/compiler dependent macros and should be moved to `iceoryx_platform` to remove those macros.

**Comment by elBoberido** [comment]
We have to be careful with this. Ideally the platform could depend on the `primitives` module but then the platform must be in hoofs. Maybe we can have a `common` folder in platform and add an include trampoline for `attributes.hpp` in hoofs.

**Comment by mossmaurice** [comment]
Picking up this issue and start working on it.
