### ISSUE TITLE
`vector::capacity()` should be `static constexpr`

### ISSUE THREAD

**Issue by JakubSosnovec** [eclipse-iceoryx/iceoryx#1747]
## Brief feature description

The type `iox::cxx::vector` has the method `capacity()` which could be `static constexpr`. This is completely analogous to the `iox::cxx::string` type, which already has `static constexpr` method `capacity()`.

## Detailed information

I think this only has benefits, no drawbacks :)

**Comment by mossmaurice** [comment]
Closing as it was implemented on #1729
