### ISSUE TITLE
Add equality operators to `cxx::variant` and `cxx::expected`

### ISSUE THREAD

**Issue by mossmaurice** [eclipse-iceoryx/iceoryx#1751]
## Brief feature description

Add the equality operators `operator==()` and `operator!=()` to `cxx::variant` and `cxx::expected` outside of the class to follow AUTOSAR rule `A13-5-5`.

**Comment by elfenpiff** [comment]
Neither `expected` nor `variant` have implemented a comparison operator so why add them now? What kind of purpose/feature would we cover with it?
