### ISSUE TITLE
return err when init a  cyclonedds reader 

### ISSUE THREAD

**Issue by sgf201** [eclipse-iceoryx/iceoryx#1761]
## Required information
iox-roudi:
**Operating system:**
Ubuntu 16.04 LTS

**Compiler version:**
E.g. GCC 5.4.0

app:
**Operating system:**
Ubuntu 16.04 LTS

**Compiler version:**
E.g. GCC 7.5.0

**Observed result or behaviour:**
failed to creat a cyclonedds reader (using iceoryx)

**Expected result or behaviour:**
creat reader successfully

![75e183c6-d457-4447-85b7-2368ac2e3d8c](https://user-images.githubusercontent.com/5253415/197563528-f4964061-326b-42fb-8150-00fa103fd5e3.jpeg)

**Comment by elfenpiff** [comment]
@sgf201 it looks like that somehow roudi is not running since it would create exactly this shared memory segment. Otherwise if roudi does not run you would not be able to startup at all.

Is it possible that some process cleaned up files in `/dev/shm`?

**Comment by sgf201** [comment]
> @sgf201 it looks like that somehow roudi is not running since it would create exactly this shared memory segment. Otherwise if roudi does not run you would not be able to startup at all.
> 
> Is it possible that some process cleaned up files in `/dev/shm`?

"IPCRM -ALL "will causethis?

**Comment by elfenpiff** [comment]
@sgf201  > "IPCRM -ALL "will causethis?

I think you had a little caps lock incident there :smiley: .

You are right, the command `ipcrm -all` causes this. When you call this command before you start any iceoryx application or roudi you should be fine otherwise very weird things may happen.

**Comment by elBoberido** [comment]
@sgf201 can this issue be closed?
