### ISSUE TITLE
Separate container logic from capacity template argument

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1775]
## Brief feature description

Currently the iceoryx_hoofs container like `vector`, `stack` etc. are fixed size with a capacity argument. To improve their test-ability we have to separate the implementation from the template capacity argument.

This means we introduce to every class a `myClass_implementation` where the whole logic is implemented and the actual `myClass` inherits from `myClass_implementation` and only provides the required memory.

This means `myClass_implementation` stores a pointer to the memory and the capacity of it but acts like the memory would be fixed size and is owned by an upper instance which takes care of the ownership.

**Comment by mossmaurice** [comment]
@elfenpiff Is this issue still needed or can it be closed?

**Comment by elfenpiff** [comment]
Out of date
