### ISSUE TITLE
CI warnings on github actions

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx#1781]
## Required information

Currently our CI issues multiple warnings on github actions. 

- `The 'set-output' command is deprecated and will be disabled soon`
    - [x] `lycheeverse/lychee-action`: fixed in v1.5.2
    - [x] `Ana06/get-changed-files`: there is an open [PR](https://github.com/Ana06/get-changed-files/pull/20)
    - [x] `egor-tensin/setup-gcc`: fixed with 1.3 which should automatically be used by the CI
    
- `Node.js 12 actions are deprecated ... Please update the following actions to use Node.js 16`
    - [x] `jwlawson/actions-setup-cmake`: fixed in v1.13
    - [ ] `ros-tooling/setup-ros`: there is an open [PR](https://github.com/ros-tooling/setup-ros/pull/521)

- `The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead`
    - [ ] build-test-ubuntu-with-gcc54 runs on ubuntu 20.04
        - gcc-5 is not in the repository anymore
        - maybe https://ftp.gnu.org/gnu/gcc/gcc-5.3.0/ can be used

- `macOS-latest pipelines will use macOS-12 soon`
    - we use `macos-latest` and it should not be a problem to run on macOS-12

**Comment by elBoberido** [comment]
@dkroenke I think you already know it but there are less than two months until the ubuntu 18.04 runner will be removed. We should look at my proposal with https://ftp.gnu.org/gnu/gcc/gcc-5.3.0/ in March

**Comment by dkroenke** [comment]
@elBoberido Yes that on my list, I will create a PR for this.
