### ISSUE TITLE
Add implementation of std::span to iceoryx_hoofs

### ISSUE THREAD

**Issue by ithier** [eclipse-iceoryx/iceoryx#180]
## Brief feature description
The std::span STL feature from C++20 will be useful for working with byte arrays in iceoryx.

## Detailed information
See: 
* https://en.cppreference.com/w/cpp/container/span
* https://en.cppreference.com/w/cpp/container/span/begin

One use-case is for passing around pointers to byte arrays to a function.
Usually, some checks need to be done in the function to ensure the array is valid (i.e. nullptr check, size validation).
With std::span, all of this logic is done automatically and the function doesn't need to reimplement it.

**Comment by patdhlk** [comment]
I'm working on the it, I hope a fist version is available beginning next week
