### ISSUE TITLE
Is it possible to increase chunks dynamically

### ISSUE THREAD

**Issue by sgf201** [eclipse-iceoryx/iceoryx#1801]
## Brief feature description

chunks defined in iox.toml may be not enouth in some corner case, Is it possible to malloc some mem for new chunks in the corner case,

## Detailed information

chunks are planned to set enough,but process is stuck in loan sample is not a good action

**Comment by elfenpiff** [comment]
@sgf201 Could you please elaborate the use case a bit more in detail.

As far as I understand this.
* You configure a custom memory configuration
* You go out of chunks and cannot acquire anymore samples with `publisher.loan()`.
* The option to provide more chunks in the memory config is not an option? Why?

The reason for the `iox.toml` memory config is that with this we are able to guarantee that there is always a fixed amount of memory available for you - if we go the route with malloc (or in the end with acquiring more shared memory) we cannot make this guarantee anymore which is essential for a safety critical framework.

So the options you have is only to increase the amount of chunks available and follow this documentation here: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/configuration-guide.md#configuring-mempools-for-roudi

But when you go more into the details of your use-case we may can come up with a better fitting one.
