### ISSUE TITLE
`iox::cxx::expected::operator bool` has wrong doxygen comment

### ISSUE THREAD

**Issue by JakubSosnovec** [eclipse-iceoryx/iceoryx#1812]
## Required information

**Operating system:**
All OSs

**Compiler version:**
All compilers

**Observed result or behaviour:**
Look here: https://github.com/eclipse-iceoryx/iceoryx/blob/master/iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp#L239
The `operator bool` doxygen comment is actually completely opposite of its behaviour!

**Expected result or behaviour:**
The comment should specify that `operator bool` actually returns true if the `expected` instance signals success.

**Conditions where it occurred / Performed steps:**

**Comment by mossmaurice** [comment]
Closing this issue as it was fixed on #1728.
