### ISSUE TITLE
There is an exception during debugging, but there is no problem in the running state.

### ISSUE THREAD

**Issue by byrnexu** [eclipse-iceoryx/iceoryx#1816]
## Required information

**Operating system:**
Ubuntu 20.04.5 LTS

**Compiler version:**
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 

**Observed result or behaviour:**
program crash during debugging

**Expected result or behaviour:**
Can be debugged normally

**Conditions where it occurred / Performed steps:**
When using gdb to debug a program

<img width="1870" alt="微信图片_20221203111443" src="https://user-images.githubusercontent.com/24740973/205419783-a58ff9b2-5c8e-4ed8-95f2-c6b72c52271c.png">

**Comment by elfenpiff** [comment]
@byrnexu I see in the stack trace that you run into the error handler. Could you please also add the error message and full log output to the issue.

My idea why this crashes is that the mutex lock receives a `SIGINT` signal from the debugger and our current policy is to repeat the call 5 times and then fail (where I have to admit that this is not the best strategy).

But if you are running into some timeout than @mossmaurice solution should solve the issue.

**Comment by byrnexu** [comment]
> @byrnexu Thanks for creating this issue! Which iceoryx version are you running?
> 
> Often, during debugging the monitoring feature can kick in, cleaning up the resource of unresponsive apps and should be disabled by starting RouDi with `./iox-roudi -m off`. If you are on `master` this feature was recently disabled by default (#1580).

Hello, I am running version 2.0.2
