### ISSUE TITLE
Can not build `iceoryx` with gcc 9.4

### ISSUE THREAD

**Issue by zmostafa** [eclipse-iceoryx/iceoryx#1871]
## Required information
Building `iceoryx` from source using gcc-9.4 yield the following error 

```
[ 17%] Building CXX object hoofs/test/CMakeFiles/hoofs_moduletests.dir/moduletests/test_cxx_vector.cpp.o
In file included from /home/ziad.mostafa/ade-home/iceoryx/iceoryx_hoofs/container/include/iox/uninitialized_array.hpp:119,
                 from /home/ziad.mostafa/ade-home/iceoryx/iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp:24,
                 from /home/ziad.mostafa/ade-home/iceoryx/iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp:18:
/home/ziad.mostafa/ade-home/iceoryx/iceoryx_hoofs/container/include/iox/detail/uninitialized_array.inl: In member function ‘virtual void {anonymous}::vector_test_EmplaceAtPositionAfterEndBeforeCapacityExceedsFails_Test::TestBody()’:
/home/ziad.mostafa/ade-home/iceoryx/iceoryx_hoofs/container/include/iox/detail/uninitialized_array.inl:40:72: error: iteration 2305843009213693951 invokes undefined behavior [-Werror=aggressive-loop-optimizations]
   40 |     return *reinterpret_cast<const ElementType*>(&m_buffer.value[index]);
      |                                                                        ^
In file included from /home/ziad.mostafa/ade-home/iceoryx/iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp:239,
                 from /home/ziad.mostafa/ade-home/iceoryx/iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp:18:
/home/ziad.mostafa/ade-home/iceoryx/iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl:188:48: note: within this loop
  188 |     for (uint64_t i{sizeBeforeEmplace - 1U}; i > position; --i)
      |                                              ~~^~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [hoofs/test/CMakeFiles/hoofs_moduletests.dir/build.make:466: hoofs/test/CMakeFiles/hoofs_moduletests.dir/moduletests/test_cxx_vector.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1218: hoofs/test/CMakeFiles/hoofs_moduletests.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Operating system:**
 Ubuntu 20.04 LTS

**Compiler version:**
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 

**Observed result or behaviour:**
A clear and precise description of the observed result.

`EmplaceAtPositionAfterEndBeforeCapacityExceedsFails` testcase fails due to `error: iteration 2305843009213693951 invokes undefined behavior [-Werror=aggressive-loop-optimizations]`

**NOTE: a strange behavior, when I swapped line 1515 and 1516, the testcase passed** 

**Expected result or behaviour:**
What do you expect to happen?
iceoryx should be built without errors as the `installation` did not specify a version upper-limit for gcc 
`[GCC](https://gcc.gnu.org/), 8.3 or later (5.4 currently supported too)`

**Conditions where it occurred / Performed steps:**
Describe how one can reproduce the bug.
1. clone `iceoryx` 
2.  `cmake -Bbuild -Hiceoryx_meta -DBUILD_ALL=ON -DBUILD_SHARED_LIBS=ON -DEXAMPLES=ON -DINTROSPECTION=ON -DBUILD_STRICT=ON -DBUILD_TEST=OFF`
3. `cmake --build build`

**Comment by elfenpiff** [comment]
@zmostafa We try to cover as much compiler versions as possible but sometimes gcc and other introduce in some version a faulty static-code analysis.

The solution is that you adjust your cmake command and use `-DBUILD_STRICT=OFF` to solve the issue. We try that the newest compilers do not cause any warnings but with the older ones it is not always possible.

**Comment by zmostafa** [comment]
@elfenpiff Understood, may I propose a small change in the documentation then ? fixing the compiler version with `-DBUILD_STRICT` would save other some troubles, or ?

**Comment by zmostafa** [comment]
@elBoberido I tried the proposed code snippet and the test passes.

> you mentioned also has switched testing off, which should not compile test_cxx_vector.cpp.

That is something I noticed while creating the build, that this parameter is somehow overridden and the code still build with testing, I will look into that and report the findings in a separate issue.

**Comment by elBoberido** [comment]
@zmostafa great. Please open a PR for the fix.

I think the issue with `-DBUILD_TEST=OFF` not working is that `-DBUILD_ALL=ON` overrides it
