### ISSUE TITLE
Slow git hooks

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx#1877]
## Required information

**Operating system:**
all

**Compiler version:**
all

**Observed result or behaviour:**
The clang-tidy checks runs even for files not present in '.clang-tidy-diff-scans.txt' which can take quite long. The check should only be performed for the files listed in '.clang-tidy-diff-scans.txt'.

Additionally, the check for missing test IDs is also quite slow. This is related to the search for the actual file with the missing IDs. There could be a fast sanity check with a slower follow up search if the first check fails.

**Expected result or behaviour:**
Fast commits without having time for too much coffee.

**Conditions where it occurred / Performed steps:**
Change a file in `iceoryx_dust` or `iceoryx_posh` and commit with the hooks enabled.

**Comment by dkroenke** [comment]
@elBoberido @elfenpiff 

> The clang-tidy checks runs even for files not present in '.clang-tidy-diff-scans.txt' which can take quite long. The check should only be performed for the files listed in '.clang-tidy-diff-scans.txt'.

It depends on what we want. Either we scan only files from the list with faster speed but at the cost that newly added files could be skipped eventually and bring more technical depth into the code base.
The purpose of scanning all files was to motivate fixing code outside of the diff scan list for reducing technical depth but yes this comes at the cost of an increased scan time.

**Comment by elBoberido** [comment]
@dkroenke the check will be performed for new files and for modified files listed in `.clang-tidy-diff-scans.txt`, similar to what the CI does.
