### ISSUE TITLE
When my program runs for a while, it crashes after displaying the "value too large for defined type" error .

### ISSUE THREAD

**Issue by byrnexu** [eclipse-iceoryx/iceoryx#1883]
## Required information

**Operating system:**
 Ubuntu 20.04 LTS

**Compiler version:**
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 

**Observed result or behaviour:**
iceoryx version 2.0.2
When my program runs for a period of time, the following error occurs, what is the reason, thank you!
<img width="1895" alt="1675817123032" src="https://user-images.githubusercontent.com/24740973/217400389-d510ac1e-1939-42c1-baa2-f9f6cfa64b09.png">
Of course this is most likely my problem.

**Expected result or behaviour:**
not crash

**Comment by elfenpiff** [comment]
@byrnexu So the problem you encounter originates in the semaphore which is used to signal events like when the publisher has delivered a sample to the subscriber.

If the subscriber is attached to a waitset and you never call `waitset->wait()` those notifications pile up. The semaphore uses internally an integer and this has a maximum value. If you exceed the value by calling to often `sem_post` (the function the publisher calls when a sample was delivered) without calling `sem_wait` (which is done by `waiset->wait()`) the number will reach its maximum value and the system prints this nice little error message.

So depending on the system the max semaphore value is 65535 (mac os), 2147483648 (linux) or even greater or smaller.

So a first idea would be:
* Do not use a waitset without handling the received events, see `waitset->wait()`

If this does not work or you didn't use a waitset at all I would require a little bit more context.
* Is this error originating in `iox-roudi` or in an `app`
* Does this error occur in an app with a `publisher`?
* Do you use other constructs `UserTrigger` in combination with a waitset?

**Comment by byrnexu** [comment]
thank you for your reply! From the code below, I have to call waitSet.wait.

```
 void SHMIPCBase::init() {
   keepRunning_.store(true);
   beforeInit();
 
   instanceWithIdentity_ = instance_;
   if (clientChannel_ != std::nullopt) {
     instanceWithIdentity_ = fmt::format("{}-{}", instance_, *clientChannel_);
   }
   subscriberName_ = fmt::format("{}{}{}{}{}", service_, SEP_OF_SHM_SVC,
                                 instanceWithIdentity_, SEP_OF_SHM_SVC, event_);
 
   subscriber_ = new iox::popo::UntypedSubscriber(
       {iox::capro::IdString_t(iox::cxx::TruncateToCapacity, service_),
        iox::capro::IdString_t(iox::cxx::TruncateToCapacity,
                               instanceWithIdentity_),
        iox::capro::IdString_t(iox::cxx::TruncateToCapacity, event_)},
       makeSubscriberOptions());
   subscriber_->subscribe();
   LOG_I("Create subscriber. {} [{}]", appName_, subscriberName_);
 
   shutdownTrigger_ = new iox::popo::UserTrigger();
   waitset_ = new iox::popo::WaitSet<>();
   waitset_->attachEvent(*shutdownTrigger_).or_else([this](auto) {
     LOG_E("Failed to attach shutdown trigger. {} [{}]", appName_,
           subscriberName_);
   }); 
 
   waitset_
       ->attachEvent(
           *subscriber_, iox::popo::SubscriberEvent::DATA_RECEIVED,
           iox::popo::createNotificationCallback(dataInSHMRecvCallback, *this))
       .or_else([this](auto) {
         LOG_E("Failed to attach subscriber. {} [{}]", appName_,
               subscriberName_);
       });
 
   afterInit();
}

 void SHMIPCBase::dataInSHMRecvCallback(
     iox::popo::UntypedSubscriber* const subscriber, SHMIPCBase* self) {
   while (self->subscriber_->hasData()) {
     self->subscriber_->take()
         .and_then([&](const void* userPayload) {
           auto chunkHeader =
               iox::mepoo::ChunkHeader::fromUserPayload(userPayload);
           if (self->dataRecvCallback_) {
             self->dataRecvCallback_(userPayload,
                                     chunkHeader->userPayloadSize());
           }
           subscriber->release(userPayload);
         })
         .or_else([self](auto& result) {
           if (result != iox::popo::ChunkReceiveResult::NO_CHUNK_AVAILABLE) {
             LOG_E("Error receiving chunk. {} [{}]", self->appName_,
                   self->subscriberName_);
           }
         });
   }
 }

 void SHMIPCBase::start() {
   init();
   isReady_.store(true);
   LOG_I("Start SHM IPC Channel. {} [{}]", appName_, subscriberName_);
   futureDataInSHMRecv_ =
       std::async(std::launch::async, [this]() { startDataInSHMRecvThread(); });
 }
 
 void SHMIPCBase::startDataInSHMRecvThread() {
   while (keepRunning_.load()) {
     auto notificationVector = waitset_->wait();
     for (auto& notification : notificationVector) {
       (*notification)();
     }
   }
 }
```
- Is this error originating in iox-roudi or in an app
error originating in an app.
- Does this error occur in an app with a publisher?
yes.
- Do you use other constructs UserTrigger in combination with a waitset?
From the code above, I have a shutdownTrigger

**Comment by byrnexu** [comment]
I found that it might be my problem. There is a compilation task in the background that deletes the running app, which may be caused by this reason.

**Comment by elfenpiff** [comment]
> I found that it might be my problem. There is a compilation task in the background that deletes the running app, which may be caused by this reason.

@byrnexu This is at least not supported by iceoryx ;)

I also looked over your code and you use the waitset correctly. So if you encounter this issue again, ping me here and we have to dig deeper into this.
