### ISSUE TITLE
nanoseconds in units::Duration are truncated

### ISSUE THREAD

**Issue by dkroenke** [eclipse-iceoryx/iceoryx#190]
## Required information

**Operating system:**
on aarch64 targets like Raspberry PI

**Compiler version:**
E.g. GCC 9.3.0

**Observed result or behaviour:**
The Posix Timer is getting double values on the API which are then converted into int64_t internally. This conversion leads to a loss of data because the compiler will truncate the value. This can lead to abnormal behaviour when using small numbers like 1 nanoseconds.

**Expected result or behaviour:**
Remove the double literals from the posix timer API and expect only integer als time values. Then we avoid this constraint and have a clean calculation.

**Conditions where it occurred / Performed steps:**
Try to start a timer with 1 nanosecond waiting time. It will no execute because the time is internally set to zero. This disarms the timer and it is not proceeding.

**Comment by budrus** [comment]
I can confirm. But first lost some time my Pi before finding this issue...

**Comment by elBoberido** [comment]
@dkroenke I think this related to the underlying `long double` of `units::Duration`. Should we rephrase this bug to fix the problem on its source?

@elfenpiff suggested in #337 to use
```c++
struct duration_t {
     uint64_t seconds;
     uint32_t nanoseconds;
};
```
as base instead of `long double`
