### ISSUE TITLE
Unsent chunk of publisher leaked after publisher exit unnormally

### ISSUE THREAD

**Issue by qujian** [eclipse-iceoryx/iceoryx#1936]
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Compiler version:**
GCC 7.5.0

**Eclipse iceoryx version:**
`v2.0.2`

**Observed result or behavior:**
`Chunk In use` of the iox-introspection-client should be 0 after the `iceperf-bench-leader` process exit directly.
```
MemPool | Chunks In Use |    Total | Min Free | Chunk Size |Chunk Payload Size  
--------------------------------------------------------------------------------
       1 |             1 |        2 |        0 |        168 |          128    
```
**Steps to Reproduce**

1. run the following programs normally:

`./iceperf-bench-leader -n 100 -t iceoryx-cpp-api`
`./iceperf-bench-follower`
`./iceperf-roudi`
`./iox-introspection-client --all`

2. add code like following file(or send Ctrl-C to the `./iceperf-bench-leader` ):
`iceoryx_examples/iceperf/iceoryx.cpp` in `sendPerfTopic()` method:

```cpp
    m_publisher.loan(payloadSizeInBytes).and_then([&](auto& userPayload) {
        auto sendSample = static_cast<PerfTopic*>(userPayload);
        sendSample->payloadSize = payloadSizeInBytes;
        sendSample->runFlag = runFlag;
        std::cout << std::endl << "going to exit(0)! ..." << std::endl;
        std::exit(0);
        std::cout << "never go this line!!!" << std::endl;
        m_publisher.publish(userPayload);
```

3. the `iceperf-bench-leader` will exit immediately, and start it again.

From the second time restart of `iceperf-bench-leader`, the `Chunk In Use` grow up to 1.

```
MemPool | Chunks In Use |    Total | Min Free | Chunk Size |Chunk Payload Size  
--------------------------------------------------------------------------------
       1 |             1 |        2 |        0 |        168 |          128    
```
And after the third time, the `Chunk In Use` grow up to 2.

**Analysis**
The code will exit immediately without send any message, but the unsent chunk should be released by RouDi process after the RouDi detect the leader process exit.

Any idea to make up for these scenarios? Thanks.

**Comment by elBoberido** [comment]
@qujian oh btw, having two chunks in use is totally okay. The leader as well as the follower are holding two chunks, one which was received and the new one which will be published. The time for this is short but since there is no sleep between the transmission the chance is quite high that the introspection samples its data during this period of time.

**Comment by mossmaurice** [comment]
Closing this issue. Feel free to reopen if there are more questions.
