### ISSUE TITLE
iox::popo::UntypedSubscriber store and expose creation parameters (QueueFullPolicy)

### ISSUE THREAD

**Issue by niclar** [eclipse-iceoryx/iceoryx#1941]
## a helper functions to get publisher/client/subscriber/server  message mode / QueueFullPolicy or the creation option/parameter

-I would like to be able to fetch the option parameter(s), QueueFullPolicy specifically wrt the subscriber etc. to make hasMissedData validation conditional . -Or are we guaranteed to only test true for  DISCARD_OLDEST_DATA setups ?

e.g
```

   static void HandleSubscriptionDataReceived(iox::popo::UntypedSubscriber* subscriber, MessageCallback* callback)
   {
      if(subscriber->hasMissedData() && 
         subscriber->getQueueFullPolicy() != iox::popo::QueueFullPolicy::DISCARD_OLDEST_DATA)
      {
         std::cerr << "subscriber missing data, exiting..." << std::endl;
         std::exit(EXIT_FAILURE);

```

**Comment by elfenpiff** [comment]
@niclar See the example: https://github.com/eclipse-iceoryx/iceoryx/tree/master/iceoryx_examples/iceoptions

When the `QueueFullPolicy` is set to `BLOCK_PRODUCER` it is guaranteed that data will never be lost. But a connection can only be established when the publisher has the corresponding `ConsumerTooSlowPolicy::WAIT_FOR_CONSUMER`. When this is not the case the subscriber will not receive any data.

**Comment by niclar** [comment]
Ok, I suspected as much. I'll close this ticket and remove the check for this case.

Thanks
