### ISSUE TITLE
Undefined behaviour in `publishCopyOf` and `publishResultOf`

### ISSUE THREAD

**Issue by JakubSosnovec** [eclipse-iceoryx/iceoryx#1963]
## Required information

**Operating system:**
Ubuntu 22

**Compiler version:**
GCC 9.4

**Eclipse iceoryx version:**
Master branch

**Observed result or behaviour:**
There is undefined behaviour in `iox::popo::Publisher::publishCopyOf` and `iox::popo::Publisher::publishResultOf`.

For `publishCopyOf`, copy-assignment operator is used to copy the user-given instance of `T` into the sample memory. However, there might not be any validly constructed instance of `T` in the sample memory before this copy-assignment! So, for example if the copy-assignment operator is implemented with some non-trivial destruction of existing data (before the assignment part), things can easily go wrong (because there might be some left-over random data from previous usages of this chunk). In general, I believe it is UB to do this. See here: https://github.com/eclipse-iceoryx/iceoryx/blob/master/iceoryx_posh/include/iceoryx_posh/internal/popo/publisher_impl.inl#L64

For `publishResultOf`, it is similar. The user-given callable must have the first argument `T*`. And again, there might not be any validly constructed instance of `T` when it is passed to the callable. So, if the user callable is using copy-assignment operator to assign to the sample memory, this will be UB again. See here: https://github.com/eclipse-iceoryx/iceoryx/blob/master/iceoryx_posh/include/iceoryx_posh/internal/popo/publisher_impl.inl#L55

Note that this is in contrast to the usual `loan()` method, where there is placement new operator called, which ensures that a valid instance is constructed in the memory: https://github.com/eclipse-iceoryx/iceoryx/blob/master/iceoryx_posh/include/iceoryx_posh/internal/popo/publisher_impl.inl#L40

**Expected result or behaviour:**
No UB.

**Conditions where it occurred / Performed steps:**
I met this when using a `iox::vector` as `T`, and the copy assignment operator got stuck trying to destroy existing samples, because it believed that its size was huge.

**Comment by elfenpiff** [comment]
@JakubSosnovec you are completely right in this case. A bug fix would be to perform a placement new using the copy constructor and we should have defined behavior again. So changing this bugged code:
```cxx
return loanSample().and_then([&](auto& sample) {
        *sample.get() = val; // Copy assignment of value into sample's memory allocation.
        sample.publish();
    });
```

Into
```cxx
return loanSample().and_then([&](auto& sample) {
        new (sample.get()) T(val); // Copy constructor of value into sample's memory allocation.
        sample.publish();
    });
```

**Comment by elfenpiff** [comment]
@JakubSosnovec aah I saw now that you have solved it exactly like this ... forget my jibber jabber from above ;)
