### ISSUE TITLE
iceoryx build error after sucessfull cmake config

### ISSUE THREAD

**Issue by shantanubanerjee** [eclipse-iceoryx/iceoryx#1975]
Hi,
I am using gcc 4.8.1 and try to cross compile iceoryx.

command : 
cmake -Bbuild -Hiceoryx_meta -DCMAKE_TOOLCHAIN_FILE=/home/shantanu/LGE/EXP/ICEROXY/telechips_toolchain.cmake

configuration sucessfull
![image](https://user-images.githubusercontent.com/2724551/231949411-fdd0ac1a-f71a-4e7e-8c37-129f765aa556.png)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/shantanu/LGE/EXP/ICEROXY/iceoryx-master/build

But I am getting error during build

`cmake --build build
[  4%] Built target iceoryx_platform
[  5%] Building CXX object hoofs/CMakeFiles/iceoryx_hoofs.dir/design/source/functional_interface.cpp.o
In file included from /home/shantanu/LGE/EXP/ICEROXY/iceoryx-master/iceoryx_hoofs/functional/include/iox/function_ref.hpp:25:0,
                 from /home/shantanu/LGE/EXP/ICEROXY/iceoryx-master/iceoryx_hoofs/design/include/iox/functional_interface.hpp:20,
                 from /home/shantanu/LGE/EXP/ICEROXY/iceoryx-master/iceoryx_hoofs/design/source/functional_interface.cpp:17:
/home/shantanu/LGE/EXP/ICEROXY/iceoryx-master/iceoryx_hoofs/primitives/include/iox/type_traits.hpp:59:16: error: template declaration of 'constexpr const bool iox::always_false_v'
 constexpr bool always_false_v{false};
                ^
/home/shantanu/LGE/EXP/ICEROXY/iceoryx-master/iceoryx_hoofs/primitives/include/iox/type_traits.hpp:100:15: error: 'std::enable_if_t' has not been declared
     test(std::enable_if_t<
               ^
/home/shantanu/LGE/EXP/ICEROXY/iceoryx-master/iceoryx_hoofs/primitives/include/iox/type_traits.hpp:100:26: error: expected ',' or '...' before '<' token
     test(std::enable_if_t<
                          ^
/home/shantanu/LGE/EXP/ICEROXY/iceoryx-master/iceoryx_hoofs/primitives/include/iox/type_traits.hpp:163:19: error: 'always_false_v' was not declared in this scope
     static_assert(always_false_v<T>, "unknown type");
                   ^
/home/shantanu/LGE/EXP/ICEROXY/iceoryx-master/iceoryx_hoofs/primitives/include/iox/type_traits.hpp:163:35: error: expected primary-expression before '>' token
     static_assert(always_false_v<T>, "unknown type");
                                   ^
/home/shantanu/LGE/EXP/ICEROXY/iceoryx-master/iceoryx_hoofs/primitives/include/iox/type_traits.hpp:163:36: error: expected primary-expression before ',' token
     static_assert(always_false_v<T>, "unknown type");
                                    ^
In file included from /home/shantanu/LGE/EXP/ICEROXY/iceoryx-master/iceoryx_hoofs/design/include/iox/functional_interface.hpp:20:0,
                 from /home/shantanu/LGE/EXP/ICEROXY/iceoryx-master/iceoryx_hoofs/design/source/functional_interface.cpp:17:
/home/shantanu/LGE/EXP/ICEROXY/iceoryx-master/iceoryx_hoofs/functional/include/iox/function_ref.hpp:78:26: error: expected type-specifier
`

**Comment by elfenpiff** [comment]
@shantanubanerjee We do not support any compiler which does not support at least C++14. As you can see here: [ojects/cxx-status.html](https://gcc.gnu.org/projects/cxx-status.html) gcc-4.* is not one of them.

The bare minimum which we test is gcc-5.4.

I think it is also not feasible to port iceoryx back to such an old compiler. So if it is possible for you I recommend to switch to a newer gcc version which is at least 5.4. But to be able to use also upcoming iceoryx version it is maybe wise to upgrade it to an even newer version like gcc-7.

**Comment by elBoberido** [comment]
@shantanubanerjee if possible please switch to a compiler already supporting C++17 since we will switch to that language specification at some point, maybe sooner rather than later. I think when we do this move, gcc-8.3 would become the minimal supported compiler.
