### ISSUE TITLE
`expected<void, Error>` is unusable due to `final`

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1976]
## Required information

Since the `final` keyword was added to all `expected` classes the specialization `expected<void, Error>` is unusable since it inherit from them.
No one has noticed this until now so we have 2 solutions.
1. Remove `expected<void, Error>` specialization
2. Remove the `final` keyword.

**Comment by elBoberido** [comment]
@elfenpiff I noticed it end of last week. There is a third option, having an `detail::expected_impl<E>` and let `expected<E>` and `expected<void, E>` derive from it
