### ISSUE TITLE
ServiceDescription interface and INTERFACE_NAMES not match

### ISSUE THREAD

**Issue by wjswjq** [eclipse-iceoryx/iceoryx#1977]
In service_description.hpp
`
constexpr const char* INTERFACE_NAMES[] = {"INTERNAL", "ESOC", "SOMEIP", "AMQP", "DDS", "SIGNAL", "MTA", "ROS1", "END"};
`
"MQTT" is lost in INTERFACE_NAMES.

**Comment by elfenpiff** [comment]
@wjswjq Thanks for the bug report! Since you discovered the bug would you like to have the opportunity to fix it and create a PR to receive the appreciation for it?
