### ISSUE TITLE
make runtime::PROCESS_WAITING_FOR_ROUDI_TIMEOUT runtime configurable

### ISSUE THREAD

**Issue by niclar** [eclipse-iceoryx/iceoryx#1989]
To aid debugging it would be nice if one could supply a (custom) runtime::PROCESS_WAITING_FOR_ROUDI_TIMEOUT  when instantiating the posh runtime.

**Comment by elBoberido** [comment]
@niclar that would be one option. Ideally it would be nice to make the runtime respect `Ctrl+C` when the app is waiting. Or is your intention more related to increasing the timeout.

**Comment by elBoberido** [comment]
@niclar there is now an experimental API which can be used to control the wait timeout and `Ctrl+C` now also works on the current API. I would close this issue if that's what you meant when opening it.
