### ISSUE TITLE
N publisher and M subscriber model where each message is received by only one subscriber

### ISSUE THREAD

**Issue by musamaanjum** [eclipse-iceoryx/iceoryx#1992]
I'm trying to make N publisher and M subscriber model where the message from the publisher is only received by one of the subscribers. For example, N publishers will keep on sending messages. Each subscriber must receive a different message to do processing in parallel. All subscribers shouldn't receive the same message. It matches more of a queue where multiple processes are putting data on a queue and multiple consumers want to get one message each.

I'm looking at the PublisherOptions and Subscriber for this configuration that one message is only delivered to one subscriber (not all of them). But I've not found any configuration. Is this kind of support present in Iceoryx?

**Comment by mossmaurice** [comment]
Closing this issue. Feel free to reopen if there are more questions.
