### ISSUE TITLE
qnx710 uds Permission denied

### ISSUE THREAD

**Issue by lujuntuan** [eclipse-iceoryx/iceoryx#1996]
Execute iox-roudi, "Permission denied" errors occur.

I try to change IOX_UDS_SOCKET_PATH_PREFIX to /data, but still have the problem

**Comment by elBoberido** [comment]
@lujuntuan you need write access to ``/tmp/ or start `RouDi` and the applications with a user which has write access

**Comment by lujuntuan** [comment]
`
...
expected<void, IpcChannelError> UnixDomainSocket::initalizeSocket() noexcept
{
    // initialize the sockAddr data structure with the provided name
    memset(&m_sockAddr, 0, sizeof(m_sockAddr));
    m_sockAddr.sun_family = AF_LOCAL;
    if (m_name.size() > LONGEST_VALID_NAME)
    {
        return err(IpcChannelError::INVALID_CHANNEL_NAME);
    }
    strncpy(&(m_sockAddr.sun_path[0]), m_name.c_str(), m_name.size());
    
#ifdef __QNX__
    m_sockAddr.sun_path[0] = '\0'; //Use abstract namespace socket.
#endif
...
`

Adding this code  works fine.
`m_sockAddr.sun_path[0] = '\0';`

**Comment by elBoberido** [comment]
@lujuntuan I'm not a QNX expert but I would be surprised if your proposal would work. It might result in being able to start RouDi but did you try to run applications, e.g. one of the examples?

**Comment by mossmaurice** [comment]
@lujuntuan Closing this issue, feel free to re-open if the issue persits.
