### ISSUE TITLE
Enable Bazel build with clang

### ISSUE THREAD

**Issue by phongt** [eclipse-iceoryx/iceoryx#1998]
## Brief feature description

Enable using clang building for bazel. This is nice to have.

## Detailed information

The commits in this branch: https://github.com/phongt/iceoryx/tree/bazel-build-clang-rules. Should I raise a PR for reviewing?

**Comment by elfenpiff** [comment]
@phongt Yes please, this is great!

**Comment by phongt** [comment]
@elfenpiff  Raised PR https://github.com/eclipse-iceoryx/iceoryx/pull/1999
