### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by neil1899** [eclipse-iceoryx/iceoryx#2033]
## Required information

**Operating system:**
E.g. Ubuntu 20.04 LTS

**Compiler version:**
E.g. GCC 9.4.0

**Eclipse iceoryx version:**
E.g. `v2.0.3` branch

**Observed result or behaviour:**

libiceoryx_posh.a(ipc_interface_creator.cpp.o):ipc_interface_creator.cpp:function iox::runtime::IpcInterfaceCreator::cleanupResource(): error: undefined reference to 'iox::posix::UnixDomainSocket::destroy()'

**Expected result or behaviour:**
linker success

**Conditions where it occurred / Performed steps:**
one:i run cmake build 2.0.3 release code.
two:use bazel build he example ioxhello
bazel-bin         bazel-out                   bazel-testlogs  WORKSPACE
bazel_build_base  bazel-single-iceoryx-cmake  hello

nvidia@ubuntu:~/workspace/dfx_rmw/single-iceoryx-cmake/bazel_build_base/prebuild/dfx_libs$ tree -L 2
.
├── BUILD
├── include
│   └── iceoryx
└── lib
    └── iceoryx

4 directories, 1 file
prebuild BUILD below:
-----
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "iceoryx-lib",
    srcs = glob([
        "lib/iceoryx/*.a",
        "**/*.inl",
    ]),
    hdrs = glob([
        "**/*.hpp",
        "**/*.h",
    ]),
    includes = [
        "include/iceoryx/v/",
    ],

    visibility = ["//visibility:public"],
)
-----

code is the same as the v2.0.3 version

the BUILD.bazel below:
-----
cc_library(
    name = "topic_data",
    hdrs = glob(["*.h"]),
)

cc_binary(
    name = "iox-cpp-publisher-helloworld",
    srcs = [
        "iox_publisher_helloworld.cpp",
    ],
    deps = [
        ":topic_data",
        "//bazel_build_base/prebuild/dfx_libs:iceoryx-lib",
    ],
    copts = ["-O0", "-std=c++14"],

)
-----

If I use shared library is ok now.

**Comment by elBoberido** [comment]
@neil1899 disclaimer, I barely know Bazel. Saying that, since iceoryx master can be build with Bazel could you try if that works for you? If yes, it might be a starting point for further investigation.

**Comment by neil1899** [comment]
have fix

**Comment by elBoberido** [comment]
@neil1899 would be great if you could share the solution in case someone else has the same problem :)

**Comment by neil1899** [comment]
no problem，if we build static library


package(default_visibility = ["//visibility:public"])

cc_library(
    name = "iceoryx-libs-platform",
    srcs = [
        "lib/iceoryx/libiceoryx_platform.a",
        "lib/iceoryx/libiceoryx_binding_c.a",
        "lib/iceoryx/libiceoryx_dds.a",
    ]
)
cc_library(
    name = "iceoryx-libs",
    srcs = [
        "lib/iceoryx/libiceoryx_hoofs.a",
    ],
    deps = [":iceoryx-libs-platform"],
)

cc_library(
    name = "iceoryx-lib",
    srcs = ["lib/iceoryx/libiceoryx_posh.a",
        "lib/iceoryx/libiceoryx_posh_config.a",
    ] + glob([
        "**/*.inl",
    ]),
    hdrs = glob([
        "**/*.hpp",
        "**/*.h",
    ]),
    includes = [
        "include/iceoryx/v2.0.3/",
    ],
    deps = [":iceoryx-libs"],

    visibility = ["//visibility:public"],
)

we need write the dep of echo static library

**Comment by neil1899** [comment]
@elBoberido the answer is ok?

**Comment by elBoberido** [comment]
@neil1899 thanks a lot. Like I said I'm not a bazel expert but if it works for you it might also work for others.

Just a small remark. Would you please edit your answer and wrap the bazel config in back-ticks, e.g.
````bazel
```bazel
package(default_visibility = ["//visibility:public"])

```
````

This makes it much easier to read the config.
