### ISSUE TITLE
topic_data of complexdata

### ISSUE THREAD

**Issue by neil1899** [eclipse-iceoryx/iceoryx#2034]
## Required information

**Operating system:**
E.g. Ubuntu 20.04 LTS

**Compiler version:**
E.g. GCC 9.4.0

**Eclipse iceoryx version:**
E.g. `v2.0.3`

from iceoryx_examples:/complexdata
struct ComplexDataType
{
    forward_list<string<10>, 5> stringForwardList;
    list<uint64_t, 10> integerList;
    list<optional<int32_t>, 15> optionalList;
    stack<float, 5> floatStack;
    string<20> someString;
    vector<double, 5> doubleVector;
    vector<variant<string<10>, double>, 10> variantVector;
};
i found ComplexDataType only define "fixed length" of data type(such as string and so on)
iceoryx support dynamic len of data type? how do it

thanks in advance!

**Comment by elBoberido** [comment]
@neil1899 closing the issue. If your question is not answered feel free to re-open
