### ISSUE TITLE
Support gcc 13.2?

### ISSUE THREAD

**Issue by sukeyisme** [eclipse-iceoryx/iceoryx#2047]
## Brief feature description

Please describe in a few sentences what should be implemented

## Detailed information

E.g. a list of pros and cons of different considerations and how iceoryx and its user could benefit from it

**Comment by elBoberido** [comment]
@sukeyisme our CI runs the latest GCC 14. What does not work with GCC 13.2?

**Comment by sukeyisme** [comment]
some test can not build success, then i disable test build.so can close this.

**Comment by elBoberido** [comment]
Do you have more info, like the error message of the compiler?

**Comment by elBoberido** [comment]
Re-open the issue. GCC 13 creates quite a lot of string overflow warnings. They are false positives but maybe we can easily suppress them. GCC13 is currently the default on Arch Linux.
