### ISSUE TITLE
Chunk fails to be released when more the GiB of chunks have been allocated

### ISSUE THREAD

**Issue by gpalmer-latai** [eclipse-iceoryx/iceoryx#2087]
## Required information

A full working example with readme exists [here](https://github.com/eclipse-iceoryx/iceoryx/compare/master...gpalmer-latai:iceoryx:4GiB_chunk_release_bug#diff-c666679baaaef746ba73d23c0b9653ead714aa2666705da9199c0989fa525221).

To summarize though, if Roudi is configured to allow a memory pool with more than 4GiB worth of chunks, and to allow subscribers to reserve enough chunks at one time to have more than 4GiB accounted for, then any chunk that is attempted to be released thereafter will fail. 

**Operating system:**
Ubuntu 20.04 LTS

**Compiler version:**
GCC 9.4.0

**Eclipse iceoryx version:**
`master`

**Observed result or behaviour:**
On the subscriber end, this error message occurs, followed by program termination:
```
2023-11-10 18:22:05.649 [Warn ]: ICEORYX error! POPO__CHUNK_RECEIVER_INVALID_CHUNK_TO_RELEASE_FROM_USER
subscriber: iceoryx_hoofs/source/error_handling/error_handler.cpp:45: static void iox::ErrorHandler::reactOnErrorLevel(iox::ErrorLevel, const char*): Assertion `false' failed.
```

On the publisher end, this error message occurs:
```
2023-11-10 18:22:05.900 [Error]: Condition: offset % m_chunkSize == 0 in void iox::mepoo::MemPool::freeChunk(const void*) is violated. (iceoryx_posh/source/mepoo/mem_pool.cpp:109)
2023-11-10 18:22:05.900 [Error]: ICEORYX error! EXPECTS_ENSURES_FAILED
publisher: iceoryx_hoofs/source/error_handling/error_handler.cpp:40: static void iox::ErrorHandler::reactOnErrorLevel(iox::ErrorLevel, const char*): Assertion `false' failed.
```

**Expected result or behaviour:**
Either the 4GiB limit is enforced and roudi presents an informative error on startup stating that the configuration cannot be supported due to memory accounting limits.

Or everything continues to work fine under these conditions.

**Conditions where it occurred / Performed steps:**
Steps are described [here](https://github.com/eclipse-iceoryx/iceoryx/compare/master...gpalmer-latai:iceoryx:4GiB_chunk_release_bug#diff-c666679baaaef746ba73d23c0b9653ead714aa2666705da9199c0989fa525221) but to summarize:

1. Configure Roudi with a memory pool containing chunk size + count greater than 4GiB
2. Continually publish a message that uses that memory pool
3. Have a subscriber take delivered message samples and store them in a datastructure
4. After more than 4GiB of data have been stored in the datastructure, attempt to release a message sample.

**Comment by elBoberido** [comment]
It seems you always find the bugs which are easy to fix. I hope it stays like this.

Your theory was right. The issue seems to be in `MemPool::getChunk` and replacing `return m_rawMemory.get() + l_index * m_chunkSize;` with
`return m_rawMemory.get() + static_cast<uint64_t>(l_index) * m_chunkSize;` fixes the problem.

**Comment by gpalmer-latai** [comment]
> It seems you always find the bugs which are easy to fix. I hope it stays like this.

I'll try harder next time 😉

I was hoping the fix would be a simple static cast. At the time I encountered the bug I wasn't familiar enough with the codebase to know exactly where to look so I'm glad you found it easily :)

**Comment by gpalmer-latai** [comment]
Anyway - I wonder if there are static analysis tools that can help detect errors like this - assigning the result of multiplying two 32bit integers to another 32 bit integer seems easy enough to at least flag. 

And maybe there is a way to ensure that all such arithmetic is validated with a unit test providing edge case values.

**Comment by elBoberido** [comment]
> Anyway - I wonder if there are static analysis tools that can help detect errors like this - assigning the result of multiplying two 32bit integers to another 32 bit integer seems easy enough to at least flag.
> 
> And maybe there is a way to ensure that all such arithmetic is validated with a unit test providing edge case values.

Up until now we used the static analysis tools only for hoofs. We want to use clang-tidy for the whole codebase but that is a big task and will take quite some time. I guess clang-tidy would have found the issue if it would have been activated for that file.

**Comment by gpalmer-latai** [comment]
> I guess clang-tidy would have found the issue if it would have been activated for that file.

A yes, I recall mentioning in the other thread about having suppressed some warnings... This is something I might be interested in looking enabling on our end again at some point.
