### ISSUE TITLE
RouDi crashed, app segment fault at computeRawPtr

### ISSUE THREAD

**Issue by sgf201** [eclipse-iceoryx/iceoryx#2094]
## Required information

E.g. Ubuntu 20.04 LTS

E.g. GCC 9.4.0

**Eclipse iceoryx version:**
RouDi version: 2.0.3
Roudi crashed after segment fault in user app, bt is bellow
[mix_image-6] #6    Object "/opt/nros/lib/librcl.so", at 0xffff8e865ae7, in rcl_return_loaned_message_from_subscription
[mix_image-6] #5    Object "/opt/nros/lib/librmw_cyclonedds_cpp.so", at 0xffff8e49ff4b, in rmw_return_loaned_message_from_subscription
[mix_image-6] #4    Object "/opt/nros/lib/libddsc.so.0", at 0xffff8e4198ef, in dds_data_allocator_free
[mix_image-6] #3    Object "/opt/nros/lib/libiceoryx_binding_c.so", at 0xffff8e2372cf, in iox_sub_release_chunk
[mix_image-6] #2    Object "/opt/nros/lib/libiceoryx_posh.so", at 0xffff8dec51a7, in iox::popo::SubscriberPortUser::releaseChunk(iox::mepoo::ChunkHeader const*)
[mix_image-6] #1    Object "/opt/nros/lib/libiceoryx_posh.so", at 0xffff8debcc3f, in iox::mepoo::ShmSafeUnmanagedChunk::getChunkHeader()
[mix_image-6] #0    Object "/opt/nros/lib/libiceoryx_hoofs.so", at 0xffff8de45638, in iox::rp::BaseRelativePointer::computeRawPtr() const

**Comment by elBoberido** [comment]
@sgf201 is this a crash in iceoryx or in the application. From be backtrace it also looks like you are using Cyclone DDS. I know of an old bug where a double free could happen which might result in such an error.

**Comment by sgf201** [comment]
thanks a lot
