### ISSUE TITLE
Add introspection to ROS iceoryx release

### ISSUE THREAD

**Issue by mossmaurice** [eclipse-iceoryx/iceoryx#2099]
## Brief feature description

See https://github.com/ros2/rmw_cyclonedds/issues/470

## Detailed information

* [x] Changes for `master` branch (release as part of `v3.0`
* [x] Backport to release `v2.x`
   * [x] Fix [RHEL issue](https://ci.ros2.org/view/nightly/job/nightly_linux-rhel_debug/1732/console#console-section-1)

**Comment by mossmaurice** [comment]
@clalancette Do you have a hint on how to install [ncurses](https://en.wikipedia.org/wiki/Ncurses) on RHEL? I have added the dependency in the [`package.xml`](https://github.com/eclipse-iceoryx/iceoryx/blob/release_2.0/tools/introspection/package.xml#L17).

cc @dkroenke @elBoberido @budrus

**Comment by elBoberido** [comment]
@mossmaurice I think we need to follow @clalancette suggestion and skip building the introspection client when ncurses is not available. If you are currently busy, we could revert the merge to take out the pressure.

**Comment by mossmaurice** [comment]
@elBoberido 

>  I think we need to follow @clalancette suggestion and skip building the introspection client when ncurses is not available. If you are currently busy, we could revert the merge to take out the pressure.

I'll prepare the PRs as suggested by @clalancette

**Comment by mossmaurice** [comment]
Created the following releases for ROS 2 `humble`, `iron`, `rolling` and for iceoryx itself:

- https://github.com/ros/rosdistro/pull/39143
- https://github.com/ros/rosdistro/pull/39151
- https://github.com/ros/rosdistro/pull/39154
- https://github.com/eclipse-iceoryx/iceoryx/releases/tag/v2.0.5
