### ISSUE TITLE
Move `MoveAndCopyHelper` to `iceoryx_hoofs/design`

### ISSUE THREAD

**Issue by Dennis40816** [eclipse-iceoryx/iceoryx#2113]
## Brief feature description

Currently, some classes in our codebase use assignment in the constructor (ctor) to avoid code duplication, as seen in issue #1517 . However, it's noted in issue #1686  that self-assignment cannot happen in the ctor. Therefore, an alternative approach should be adopted to replace the current implementation.

One method involves placing the shared logical code within a separate function, hereafter referred to as `copy_and_move_impl`. This function is then called within the ctor and assignment operations, using template parameters to specify the method of member initialization.

`MoveAndCopyHelper` has been implemented in PR #2105 and applied to `FixedPositionContainer`. This helper controls through template parameter types, specifically an enum class `MoveAndCopyOperations`.

### Example usage

When the helper is invoked with the template (referred to as `Opt`) set to `MoveAndCopyOperations::CopyConstructor`, it would look something like:

```c
#include "iox/detail/fixed_position_container_helper.hpp"

// for class A ...

inline A::A(const A& rhs) noexcept
{
    copy_and_move_impl<detail::MoveAndCopyOperations::CopyConstructor>(rhs);
}

inline A::A(A&& rhs) noexcept
{
    copy_and_move_impl<detail::MoveAndCopyOperations::MoveConstructor>(std::forward<A>(rhs));
}

... 

template <detail::MoveAndCopyOperations Opt, typename RhsType, /* other template */>
inline void A::copy_and_move_impl(RhsType&& rhs) noexcept
{
    // alias helper struct
    using Helper = detail::MoveAndCopyHelper<Opt>;
    
    // determine by `Opt`
    constexpr bool_is_ctor = Helper::is_ctor();
    constexpr bool is_move = Helper::is_move(); 
    
    // if you want to transfer rhs.m_data array to this.m_data
    for (uint64_t i = 0; i < rhs.size(); ++i)
    {
	 if constexpr (is_move)
        {
            Helper::transfer(m_data[i], std::move(rhs.m_data[i]));
        }
        else
        {
            Helper::transfer(m_data[i], rhs.m_data[i]);
        }
    }
    
    // if you want to initialize a status array in ctor operation
    if constexpr (is_ctor)
    {
        initialize_status();
    }
}
```

### Cons
Integrating this helper into the `design` can be beneficial when the differences between the constructor and assignment are minimal. It allows for the creation of a unified template function within the class to manage these operations, with the behavior inside controlled by the `Opt` parameter. Simultaneously, it helps to avoid situations where the ctor invokes assignment, especially in cases where the assignment is deleted.

## Evaluate `copy_or_move`

If `move_or_copy` can be implemented correctly, the code mentioned above can be simplified as

```c
...
// if you want to transfer rhs.m_data array to this.m_data
    for (uint64_t i = 0; i < rhs.size(); ++i)
    {
            Helper::transfer(m_data[i], Helper::move_or_copy(rhs.m_data[i]));
    }
...
```
 
However, the following `move_or_copy` will call move ctor at return syntax.  
```c
template <typename T>
 static inline constexpr auto move_or_copy(T&& value) noexcept
 {
     if constexpr (is_move())
     {
         return std::move(std::forward<T>(value));
     }
     else
     {
         return std::cref(std::forward<T>(value));
     }
}
```
You can see the details at [here](https://godbolt.org/z/heTcqoeo7).

Short summary:
- So far, I have no idea how to implement it correctly.

**Comment by gpalmer-latai** [comment]
Can you update the examples in the summary to all use `std::forward` instead of `std::move`?
