### ISSUE TITLE
Option to disable service discovery in DDS Gateways.

### ISSUE THREAD

**Issue by ithier** [eclipse-iceoryx/iceoryx#212]
## Brief feature description
A configuration option to disable dynamic discovery in the dds gateways.

## Detailed information

There are use-cases where one might want the dds gateway to only forward data for specific topics rather than every topic that appears in the system.
This can be achieved by specifying the topics to forward (i.e. by the existing config file feature) and disabling service discovery in the gateway (missing).

**Comment by mossmaurice** [comment]
Moved to https://github.com/eclipse-iceoryx/iceoryx-gateway-dds/issues/4
