### ISSUE TITLE
historyRequest may larger than queueCapacity during creating Subscribers in PoshRuntimeImpl.

### ISSUE THREAD

**Issue by waliceSnow** [eclipse-iceoryx/iceoryx#2121]
https://github.com/eclipse-iceoryx/iceoryx/blame/f0622f1f21c740a8e4510bd6d682db04cba566e7/iceoryx_posh/source/runtime/posh_runtime_impl.cpp#L237

At `if (subscriberOptions.historyRequest > subscriberOptions.queueCapacity)`, since `queueCapacity` may exceed the `MAX_QUEUE_CAPACITY`, `subscriberOptions.historyRequest` may need to compare with `options.queueCapacity`.

**Comment by elBoberido** [comment]
Good catch. Do you want to create a PR?

**Comment by waliceSnow** [comment]
Sure.

**Comment by elBoberido** [comment]
Here you can find the important stuff
https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md

The initial PR might be a bit cumbersome due to the one time tasks required to be able to contribute to an Eclipse project and our workflow. We will guide you though :)

**Comment by waliceSnow** [comment]
Thank you for the support. I created a PR. Please help to check if it helps.
