### ISSUE TITLE
Versions 2.0.4 and 2.0.5 not availble in docs (pages)

### ISSUE THREAD

**Issue by michael-sbarra-apexai** [eclipse-iceoryx/iceoryx#2134]
## Required information
https://iceoryx.io/latest points to https://iceoryx.io/v2.0.3, even though both 2.0.4 (tag) and 2.0.5 (release) have been made,
and their CI pipeline job for the docs succeeded. These versions are not in the version picker dropdown. https://iceoryx.io/v2.0.4 and https://iceoryx.io/v2.0.5 are error pages.

**Operating system:**
NA

**Compiler version:**
NA

**Eclipse iceoryx version:**
NA

**Observed result or behaviour:**
https://iceoryx.io/latest points to https://iceoryx.io/v2.0.3

**Expected result or behaviour:**
https://iceoryx.io/latest points to https://iceoryx.io/v2.0.5/, 2.0.4 and 2.0.5 are in the version picker dropdown and their docs are available and not an error page.

**Conditions where it occurred / Performed steps:**

**Comment by elBoberido** [comment]
@michael-sbarra-apexai thanks for pointing this out. Usually @mossmaurice takes care of updating the website.

**Comment by mossmaurice** [comment]
@michael-sbarra-apexai Thanks for creating the issue! I'll publish the docs in the next few days.
