### ISSUE TITLE
subscriber crashed when deserialize msg which is send by foxglove_bridge through loaned api

### ISSUE THREAD

**Issue by sgf201** [eclipse-iceoryx/iceoryx#2136]
## Required information

**Operating system:**
Ubuntu 20.04 LTS

**Compiler version:**
E.g. GCC 9.4.0

**Eclipse iceoryx version:**
2.0.3

**Observed result or behaviour:**
loaned api deserialize crash
turn off loaned api it worked
[decodec-1] #12   Object "/home/admin/5v5r/fsinstall/nov_codec/lib/nov_codec/decodec", at 0xaaaae95184e3, in                                                                                               
[decodec-1] #11   Object "/lib/aarch64-linux-gnu/libc.so.6", at 0xffff823bfe0f, in __libc_start_main                                                                                                       
[decodec-1] #10   Object "/home/admin/5v5r/fsinstall/nov_codec/lib/nov_codec/decodec", at 0xaaaae9518b57, in main                                                                                          
[decodec-1] #9    Object "/opt/nros/lib/librclcpp.so", at 0xffff828fad83, in rclcpp::executors::SingleThreadedExecutor::spin()                                                                             
[decodec-1] #8    Object "/opt/nros/lib/librclcpp.so", at 0xffff828f42fb, in rclcpp::Executor::execute_any_executable(rclcpp::AnyExecutable&)                                                              
[decodec-1] #7    Object "/opt/nros/lib/librclcpp.so", at 0xffff828f2fcb, in rclcpp::Executor::execute_subscription(std::shared_ptr<rclcpp::SubscriptionBase>)                                             
[decodec-1] #6    Object "/opt/nros/lib/librclcpp.so", at 0xffff828f208b, in                                                                                                                               
[decodec-1] #5    Object "/opt/nros/lib/librclcpp.so", at 0xffff828f1ee3, in                                                                                                                               
[decodec-1] #4    Object "/opt/nros/lib/librcl.so", at 0xffff8233183b, in rcl_take_loaned_message                                                                                                          
[decodec-1] #3    Object "/opt/nros/lib/librmw_cyclonedds_cpp.so", at 0xffff81f7bcd3, in                                                                                                                   
[decodec-1] #2    Object "/opt/nros/lib/librmw_cyclonedds_cpp.so", at 0xffff81f7b5a7, in rmw_deserialize
[decodec-1] #1    Object "/opt/nros/lib/librmw_cyclonedds_cpp.so", at 0xffff81f88b07, in 
[decodec-1] #0    Object "/opt/nros/lib/librmw_cyclonedds_cpp.so", at 0xffff81f88a84, in 
[decodec-1] Segmentation fault (Address not mapped to object [(nil)])

**Expected result or behaviour:**
What do you expect to happen?
worked
**Conditions where it occurred / Performed steps:**
Describe how one can reproduce the bug.
code in foxglove_bridge
// Copy the message payload into a SerializedMessage object
  rclcpp::SerializedMessage serializedMessage{message.getLength()};
  auto& rclSerializedMsg = serializedMessage.get_rcl_serialized_message();
  std::memcpy(rclSerializedMsg.buffer, message.getData(), message.getLength());
  rclSerializedMsg.buffer_length = message.getLength();

  // Publish the message
  publisher->publish(serializedMessage);

reported  to foxglove-bridge
https://github.com/foxglove/ros-foxglove-bridge/issues/280

**Comment by elBoberido** [comment]
@sgf201 the backtrace looks weird. I'm not sure if this is related to iceoryx itself or to the integration in CycloneDDS or something on the user side.

One scenario for an segmentation fault is when the shared memory segment for the publisher is not mapped into the application. But my memory can also deceive me and we might have a check for that.

Can you check if the application runs under the same POSIX user as RouDi or if not if there is a shared memory segment with the POSIX user of the application configured in the `roudi_config.toml`?

**Comment by sgf201** [comment]
> @sgf201 the backtrace looks weird. I'm not sure if this is related to iceoryx itself or to the integration in CycloneDDS or something on the user side.回溯看起来很奇怪。我不确定这是否与iceoryx本身有关，还是与CycloneDDS中的集成有关，或者与用户端的其他内容有关。
> 
> One scenario for an segmentation fault is when the shared memory segment for the publisher is not mapped into the application. But my memory can also deceive me and we might have a check for that.分段故障的一种情况是发布者的共享内存段未映射到应用程序中。但我的记忆也会欺骗我，我们可能会对此进行检查。
> 
> Can you check if the application runs under the same POSIX user as RouDi or if not if there is a shared memory segment with the POSIX user of the application configured in the `roudi_config.toml`?您能否检查应用程序是否在与 RouDi 相同的 POSIX 用户下运行，或者如果不是，是否与 中配置的应用程序的 POSIX 用户共享内存段 `roudi_config.toml` ？

all apps runs under the same POSIX user, and I have checked the roudi log, there is no warning or error info.anther info is the "ros2 topic echo msg" works well. the content shows out.

**Comment by elBoberido** [comment]
@sgf201 in this case it might be an issue in the RMW implementation. I know that zero copy is restricted to some use cases. Maybe your use case is also a restricted one. I think the Cyclone DDS developer can tell you more about it.

**Comment by elBoberido** [comment]
Closing this since it looks like an issue in a layer above iceoryx

**Comment by sgf201** [comment]
The root cause has been identified. When the bridge is using the generic publisher to forward messages, it does not use the publish_as_loaned interface for the original loan-based messages.
