### ISSUE TITLE
bazel support release

### ISSUE THREAD

**Issue by wep21** [eclipse-iceoryx/iceoryx#2154]
## Brief feature description

Will a new release including bazel support be created?

**Comment by elBoberido** [comment]
The current master branch supports bazel which means it will also be in the next release.

It is not on the same level like cmake, e.g. some compile time configuration cannot be set with bazel yet. If you have experience with bazel and want to add this configuration options we would appreciate a patch.

**Comment by elBoberido** [comment]
Closing this issue. The next release will have bazel support
