### ISSUE TITLE
Allow For memory chunks bigger than 4GB

### ISSUE THREAD

**Issue by kozakusek** [eclipse-iceoryx/iceoryx#2157]
As discussed this seems to be a "technical unnecessary restriction."
From my experiments it seems possible to fix it by tweaking some of the types 

### Discussed in https://github.com/eclipse-iceoryx/iceoryx/discussions/2149

<div type='discussions-op-text'>

<sup>Originally posted by **kozakusek** January  3, 2024</sup>
When trying to start RouDi with a 4GB segment.mempool I encountered an unpleasant error:

```
 Condition: (t >= Minimum) && (t <= Maximum) in iox::range<T, Minimum, Maximum>::range(T) [with T = unsigned int; T Minimum = 1; T Maximum = 4294967255] is violated. (/workdir/iceoryx/iceoryx_hoofs/primitives/include/iox/algorithm.hpp:208)
```

Then after reading into the source code I noticed that in many cases (e.g. `iox_pub_loan_chunk`) the variable that refers to size is of type `uint32_t`.

Is there a reason for this limitation? Are you planning to add support for bigger memory chunks by adding option to hold size in 64bit integers?

Thanks</div>

**Comment by elBoberido** [comment]
@kozakusek looking forward to your PR :)

**Comment by kozakusek** [comment]
I've created a draft PR https://github.com/eclipse-iceoryx/iceoryx/pull/2158.
I just need to delete the temporary modifications made in iceperf example and I think it will be ready for review.

In the meantime if you have a spare second I would apprieciate if you could check if I didn't messed up anything with the issue/commit/pr format :smiley:
