### ISSUE TITLE
 How to solve the problem that the app is connected before Roudi is terminated, causing the app to fail to access the socket after Roudi is terminated ("Transport endpoint is not connected")

### ISSUE THREAD

**Issue by zhang-ke-liang** [eclipse-iceoryx/iceoryx#2179]
## Required information

**Operating system:**
E.g. Ubuntu 22.04 LTS

**Compiler version:**
E.g. GCC 11.4.0

**Eclipse iceoryx version:**
v2.0.3

**Observed result or behaviour:**

（Multiple programs register apps to connect to Roudi. When a program is terminated, the systemd restarts the service.）

When roudi terminates, since multiple app processes are connected to roudi, after roudi kills the app, the app connects to roudi again, and after connecting, roudi terminates. At this time, the roudi socket file is still in the "/tmp" directory. (Multiple processes of the app are automatically restarted through the system) At this time, the app reports an error (always):

 /tmp/iceoryx-2.0.3/iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp:249 { iox::cxx::expected<iox::posix ::IpcChannelError> iox::posix::UnixDomainSocket::timedSend(const string&, const iox::units::Duration&) const -> iox_sendto } ::: [ 107 ] Transport endpoint is not connected
internal logic error in unix domain socket "/tmp/roudi" occurred
2024-02-04 12:10:13.794 [Warning]: Error in sending keep alive

roudi's logs:
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: Log level set to: [ Debug ]
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: Reserving 66761736 bytes in the shared memory [iceoryx_mgmt]
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: [ Reserving shared memory successful ]
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: 2024-02-04 11:24:55.756 [ Debug ]: Registered memory segment 0x7f566d854000 with size 66761736 to id 1
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: Reserving 149264720 bytes in the shared memory [root]
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: [ Reserving shared memory successful ]
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: 2024-02-04 11:24:55.805 [ Debug ]: Roudi registered payload data segment 0x7f56649fa000 with size 149264720 to id 2
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: RouDi is ready for clients
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: 2024-02-04 11:24:55.943 [ Debug ]: Registered new application WUdOKBTUjfLdAA
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: 2024-02-04 11:24:55.944 [ Debug ]: Created new PublisherPort for application 'WUdOKBTUjfLdAA' with service description 'Service: ***, Instance: ***, Event: ***'
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: 2024-02-04 11:24:55.944 [ Debug ]: Created new SubscriberPort for application 'WUdOKBTUjfLdAA' with service description 'Service: ***, Instance: ***, Event: ***'
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: 2024-02-04 11:24:55.944 [ Debug ]: Created new ConditionVariable for application WUdOKBTUjfLdAA
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: 2024-02-04 11:24:55.966 [ Debug ]: Registered new application lWwTkadkAgVCAA
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: 2024-02-04 11:24:55.967 [ Debug ]: Created new PublisherPort for application 'lWwTkadkAgVCAA' with service description 'Service: ***, Instance: ***, Event: ***'
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: 2024-02-04 11:24:55.967 [ Debug ]: Created new SubscriberPort for application 'lWwTkadkAgVCAA' with service description 'Service: ***, Instance: ***, Event: ***'
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: 2024-02-04 11:24:55.967 [ Debug ]: Created new ConditionVariable for application lWwTkadkAgVCAA
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: 2024-02-04 11:24:55.994 [ Debug ]: Registered new application lFzAeaABrnCCAA
 04 11:24:55 ubuntu22 iox-roudi[350832]: 2024-02-04 11:24:55.995 [ Debug ]: Created new PublisherPort for application 'lFzAeaABrnCCAA' with service description 'Service: ***, Instance: ***, Event: ***'
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: 2024-02-04 11:24:55.995 [ Debug ]: Created new SubscriberPort for application 'lFzAeaABrnCCAA' with service description 'Service: ***, Instance: ***, Event: ***'
2月 04 11:24:55 ubuntu22 iox-roudi[350832]: 2024-02-04 11:24:55.995 [ Debug ]: Created new ConditionVariable for application lFzAeaABrnCCAA
2月 04 11:25:03 ubuntu22 iox-roudi[350832]: 2024-02-04 11:25:03.721 [ Debug ]: Joining 'Mon+Discover' thread...
2月 04 11:25:03 ubuntu22 iox-roudi[350832]: 2024-02-04 11:25:03.814 [ Debug ]: ...'Mon+Discover' thread joined.
2月 04 11:25:03 ubuntu22 iox-roudi[350832]: 2024-02-04 11:25:03.986 [ Debug ]: Registered new application lfDmfeYTSGTaAA
2月 04 11:25:03 ubuntu22 iox-roudi[350832]: 2024-02-04 11:25:03.986 [ Debug ]: Created new PublisherPort for application 'lfDmfeYTSGTaAA' with service description 'Service: ***, Instance: ***, Event: ***'
2月 04 11:25:03 ubuntu22 iox-roudi[350832]: 2024-02-04 11:25:03.986 [ Debug ]: Created new SubscriberPort for application 'lfDmfeYTSGTaAA' with service description 'Service: ***, Instance: ***, Event: ***'
2月 04 11:25:03 ubuntu22 iox-roudi[350832]: 2024-02-04 11:25:03.986 [ Debug ]: Created new ConditionVariable for application lfDmfeYTSGTaAA
2月 04 11:25:04 ubuntu22 iox-roudi[350832]: 2024-02-04 11:25:04.009 [ Debug ]: Registered new application JOggKaNCqILEAA
2月 04 11:25:04 ubuntu22 iox-roudi[350832]: 2024-02-04 11:25:04.010 [ Debug ]: Created new PublisherPort for application 'JOggKaNCqILEAA' with service description 'Service: ***, Instance: ***, Event: ***'
2月 04 11:25:04 ubuntu22 iox-roudi[350832]: 2024-02-04 11:25:04.010 [ Debug ]: Created new SubscriberPort for application 'JOggKaNCqILEAA' with service description 'Service: ***, Instance: ***, Event: ***'
2月 04 11:25:04 ubuntu22 iox-roudi[350832]: 2024-02-04 11:25:04.010 [ Debug ]: Created new ConditionVariable for application JOggKaNCqILEAA

2月 04 11:25:13 ubuntu22 systemd[1]: ***.service: State 'stop-sigterm' timed out. Killing.
2月 04 11:25:13 ubuntu22 systemd[1]: ***.service: Killing process 350832 (iox-roudi) with signal SIGKILL.
2月 04 11:25:13 ubuntu22 systemd[1]: ***.service: Killing process 350835 (MemPoolIntr) with signal SIGKILL.
2月 04 11:25:13 ubuntu22 systemd[1]:***.service: Main process exited, code=killed, status=9/KILL
2月 04 11:25:13 ubuntu22 systemd[1]: ***.service: Failed with result 'timeout'.
2月 04 11:25:13 ubuntu22 systemd[1]: Stopped iceoryx roudi daemon.

**Expected result or behaviour:**
How to prevent the app process from reconnecting during Roudi termination (or how to detect that Roudi is unavailable at this time)?

**Conditions where it occurred / Performed steps:**

**Comment by zhang-ke-liang** [comment]
Before roudi terminates, delete roudi socket file?

**Comment by elBoberido** [comment]
@zhang-ke-liang the socket file is already deleted when RouDi is terminated gracefully, e.g. sending `SIGTERM`. A `SIGKILL` will terminate the process without giving it a chance to clean up its resources. Please ensure that RouDi is terminated gracefully and the socket will be removed.

You still might have the problem that applications open the socket and try to register while RouDi is shutting down but they will eventually run into a timeout. Unfortunately, there is nothing we can do about this.

**Comment by ceccocats** [comment]
Hi, its possible to detect error like this in my application?
```
/tmp/iceoryx-2.0.3/iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp:249 { iox::cxx::expected<iox::posix ::IpcChannelError> iox::posix::UnixDomainSocket::timedSend(const string&, const iox::units::Duration&) const -> iox_sendto } ::: [ 107 ] Transport endpoint is not connected
```
i assume something is failing where I can check if this is happening?

**Comment by elBoberido** [comment]
@ceccocats that depends where it occurs. If you use the socket directly then the return value of the socket call will inform you. If it is deep inside iceoryx we either propagate the error up in the stack or handle it locally but the message is printed nevertheless.

In case this happens during the startup of the application, there is a work in progress experimental API where you could catch this during startup and handle it yourself. Currently only the publisher, subscriber and waitset are available with the experimental API.

**Comment by lix19937** [comment]
I also come across this problem.  
```
/tmp/binarydeb/ros-galactic-iceoryx-utils-1.0.0/source/posix_wrapper/unix_domain_socket.cpp:245 { iox::cxx::expected<iox::posix::IpcChannelError> iox::posix::UnixDomainSocket::timedSend(const string&, const iox::units::Duration&) const }  :::  [ 107 ]  Transport endpoint is not connected
/tmp/binarydeb/ros-galactic-iceoryx-utils-1.0.0/source/posix_wrapper/unix_domain_socket.cpp:245 { iox::cxx::expected<iox::posix::IpcChannelError> iox::posix::UnixDomainSocket::timedSend(const string&, const iox::units::Duration&) const }  :::  [ 107 ]  Transport endpoint is not connected
internal logic error in unix domain socket "/tmp/roudi" occurred
2024-07-24 02:07:03.524 [Warning]: Error in sending keep alive
/tmp/binarydeb/ros-galactic-iceoryx-utils-1.0.0/source/posix_wrapper/unix_domain_socket.cpp:245 { iox::cxx::expected<iox::posix::IpcChannelError> iox::posix::UnixDomainSocket::timedSend(const string&, const iox::units::Duration&) const }  :::  [ 107 ]  Transport endpoint is not connected
/tmp/binarydeb/ros-galactic-iceoryx-utils-1.0.0/source/posix_wrapper/unix_domain_socket.cpp:245 { iox::cxx::expected<iox::posix::IpcChannelError> iox::posix::UnixDomainSocket::timedSend(const string&, const iox::units::Duration&) const }  :::  [ 107 ]  Transport endpoint is not connected
internal logic error in unix domain socket "/tmp/roudi" occurred

```

**Comment by lix19937** [comment]
The experimental API is released ?  @elBoberido

**Comment by lix19937** [comment]
The experimental API is released ?  @elBoberido

**Comment by elBoberido** [comment]
@lix19937 the experimental API is not released but in the `main` branch and hidden behind a cmake flag

**Comment by lix19937** [comment]
@elBoberido  thanks.
