### ISSUE TITLE
ThreadSafePolicy:lock fail

### ISSUE THREAD

**Issue by fengtuo58** [eclipse-iceoryx/iceoryx#2180]
## Required information
iox::errorHandler(iox::Error,std::function<void ()> const&, iox::ErrorLevel) () from /lib/libiceoryx hoofs.so
iox:popo::ThreadSafePolicy::lock() const () from /lib/libiceoryx posh.sc
iox::popo::PublisherPortuser::sendchunk(iox: :mepoo::ChunkHeader*) () from /lib/libiceoryx posh,so
**Operating system:**
E.g. Ubuntu 20.04 LTS

**Compiler version:**
E.g. GCC 9.3.0

**Eclipse iceoryx version:**
E.g. `v2.0.1`

**Observed result or behaviour:**
A clear and precise description of the observed result.

**Expected result or behaviour:**
Not coredump, what case result in the threadsafepolicy lock failing?

**Conditions where it occurred / Performed steps:**
Describe how one can reproduce the bug.

**Comment by lizhaoce905** [comment]
![img_v3_02fi_1fb3d19c-1d4e-4899-b9bf-2cd9b8eb53ag](https://github.com/user-attachments/assets/9279f07c-07df-41dc-a2c2-0dc18d3f4467)
 i

**Comment by lizhaoce905** [comment]
![img_v3_02fi_1fb3d19c-1d4e-4899-b9bf-2cd9b8eb53ag](https://github.com/user-attachments/assets/8ea9d45c-6fd5-48ed-9678-7941b10cfcd1)

**Comment by elBoberido** [comment]
@lizhaoce905 the backtrace shows a problem with a lock in `ddsrt_mutex_lock`. That's not iceoryx code.
