### ISSUE TITLE
Test Fixtures for RouDi

### ISSUE THREAD

**Issue by geke-mir** [eclipse-iceoryx/iceoryx#2186]
Is it possible to start the RouDi daemon in a google test fixture so I can perform integration tests on my application?  If so, is there any code I can model my tests off of?  I read the entry in the documentation, but it was at a higher level than actually writing tests that used the iceoryx library.

**Comment by elBoberido** [comment]
@geke-mir there is `RouDiEnv` and `RouDi_GTest` which uses the `RouDiEnv`

An example for `RouDi_GTest` is `iceoryx_posh/test/integrationtests/test_popo_pub_sub_listener.cpp` and for `RouDiEnv` there is `iceoryx_posh/test/moduletests/test_posh_runtime_node.cpp`.

Does this answer your question?

**Comment by geke-mir** [comment]
Thanks for the references, I believe so
