### ISSUE TITLE
Problems with multiple "persistent" publishers on the same topic at subscriber startup

### ISSUE THREAD

**Issue by FabioBagni** [eclipse-iceoryx/iceoryx#2207]
Hi,
we're having trouble trying to implement "persistent" publishers and subscribers.

To do that we are initializing publishers with `publisherOptions.historyCapacity = 10` (or any size > 0), and subscribers with `subscriberOptions.historyRequest = 1`.

With these options, the subscriber receives the latest published message at its creation.

The problem is that if we have multiple publishers with these options publishing on the same topic, the subscriber receives the latest published message from each publisher.

So, is there a way to understand which one of the received messages is the latest?

**Comment by elBoberido** [comment]
@FabioBagni Are your questions answered and can this be closed?

**Comment by FabioBagni** [comment]
Yes the answers are very clear, thanks.

I solved it writing timestamp inside the payload and manually discarding everything but the latest.
