### ISSUE TITLE
Add aliases that conform with other STL container types

### ISSUE THREAD

**Issue by gmandhyan** [eclipse-iceoryx/iceoryx#2220]
## Brief feature description

Add aliases that conform with other STL container types

## Detailed information

The current iox container types such miss a lot of aliases normally present in STL type containers, such as `size_type`, `index_type`, `reference`, `const_reference`, `difference_type`. These are normally useful in writing type traits for STL and STL-like container types and are used a lot in templated code.

**Comment by elBoberido** [comment]
@gmandhyan would be great to have those aliases. Patches welcome :)

**Comment by gmandhyan** [comment]
Have a PR up, appreciate your review 🙏 
https://github.com/eclipse-iceoryx/iceoryx/pull/2223
