### ISSUE TITLE
[BUG] bazel http_archive iceoryx as 3rdparty dependency report errors.

### ISSUE THREAD

**Issue by ZhenshengLee** [eclipse-iceoryx/iceoryx#2240]
## Required information

**Operating system:**
E.g. Ubuntu 22.04 LTS

**Compiler version:**
E.g. GCC 9.4.0

**Eclipse iceoryx version:**
master

**bazel version**
7.0.2

**bazel config**

```bzl
    http_archive(
        name = "oss_eclipse_iceoryx",
        # sha256 = "d0f5f605d0d656007ce6c8b5a82df3037e1d8fe8b121ed42e536f569dec16113",
        # patches = [clean_dep("//bazel/3rdparty/protobuf:protobuf.patch")],
        strip_prefix = "iceoryx-master",
        urls = [
            "https://github.com/eclipse-iceoryx/iceoryx/archive/refs/heads/master.zip",
        ]
    )
```

**Observed result or behaviour:**

```sh
(02:33:47) INFO: Current date is 2024-04-02
(02:34:26) DEBUG: Rule 'oss_eclipse_iceoryx' indicated that a canonical reproducible form can be obtained by modifying arguments integrity = "sha256-fLUCR67j0Q/wVL9Y+ipcBL0LHjuG3SLt+KpxTe0m2Fk="
(02:34:26) DEBUG: Repository oss_eclipse_iceoryx instantiated at:
  /gw_demo/WORKSPACE:7:18: in <toplevel>
  /gw_demo/bazel/workspace.bzl:78:27: in gaos_repositories
  /gw_demo/bazel/workspace.bzl:57:12: in initialize_third_party
  /gw_demo/bazel/3rdparty/iceoryx/workspace.bzl:15:17: in repo
Repository rule http_archive defined at:
  /home/zs/.cache/bazel/_bazel_zs/2c098eac6c684e1fabebb74f5f4483bd/external/bazel_tools/tools/build_defs/repo/http.bzl:381:31: in <toplevel>
(02:34:26) ERROR: error loading package '@@oss_eclipse_iceoryx//': Unable to find package for @@com_github_bazelbuild_buildtools//buildifier:def.bzl: The repository '@@com_github_bazelbuild_buildtools' could not be resolved: Repository '@@com_github_bazelbuild_buildtools' is not defined.
(02:34:26) ERROR: /gw_demo/gaos/tools/system_test/test_cm/BUILD:5:13: error loading package '@@oss_eclipse_iceoryx//': Unable to find package for @@com_github_bazelbuild_buildtools//buildifier:def.bzl: The repository '@@com_github_bazelbuild_buildtools' could not be resolved: Repository '@@com_github_bazelbuild_buildtools' is not defined. and referenced by '//gaos/tools/system_test/test_cm:test_socket'
(02:34:26) ERROR: Analysis of target '//gaos/tools/system_test/test_cm:test_socket' failed; build aborted: Analysis failed
(02:34:26) INFO: Elapsed time: 38.788s, Critical Path: 0.04s
(02:34:26) INFO: 1 process: 1 internal.
(02:34:26) ERROR: Build did NOT complete successfully
```

**Expected result or behaviour:**

bazel using iceoryx as a 3rdparty elegantly.

**Comment by elfenpiff** [comment]
@ZhenshengLee I think on our side the expertise with bazel is very limited. Would you be able to support us here? Or give us some detailed pointers what elegantly means?

**Comment by phongt** [comment]
@ZhenshengLee  You need to add this to `WORKSPACE` . I can use iceoryx as external repo with it.
```
load("@oss_eclipse_iceoryx//bazel:load_repositories.bzl", "load_repositories")
load_repositories()
load("@oss_eclipse_iceoryx//bazel:setup_repositories.bzl", "setup_repositories")
setup_repositories()
```
My setup like this here: 
https://github.com/phongt/helloworld_iox/

**Comment by elBoberido** [comment]
@phongt would be great if you could add that to our examples

**Comment by phongt** [comment]
> @phongt would be great if you could add that to our examples

@elBoberido  the examples are having bazel [rules](https://github.com/eclipse-iceoryx/iceoryx/blob/master/WORKSPACE.bazel) there in the same repo with `iceoryx`. In this use case my understanding is using `iceoryx` from external repo. So the [bazel rules](https://github.com/eclipse-iceoryx/iceoryx/issues/2240#issuecomment-2041057335) here is necessary. 

I would say to add it to docs one section  _How to use iceoryx with bazel_
https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/FAQ.md
How do you think?

**Comment by elBoberido** [comment]
@phongt that would also work

I'm not that familiar with bazel so I thought it might work if there is an example which is not in the workspace file of iceoryx but has its own workspace file with iceoryx as external dependency.

Either way, it would be good to have some documentation on how to use iceoryx as external dependency with bazel
