### ISSUE TITLE
how to run ice_access_control demo

### ISSUE THREAD

**Issue by Autostone-c** [eclipse-iceoryx/iceoryx#2267]
I want to run the demo of ice access control on a Ubuntu 22.04, but I don't know how to do it. The four terminals in the video used different usernames, but the config script set a parameter to prohibit login. Perhaps you could provide a detailed tutorial in the video

**Comment by elfenpiff** [comment]
It seems that the example is currently broken. Could you please open `config_and_run_ice_access_control.sh` and change line 27 into
```
TMUX="tmux -2 -q"
```

and tell us if this fixes your issue.

Did you execute the command
```sh
./config_and_run_ice_access_control.sh config
```

before you executed the example with
```sh
./config_and_run_ice_access_control.sh run
```

Sometimes, the user and group information are not updated in your current session until you re-login. Could you try this as well please.

**Comment by Autostone-c** [comment]
> 看来这个例子目前已经被破坏了。能否请您打开`config_and_run_ice_access_control.sh`第 27 行并将其更改为
> 
> ```
> TMUX="tmux -2 -q"
> ```
> 
> 并告诉我们这是否可以解决您的问题。
> 
> 你执行命令了吗
> 
> ```shell
> ./config_and_run_ice_access_control.sh config
> ```
> 
> 在执行示例之前
> 
> ```shell
> ./config_and_run_ice_access_control.sh run
> ```
> 
> 有时，在您重新登录之前，当前会话中的用户和组信息不会更新。您也可以尝试一下吗？

hi，thanks for your reply. I have modified and run what you said. but i get nothing on my terminal

**Comment by elfenpiff** [comment]
Could you start it manually.
1. Open 4 Terminals
2. In every terminal, go inside the iceoryx directory and then type `cd build/iceoryx_examples/ice_access_control/`
3. Terminal 1: Start roudi with user `roudi` and group `iceoryx` with `sudo -u roudi -g iceoryx -- ./iox-cpp-roudi-static-segments`
4. Terminal 2: Start the radar app with user `perception` and group `iceoryx` via `sudo -u perception -g iceoryx -- ./iox-cpp-radar`
5. Terminal 3: Start the display app with user `infotainment` and group `iceoryx` via `sudo -u infotainment -g iceoryx -- ./iox-cpp-display`
6. Terminal 4: Start the application that is not allowed to participate in the communication `sudo -u notallowed -g iceoryx -- ./iox-cpp-cheeky'. Here you should observe an error.

Did the single steps work?

**Comment by Autostone-c** [comment]
> 4\. sudo -u perception -g iceoryx -- ./iox-cpp-radar

something wrong like 
![image](https://github.com/eclipse-iceoryx/iceoryx/assets/50130211/14ff5823-3bf5-40c4-8030-bf97c92ea8b2)

**Comment by Autostone-c** [comment]
this is my User Configuration
![image](https://github.com/eclipse-iceoryx/iceoryx/assets/50130211/f6c7bda4-0f47-4ac9-81ca-5afc2873754e)

**Comment by Autostone-c** [comment]
> 5\. sudo -u infotainment -g iceoryx -- ./iox-cpp-display

![image](https://github.com/eclipse-iceoryx/iceoryx/assets/50130211/e1e410c0-ca0c-4f6a-b7ad-0bcfeff81e13)
Have you ever encountered this error

**Comment by elBoberido** [comment]
I think you get this if there are some remnants of an old application with the same name, e.g. when you started that application with a different user and that application was not shut down gracefully. When the application is restarted, it notices that there are some remnants and tries to clean them up but they were created by a different user, it fails.

**Comment by elfenpiff** [comment]
@Autostone-c I think I quick fix would be to restart the system, then those remnants should be cleaned up. 

You can do this also manually by calling:
```sh
rm -rf /dev/shm/* # removes all shared memory data segments
rm -rf /tmp/$APP_NAME$* # removes all iceoryx lock files and sockets
```

For instance for the application `iox-cpp-display` it should be

```sh
rm -rf /tmp/iox-cpp-display*
```

Please check manually via `ls -alh /tmp/` the files.

**Comment by Autostone-c** [comment]
I have resolved the issue and need to add the dell user to the iceoryx group as well as delete the temporary files in the /tmp directory，i will close this issues

**Comment by elBoberido** [comment]
@Autostone-c @elfenpiff since iceoryx now uses a prefix for it's resources, it is sufficient to just do `rm -rf /dev/shm/iox1*` and `rm -rf /tmp/iox1*`. No need to remove unrelated shm files anymore
