### ISSUE TITLE
ICEORYX error! POPO__CHUNK_LOCKING_ERROR

### ISSUE THREAD

**Issue by deepaksree** [eclipse-iceoryx/iceoryx#2276]
## Required information

**Operating system:**
E.g. Ubuntu 20.04 LTS

**Compiler version:**
E.g. GCC 7.4.0

**Observed result or behaviour:**
Iox-roudi publisher application exits saying popo chunk locking error

**Expected result or behaviour:**
What do you expect to happen?
publisher continues operation without exiting
**Conditions where it occurred / Performed steps:**

## Additional helpful information
ICEORYX error! POPO__CHUNK_LOCKING_ERROR**

**Comment by elBoberido** [comment]
Can you give us more infos, like the iceoryx version, OS and your setup?

My guess is that there are two processes which publish to the same topic, right?
I would also guess that one of these two process crashed or was killed with `kill -9` ... I'm not sure if `ctrl+c` could also lead to this scenario if there is no signal handler to shut the application down gracefully.

Are my assumptions correct?

**Comment by deepaksree** [comment]
we are using iceoryx-version v2.0.3. OS is custom LMP OS(but consider it close to ubuntu). 

SetUp: Roudi daemon is started and then I start the publisher application. It runs and sometimes it throws the below error
`navsensord[10963]: Informational: �[0;90m2024-02-11 19:00:04.330 �[0;1;31;103m[ Error ]�[m: ICEORYX error! POPO__CHUNK_LOCKING_ERROR`

When this error is thrown my publisher application is exiting out as below
```
887490 2024/04/22 22:28:42.000000 70.2888 255 LNX SYS JOUR 689 log info verbose 5 2024/02/11 19:00:04.331012 70.217582 navsensord[10963]: Informational: terminate called without an active exception
887492 2024/04/22 22:28:42.000000 70.2888 1 LNX SYS JOUR 689 log warn verbose 5 2024/02/11 19:00:04.333680 70.221799 kernel: Warning: CPU: 2 PID: 10963 Comm: navsensord Tainted: G W OE 5.15.104 https://github.com/eclipse-iceoryx/iceoryx/issues/1
887515 2024/04/22 22:28:42.000000 70.5656 24 LNX SYS JOUR 689 log warn verbose 5 2024/02/11 19:00:04.539121 70.425722 systemd[1]: Warning: navsensord.service: Main process exited, code=dumped, status=6/ABRT
887516 2024/04/22 22:28:42.000000 70.5656 25 LNX SYS JOUR 689 log warn verbose 5 2024/02/11 19:00:04.539226 70.425953 systemd[1]: Warning: navsensord.service: Failed with result 'core-dump'.
```
We are not closing the publisher application by ourselves this popo chunk error occurs and the publisher app crashes on its own

**Comment by elBoberido** [comment]
Do you have more infos?

Which iceoryx version are you running? Which OS? What's the output of RouDi? What's your exact setup, e.g. which appications are connected in which way to the crashing application?

**Comment by deepaksree** [comment]
issue closed
