### ISSUE TITLE
How to setting the right val of size and count in toml config ?

### ISSUE THREAD

**Issue by lix19937** [eclipse-iceoryx/iceoryx#2340]
Usually toml file content is follow  
```
[general]
version = 1

[[segment]]


[[segment.mempool]]
size = 43336
count = 50

[[segment.mempool]]
size = 563336
count = 50

[[segment.mempool]]
size = 2096776
count = 50

[[segment.mempool]]
size = 46489736
count = 70  
``` 

@elBoberido  Can you give me the guide/document  about the **size** and **count** in segment.mempool ?   

I usually set **size** = sizeof(msg) + `offset`,  offset maybe 96 or other value at present.    
I guess that the **count** maybe related with the sub depth and subcallback(sub msg then pub )latency ?

**Comment by elBoberido** [comment]
@lix19937 from your comment https://github.com/eclipse-iceoryx/iceoryx/issues/2337#issuecomment-2324209687 I think you already found the solution in https://github.com/eclipse-iceoryx/iceoryx/blob/main/doc/website/advanced/configuration-guide.md

Closing this issue. Feel free to re-open if you still have problems.
