### ISSUE TITLE
Add PortThroughputIntrospectionTopic

### ISSUE THREAD

**Issue by consolexinhun** [eclipse-iceoryx/iceoryx#2347]
## Brief feature description

I want to get information about PortThroughputIntrospectionTopic in iox-introspection

## Detailed information

`PortIntrospection<PublisherPort, SubscriberPort>::PortData::prepareTopic(PortThroughputIntrospectionTopic& topic)` is unimpliment （https://github.com/eclipse-iceoryx/iceoryx/blob/main/iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.inl#L597），when will this feature be ready?

**Comment by elBoberido** [comment]
@consolexinhun currently there is no-one working on this and the focus of the core team is shifting more and more towards iceoryx2.

**Comment by elBoberido** [comment]
Closing the issue since it is a duplicate of #402
