### ISSUE TITLE
The issue with generating deb packages

### ISSUE THREAD

**Issue by Heyangq** [eclipse-iceoryx/iceoryx#2354]
## Required information

**Operating system:**
Ubuntu 20.04 LTS

**Compiler version:**
GCC 9.4.0

**Eclipse iceoryx version:**
`main` branch

**Observed result or behaviour:**
Unable to modify the installation path of the deb package

**Expected result or behaviour:**
I want to change the installation path of the deb package, but the deb package I generated has always been in"/usr", even though I set INSTALL-PREFIX

**Comment by Heyangq** [comment]
I found that CPack uses the default prefix, and using CMAKE-INSTALL-PREFIX does not work. We need to modify the default prefix of PACKING in package.cmake
As follows:

cmake_minimum_required(VERSION 3.16)
set(IOX_VERSION_STRING "2.95.2")

project(iceoryx_package VERSION ${IOX_VERSION_STRING})


set(CPACK_GENERATOR "DEB")
set(CPACK_PACKAGE_NAME "iceoryx-${iceoryx_package_VERSION}")
set(CPACK_PACKAGE_FILE_NAME "iceoryx_${iceoryx_package_VERSION}_${CMAKE_CXX_COMPILER_ID}-${CMAKE_CXX_COMPILER_VERSION}")
set(CPACK_PACKAGE_CONTACT "iceoryx-oss-support@apex.ai")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libacl1-dev,libncurses5-dev")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "iceoryx inter-process-communication (IPC) middleware")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/eclipse-iceoryx/iceoryx")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "https://projects.eclipse.org/projects/technology.iceoryx/who")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/../LICENSE")
**_set(CPACK_PACKAGING_INSTALL_PREFIX "/usr/local")_**
include(CPack)

**Comment by Heyangq** [comment]
I will close this issue. I am very sorry

**Comment by elBoberido** [comment]
@Heyangq no problem :)
