### ISSUE TITLE
Meet error: AllocationError::TOO_MANY_CHUNKS_ALLOCATED_IN_PARALLEL

### ISSUE THREAD

**Issue by jerry-xie-000** [eclipse-iceoryx/iceoryx#2358]
The variable `g_data_size` for publisher loan size should be modified each time, maybe 200, 2000,20000,200000,  200, 2000...

```
    iox::popo::UntypedPublisher publisher({"adc", "data", "Object"});

while(true)
{
   publisher.loan(g_data_size))
              .and_then([&](auto& userPayload) {   ...   }
}
```

After changing many times with different loan data size , these errors will be shown:
```
Unable to loan sample, error code: AllocationError::TOO_MANY_CHUNKS_ALLOCATED_IN_PARALLEL
Unable to loan sample, error code: AllocationError::TOO_MANY_CHUNKS_ALLOCATED_IN_PARALLEL
Unable to loan sample, error code: AllocationError::TOO_MANY_CHUNKS_ALLOCATED_IN_PARALLEL
Unable to loan sample, error code: AllocationError::TOO_MANY_CHUNKS_ALLOCATED_IN_PARALLEL
Unable to loan sample, error code: AllocationError::TOO_MANY_CHUNKS_ALLOCATED_IN_PARALLEL
```
Is my usage wrong? We need to change loan data size in different situation.

**Comment by elfenpiff** [comment]
@jerry-xie-000 are you sending the message with `publisher.publish()`? or releasing it in any other way?

**Comment by jerry-xie-000** [comment]
Yes, I sending the message with `publisher.publish()`
```
  iox::popo::UntypedPublisher publisher({"adc", "data", "Object"});

while(true)
{
   publisher.loan(g_data_size))
              .and_then([&](auto& userPayload) {  
                    ... 
                publisher.publish(userPayload);
                          }
}
```
I just run the publisher application, and doesn't run the subscriber.

I try to just change the size with two different size, the errors can be reproduced.

**Comment by elfenpiff** [comment]
@jerry-xie-000 The error message `Unable to loan sample, error code: AllocationError::TOO_MANY_CHUNKS_ALLOCATED_IN_PARALLEL` should only come when you loan messages on the publisher side and never release them. But since you call `Publisher::publish()` which releases them, it should not occur.
Do you store some of the samples and do not publish them?

@elBoberido do you have any ideas here?

**Comment by jerry-xie-000** [comment]
Sorry, it's my mistake. There is one code to return the function before `Publisher::publish()`.
