### ISSUE TITLE
Async connect iox-roudi

### ISSUE THREAD

**Issue by owny990312** [eclipse-iceoryx/iceoryx#2374]
Currently, using pub/sub blocks when iox-roudi is not running. Can it asynchronously wait without blocking subsequent operations? 
Additionally, when iox-roudi is closed, can pub/sub enter a suspended state and wait to resume when iox-roudi is running again, instead of exiting directly?

**Comment by elBoberido** [comment]
I'm not sure if I understand you correctly but classic iceoryx requires iox-roudi to run all the time. With the next-gen iceoryx2 we switched to a decentralized approach without a daemon. Maybe that's a better fit to your problem.
https://github.com/eclipse-iceoryx/iceoryx2
It almost reached feature parity with classic iceoryx. The only missing feature is request-response.

**Comment by owny990312** [comment]
> I'm not sure if I understand you correctly but classic iceoryx requires iox-roudi to run all the time. With the next-gen iceoryx2 we switched to a decentralized approach without a daemon. Maybe that's a better fit to your problem.I'm not sure if I understand you correctly but 经典 iceoryx 要求 iox-roudi 一直运行。新一代 iceoryx2 我们采用了去中心化的 approach 没有守护进程。也许这更适合你的问题。 https://github.com/eclipse-iceoryx/iceoryx2 It almost reached feature parity with classic iceoryx. The only missing feature is request-response.它几乎达到了与经典 iceoryx 的功能平齐。唯一缺少的功能是请求-响应。

thanks for your reply, iceoryx2 has excellent performance, but, now ,we need rpc in project. I want to know, when she iox-roudi shutdown, the publisher or subscribe node can alive not be killed by iox-roudi
