### ISSUE TITLE
Broken link in single process readme

### ISSUE THREAD

**Issue by EgorWeders** [eclipse-iceoryx/iceoryx#2389]
[Check out singleprocess on GitHub :fontawesome-brands-github:]([https://github.com/eclipse-iceoryx/iceoryx/tree/main/iceoryx_examples/singleprocess){](https://github.com/eclipse-iceoryx/iceoryx/tree/main/iceoryx_examples/singleprocess)%7B) .md-button }

**Comment by EgorWeders** [comment]
Found  comment, so it is not an issue?

**Comment by elBoberido** [comment]
This is required for mkdocs to work. We are already looking for a solution in #1299
