### ISSUE TITLE
Integration test for posh-runtime class

### ISSUE THREAD

**Issue by nihalchari** [eclipse-iceoryx/iceoryx#240]
This is in continuation with Iox #177 unit test for posh runtime.
Test to be covered 

    findService
        reoffer service
        mix up of AnyService, AnyInstance, AnyEvent
    offerService
        call offer service twice
    stopOfferService
        call with invalid serviceDescription like {AnyService, AnyInstance, AnyEvent}
        call with non existing serviceDescription
        call stop offer service twice

**Comment by dkroenke** [comment]
@nihalchari this can be closed or?

**Comment by nihalchari** [comment]
yes @dkroenke , ill close it

**Comment by nihalchari** [comment]
closed by mistake, reopening,

**Comment by ithier** [comment]
@nihalchari Why was this reopenned ?

**Comment by nihalchari** [comment]
@ithier   This is in continuation with https://github.com/eclipse/iceoryx/pull/214  unit test for posh runtime., this issue was closed by mistake, actually 177 should hvae closed
