### ISSUE TITLE
Request/Response communication with iceoryx

### ISSUE THREAD

**Issue by budrus** [eclipse-iceoryx/iceoryx#27]
## Brief feature description

Besides publish/subscribe also request/response communication shall be supported

## Detailed information

So far iceoryx only supports publish/subscribe. For frameworks like ROS2 also a request/response communication shall be supported (services in ROS2).  The building blocks in posh can be re-used here, so start with client and server ports and then do the layers above

We will have the same layered architecture as for publishers and subscribers. With `ChunkSender` and `ChunkReceiver` common building blocks are reused but a `Client` and a `Server` will use one of each for the bidirectional data transfer with requests and responses. 
This image is a simplified view that shows the class hierarchy and the public method names for the typed C++ API. 

![component](https://user-images.githubusercontent.com/55156294/109230075-8db9ee00-77c4-11eb-8a29-913808769f35.png)

1. It will also have a zero-copy API, i.e. we can loan requests and take responses on the `Client` side and take requests and loan responses on the `Server` side.   
1. Like a `Publisher`, a `Server` can `offer()` or `stopOffere()`
2. Similar to a `Subscriber` `subscribe()` and `unsubscribe()`, the `Client` can `connect()`, `disconnect()` and getConnectionState()
3. You can poll the `Server` for requests and the `Client` for responses or use a `Waitset` to wait for requests and responses 

- [x] 1. Design and interface implementation for ports

- [x] 2. Implementation and unit tests for ports

- [x] 3. Integration test for ports
   - [x] including QueueFullPolicy tests with a real Client- and ServerPort

- [x] 4. C API 
   - [x] client
   - [x] request/response header
   - [x] server
   - [x] examples
   - [ ] (optional) add `iceoryx_posh_types.hpp` RPC related config stuff to `config.h`.
   - [ ] (optional) add missing functionality to chunk header

- [x] 5. C++ API
   - [x] typed C++ API 
   - [x] tests for typed C++ API
   - [x] untyped C++ API
   - [x] tests for untyped C++ API
   - [x] send returns an expected instead of void

- [x] 6. Integration in runtime and RouDi
   - [x] Make `ServerPort`'s findable via `ServiceDiscovery` 

- [x] 7. Common port queue policies
    - rename `SubscriberTooSlowPolicy` -> `ConsumerTooSlowPolicy`
        - alias for ConsumerTooSlowPolicy for easy migration to new API
        - rename `WAIT_FOR_SUBSCRIBER` -> `WAIT_FOR_CONSUMER`
        - add `WAIT_FOR_SUBSCRIBER = WAIT_FOR_CONSUMER` for migration purposes
    - rename `QueueFullPolicy::BLOCK_PUBLISHER` -> `QueueFullPolicy::BLOCK_PRODUCER`
        - add `BLOCK_PUBLISHER = BLOCK_PRODUCER` for migration purposes
    - decide if `SubscriberTooSlowPolicy`, `WAIT_FOR_SUBSCRIBER` and `BLOCK_PUBLISHER` should be deprecated

- [ ] 8. Integration test with clients, server and waitsets (user API level)

- [ ] 9. Example

**Comment by budrus** [comment]
@Karsten1987 let's get the party started

**Comment by tolga-talkme** [comment]
is it possible to use iceoryx in this way?
I mean as in request<->response way

**Comment by elBoberido** [comment]
@tolga-talkme yes. There is a [request/response example](https://github.com/eclipse-iceoryx/iceoryx/tree/master/iceoryx_examples/request_response)
