### ISSUE TITLE
Restructuring of Cmake files in iceroyx

### ISSUE THREAD

**Issue by dkroenke** [eclipse-iceoryx/iceoryx#280]
The CMakelists.txt for posh and utils are very large and aggregate multiple targets in it for different purposes (e.g. iceoryx_utils_testing) which make it harder to maintain. Goal is to split up the CMake files and create new ones in the right place.

**Comment by andre-nguyen** [comment]
Is this still an issue? Looks like `utils` has been refactored into `hoofs`?

**Comment by elBoberido** [comment]
@andre-nguyen it should be. Except the renaming, the CMakeLists.txt didn't change much.
