### ISSUE TITLE
NewType Copy-Assign raises compiler warning on GCC 8.4.0

### ISSUE THREAD

**Issue by ithier** [eclipse-iceoryx/iceoryx#282]
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Compiler version:**
GCC 8.4.0

**Observed result or behaviour:**
The following test for the NewType class in utils causes an incorrect compiler warning:
```
TEST(NewType, CopyAssignableDoesCompile)
{
    Sut<cxx::NewType<int, newtype::ConstructByValueCopy, newtype::CopyAssignable, newtype::Comparable>> a(491), b(492),
        c(423);
    b = a;
    EXPECT_TRUE(a == b);
}
```

The warning "deprecated-copy" is raised at `b = a;` despite the NewType having no deprecated copy constructor.
The source of the error might be elsewhere but this is not clear to me.

GCC 8.4.0 is what is used on the Github Workflow VM so this test causes the build to fail and thus blocks merges.

**Expected result or behaviour:**
This code should compile without warning.

**Conditions where it occurred / Performed steps:**
Compile on GCC 8.4.0

**Comment by elBoberido** [comment]
@dkroenke I think this is because we use this ugly `#pragma GCC diagnostic ignored "-Wdeprecated-copy"`. It's currently only an issue in `test_cxx_newtype.cpp` because it is not used anywhere else with the copy constructor. There is an easy fix for this though, we just have to create the class like this
```cpp
struct Foo : public cxx::NewType<...>
{
    /* this is already in the documentation of the NewType pattern */
    using ThisType::ThisType;
    using ThisType::operator=; // bring all operator= into scope

   /* this is new */
    // implement copy and move ctors when they are implemented by the base class
    Foo(const Foo&) = default;
    Foo(Foo&&) = default;

    // implement copy and move assingment when they are implemented by the base class
    Foo& operator=(const Foo&) = default;
    Foo& operator=(Foo&&) = default;
};
```

@elfenpiff @MatthiasKillat do you think there are any reasons not to do it as suggested?

**Comment by elfenpiff** [comment]
@elBoberido no I am fine with this :D
