### ISSUE TITLE
Modern logging

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx#296]
## Brief feature description

Stream based logging is quite slow and not the recommended modern way.

## Detailed information

There are fast and modern alternatives, like [fmt](https://github.com/fmtlib/fmt) which uses the new C++20 [format](
https://en.cppreference.com/w/cpp/utility/format) API.

We should have a look at fmt and decide if it's possible to make it stack based or maybe implement the C++20 format API based on the cxx::string.

**Comment by mossmaurice** [comment]
Closing, as superseded by #1345
