### ISSUE TITLE
offerService should not allow invalid ServiceDescriptions

### ISSUE THREAD

**Issue by nihalchari** [eclipse-iceoryx/iceoryx#359]
- adjust offerService() behavior so that it should not allow invalid ServiceDescriptions
(https://github.com/eclipse/iceoryx/blob/master/iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp)

- offerService should return a bool signalling if it was successful

- add more test cases to verify the behavior fully

**Comment by dkroenke** [comment]
@nihalchari 
This issue was already resolved by https://github.com/eclipse-iceoryx/iceoryx/pull/342, therefore i close it.
