### ISSUE TITLE
Clean up all shared memory resources when corresponding user objects go out of scope

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#369]
## Brief feature description

Publisher, Subscriber, Runnables and other resources can be allocated in the shared memory via roudi runtime calls like `getMiddlewarePublisher`. There is the possibility to clean up ports with the `destroy` method provided by the` BasePort`. But we have to extend this to all shared memory resources like condition variables and also the runtime itself

This is essential since the resources are allocated by our classes in our public API and when they go out of scope we have a resource leak inside of the shared memory. RouDi cleans up resources when the application terminates and the monitoring is active but we should do the clean up for all resources created by objects from the public API that can go out of scope 

## Detailed information

We have to take care of (and also have to consider that there are C and C++ APIs)

- [x] Publisher Ports

- [x] Subscriber Ports 

- [x] Application Port

- [x] Interface Port

- [x] Nodes

- [x] Condition Variables

- [x] Runtime

**Comment by budrus** [comment]
The old API uses the `destroy()` call in the d'tor. Then the discovery loop will do the job. like [here](https://github.com/eclipse/iceoryx/blob/master/iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber.inl#L42)

You haver to call it also for the new public API classes @elfenpiff @ithier. These cleanup calls wpould be another option, both have pros and cons. If you do the cleanup approach you have to be careful not to destroy e.g. subscribers that are still conneczted with publishers. The destroy flag approach handles all of this but delays the actual destroy till the next discovery loop

**Comment by ithier** [comment]
Adding `destroy` logic to the destructors makes sense to me.
When else would a user application want to clean up the e.g.  `PublisherPortUser"?
So, we should add `destroy` methods to the ports so the public entities (publishers, subscribers etc.) can do this.

**Comment by budrus** [comment]
I guess you have it in the Base Pott, so the d'tors of the public API classes can call it on the port objects they have

**Comment by budrus** [comment]
We have to take care of all resources: Ports(Publisher, Subscriber, Application, Interface), Condition Variables, Runnables and the Runtime. I'll update this issue and we will address them all. E.g. the Runtime does not signal to RouDi when it is destroyed and we need the monitoring to start cleaning up things
