### ISSUE TITLE
Review `cxx::optional` and adjust it to newest C++ proposal

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#392]
## Brief feature description

The current `optional` implementation does not support all monadic operations suggested in that paper: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0798r3.html 

We should read and explore the paper and if some ideas are applicable we should implement them - like chaining and transform.

Additionally, it would be great if we could chain `and_then` and `or_else` with in a generic way with other constructs which are offering `and_then` and `or_else` like the `expected`.

**Comment by MatthiasKillat** [comment]
I support this and have already experimented with this, we need something similar to the monadic bind operation >>=. I propose adding some suitable operator to do so. This operator must be left associative to be useful. I propose just using operator>> (>>= is right assoicative...). Adding a named function with the same semantics in addition is possible.

Note that this can even be somewhat generalized to cxx::expected, but imposes (mostly reasonable) limitations on the the return values of the functions called in the success and error cases.

**Comment by ithier** [comment]
I've got the `and_then` functionality working in #395 and have also generalized it to work with `cxx::expected` too.
It's still a work in progress though and needs some more testing.
I will try and deal with the `or_else` case in this PR too. As for `transform`, I would leave that as the next step.

**Comment by MatthiasKillat** [comment]
The tricky part is to define something reasonable for std::expected. I had something fancy in mind such as some function (or ``operator()``) taking two functions, one for the successful case and one for the error case.

Assume this function is called ``apply_either`` and we have some result of type ``expected<T,E>``:

``result.apply_either(f1,g1).apply_either(f2,g2);``

Semantically it would apply f1 in the value case and g1 in the error case. Now, for this to properly be chainable f1 and g1 would need to return an expected of compatible (same) type as well. The idea is to chain the success cases and the error cases respectively.

This does not help for the real general case where you have multiple values and want to apply a function on them though, but neither does the optional.

BTW: I really think expected needs to be called result, in functional programming parlance it is (almost) the either monad.

**Comment by elfenpiff** [comment]
@MatthiasKillat I agree with you, it should be called result. But in the C++ world it is known as expected and for that reason I would keep the name as it is since we are also trying to implement somehow the proposed interface and behavior.

**Comment by MatthiasKillat** [comment]
Yes, but I would leave the possibility open to extend it with useful functionality which we can call however we see fit. The class name may stay as is, does not matter to much to me.

**Comment by elfenpiff** [comment]
Already implemented in #131 .

**Comment by elBoberido** [comment]
I think we have to work on the tracing front. Out of interest I wanted to see what was changed but couldn't find any relevant PR

**Comment by elfenpiff** [comment]
@elBoberido You are right! I looked it up in git blame and the only thing I found was the issue linked above.
