### ISSUE TITLE
roudi_lock should use UDS

### ISSUE THREAD

**Issue by dkroenke** [eclipse-iceoryx/iceoryx#470]
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Compiler version:**
GCC 7.5.0

**Observed result or behaviour:**
In the RouDiLock Class is a socket used to prevent the startup of multiple instances of RouDi. This socket is an `AF_INET` socket which binds to a TCP port. A second starting instance is trying to bind that port and fails with that.

**Expected result or behaviour:**
Instead of using a TCP port Unix Domain Socket with `AF_LOCAL` should be used to avoid conflicts with other applications who wants to use that port in future.

**Comment by elBoberido** [comment]
Are you sure that Unix Domain Sockets are automatically cleaned up when an application crashes?

**Comment by dkroenke** [comment]
> Are you sure that Unix Domain Sockets are automatically cleaned up when an application crashes?

It seems not, the binding still persist when a crash occurs and the next time when you try to bind it throws `[ 98 ]  Address already in use`. So the UDS is not an option then anymore.

Maybe we create an internal port with latched topic which sets some value. The next RouDi connect to the Port and see that the value is set.

**Comment by elBoberido** [comment]
You still have the race. How does RouDi know to register at another RouDi? When there is no RouDi and you start two of them, how do they decide which one creates the resources?

**Comment by mossmaurice** [comment]
Closing this issue as the `RouDiLock` was removed with #687
