### ISSUE TITLE
Evaluation and restructuring of tools 

### ISSUE THREAD

**Issue by dkroenke** [eclipse-iceoryx/iceoryx#471]
## Brief feature description
For making iceoryx more stable, we need to look for better tooling to do code analysis and support the developer.
We should also take a deeper look into the ROS side what there is used, e.g. ament_lint.
Proposals are welcome!

List of common tools from ROS2:
* `ament_cmake_copyright <https://github.com/ament/ament_lint/blob/master/ament_cmake_copyright/doc/index.rst>`_ : a copyright linter which checks that copyright statements and license headers are present and correct (already integrated)

* `ament_cmake_cppcheck <https://github.com/ament/ament_lint/blob/master/ament_cmake_cppcheck/doc/index.rst>`_ : a C++ checker which can also find some logic tests (Not to be used because there is already clang-tidy)

* `ament_cmake_cpplint <https://github.com/ament/ament_lint/blob/master/ament_cmake_cpplint/doc/index.rst>`_ : a C++ style checker (e.g. comment style)

* `ament_cmake_lint_cmake <https://github.com/ament/ament_lint/blob/master/ament_cmake_lint_cmake/doc/index.rst>`_ : a cmake linter (Not to be used with ament to avoid hard ROS dependency)

* `ament_cmake_uncrustify <https://github.com/ament/ament_lint/blob/master/ament_cmake_uncrustify/doc/index.rst>`_ : a C++ style checker (Not to be used because there is already clang-format)

Additional ToDos for tooling:

- [x] restructure scripts in tools folder
- [x] lint shell scripts
- [x] tidy-up CI jobs
- [x] update dockerfile to Ubuntu Focal LTS

**Comment by elBoberido** [comment]
I think we already have `ament_cmake_copyright` since #346.

Since we already use `clang-format` I'm not sure if we need `uncrustify`. A pre-commit hook for `clang-format` would be nice, though

**Comment by prasannabhat** [comment]
We currently have Address, Leak & Undefined Behaviour Sanitizers. 
Clang has some more tools in their basket.

- https://clang.llvm.org/docs/ThreadSanitizer.html
- https://clang.llvm.org/docs/MemorySanitizer.html (all dependent libs including libc++ should be recompiled with special flags)
