### ISSUE TITLE
Git Hooks on iceoryx

### ISSUE THREAD

**Issue by dkroenke** [eclipse-iceoryx/iceoryx#486]
## Brief feature description
On iceoryx apply several formal rules from [CONTRIBUTING.md)](https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md) which we need for traceability.

To assist the developer/contributors we should add git hooks to check several formal or technical aspects.

## Detailed information

- [x] prepare-commit-msg hook for adding `iox-#123` from the branchname + installation manual
- [x] pre-check if the commit is signed-off
- [x] commit hook to check for clang-format violations
- [x] Check in Github CI for valid commit messages

**Comment by dkroenke** [comment]
Reopened to adress the missing clang-tidy integration once the ruleset is clarified in https://github.com/eclipse-iceoryx/iceoryx/issues/299.

**Comment by elBoberido** [comment]
Could we just add a task to that issue? When we close his issue we are again under 100 ;)
