### ISSUE TITLE
fail build on ubuntu 16.04 with g++ 5.4.0

### ISSUE THREAD

**Issue by BH1SCW** [eclipse-iceoryx/iceoryx#495]
## Required information

**Operating system:**
PRETTY_NAME="Ubuntu 16.04.7 LTS"

**Compiler version:**
Target: x86_64-linux-gnu
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)

**Observed result or behaviour:**
See attached log file [compiler_log_BH1SCW.txt](https://github.com/eclipse-iceoryx/iceoryx/files/6090535/compiler_log_BH1SCW.txt)

**Expected result or behaviour:**
build with no error 

**Conditions where it occurred / Performed steps:**
git commit id:
current master (original f1c4b31c54cc7fccb352fc3cdda562d9a22fe638)

---

Issues:
- [ ] Unsupported compiler command line option `-Wno-noexcept-type`
- [ ] Call to ostream from constexpr function; basically all `clog` calls in `duration.inl`; added in PR #501
   Error: `call to non-constexpr function ‘std::basic_ostream`

**Comment by mossmaurice** [comment]
Hi @BH1SCW 

Thanks, for reporting this issue! Unfortunately iceoryx does not supported GCC 5.4.0 (released on June 3, 2016). Same goes for the QNX compiler QCC. Here I'd advise to use QNX 7.1 with QCC 8.3.

Please update to a newer version of GCC/QCC. In the meantime I'll update our documentation.

**Comment by BH1SCW** [comment]
Thanks for your advice~

**Comment by dkroenke** [comment]
@BH1SCW We will open this issue again because the errors are pointing to some Lambdas in `PortManager` where the capture clause should be cleaned up.

**Comment by marthtz** [comment]
QNX 7 is using GCC 5.4.0 as well. So, I think we have to re-open the issue and resolve the issues!

**Comment by elfenpiff** [comment]
@marthtz  Oh please no! :( ...
To fix this then we require a pipeline with an old gcc-5.4.0 compiler! And we may have an even bigger problem, we use C++14 in our project and gcc-5.4.0 does it support only partially but I hope we are lucky here.

**Comment by mossmaurice** [comment]
> To fix this then we require a pipeline with an old gcc-5.4.0 compiler! 

I agree! Talked to @dkroenke last week and all companies contributing to iceoryx are currently using QNX7 with QCC 5.4.0. It [fully supports](https://github.com/eclipse-iceoryx/iceoryx/issues/220#issuecomment-668683249) C++14.

However, I'd strongly disagree to release v1.0 without any QNX support. In case it's more work than anticipated we have our April fool fallback ;-)

**Comment by budrus** [comment]
QNX support can also mean we support QNX > 7.1. Some weeks ago we made the decision to switch to C++14. As far as I understood, the problem here is related to  a C++14 problem of gcc 5.4. So if it is fine with QNX 7.1,  I would not try to solve problems related to outdated compiler versions

**Comment by marthtz** [comment]
@dkroenke did you manage set up a CI build for 16.04? That's probably the final step to close this issue after my PR is merged.

**Comment by elBoberido** [comment]
GCC5.4 has some quirks which might make the code ugly when fixing. From my point of view I wouldn't invest much time on GCC5.4 but require QNX7.1 which was released in July last year.
