### ISSUE TITLE
Add unit test for iceoryx-posh

### ISSUE THREAD

**Issue by nihalchari** [eclipse-iceoryx/iceoryx#496]
## For iceoryx is more testing needed to achieve good code coverage

add more unit/module tests for following files

- [x] capro/service_description.cpp 
- [ ] mepoo/shared_chunk.cpp 
- [ ] mepoo/ mem_pool.cpp 
- [ ] mepoo/memory_manager.cpp 
- [ ] mepoo/ mepoo_config.cpp 
- [ ] runtime/shared_memory_user.cpp 
- [ ] runtime/posh_runtime_single_process.cpp 
- [ ] runtime/posh_runtime.cpp 
- [x] runtime/node.cpp 
- [ ] gateway/gateway_base.cpp 
- [ ] gateway/gateway_config.cpp 
- [ ] gateway/toml_gateway_config_parser.cpp 
- [ ] roudi/port_pool.cpp 
- [ ] roudi/roudi_process.cpp 
- [ ] roudi/ roudi_config.cpp 
- [ ] roudi/port_manager.cpp 
- [ ] roudi/roudi_cmd_line_parser.cpp 
- [ ] roudi/roudi_cmd_line_parser_config_file_option.cpp 
- [ ] roudi/memory/memory_block.cpp 
- [ ] roudi/memory/roudi_memory_manager.cpp 
- [ ] roudi/memory/memory_provider.cpp 
- [ ] roudi/application/ iceoryx_roudi_app.cpp 

- [x] Define a default constructor ServiceDescription::ClassHash 

reference for code-coverage
https://codecov.io/gh/eclipse-iceoryx/iceoryx?branch=master

**Comment by dkroenke** [comment]
@nihalchari Could you please rework the description and write down the classes and files where you want to test. It is better for traceability to see which classes where already touched.

**Comment by dkroenke** [comment]
@nihalchari Could you please rework the issue and give more details on what you are currently working and in which classes you intent to work? It is hard to understand where in `iceoryx/iceoryx_posh/source/roudi/` you want to write tests.

Additionally the capro tests are mssing here.

**Comment by nihalchari** [comment]
> 
> 
> @nihalchari Could you please rework the description and write down the classes and files where you want to test. It is better for traceability to see which classes where already touched.

okay, ill do that

**Comment by nihalchari** [comment]
> 
> 
> @nihalchari Could you please rework the description and write down the classes and files where you want to test. It is better for traceability to see which classes where already touched.

done
