### ISSUE TITLE
Build with gcov is broken

### ISSUE THREAD

**Issue by marthtz** [eclipse-iceoryx/iceoryx#497]
## Required information

**Operating system:**
Ubuntu 20.04 LTS

**Compiler version:**
GCC 7.5.0

**Observed result or behaviour:**
Build with coverage enabled fails.

**Expected result or behaviour:**
Build works with coverage.

**Conditions where it occurred / Performed steps:**
Build broke when PR #487 was merged.
Build command: `./tools/iceoryx_build_test.sh build-strict clean debug test -c all`
Error:
```
/usr/bin/ld: CMakeFiles/test_stress_sofi.dir/stresstests/test_stress_sofi.cpp.o: in function `_GLOBAL__sub_I_00100_0__ZN51SoFiStress_SimultaneouslyPushAndPopOnEmptySoFi_Test10test_info_E':
/home/htm2abt/repo/ice_github/iceoryx_utils/test/stresstests/test_stress_sofi.cpp:552: undefined reference to `__gcov_init'
/usr/bin/ld: CMakeFiles/test_stress_sofi.dir/stresstests/test_stress_sofi.cpp.o: in function `_GLOBAL__sub_D_00100_1__ZN51SoFiStress_SimultaneouslyPushAndPopOnEmptySoFi_Test10test_info_E':
/home/htm2abt/repo/ice_github/iceoryx_utils/test/stresstests/test_stress_sofi.cpp:552: undefined reference to `__gcov_exit'
/usr/bin/ld: CMakeFiles/test_stress_sofi.dir/stresstests/test_stress_sofi.cpp.o:(.data.rel+0x20): undefined reference to `__gcov_merge_add'
collect2: error: ld returned 1 exit status

```

**Comment by elBoberido** [comment]
That's weird. I had a look at the CMakeLists.txt and the target for that stress test has the same compiler and linker flags like the other tests ... okay, I ran the command locally and the other tests also have the same linker issues.
The mentioned PR should not cause this effect. Maybe it was the previous one and that one just made it visible?

**Comment by dkroenke** [comment]
@elBoberido no, the flag `build-static` for linking gcov with static libs of iceoryx is missing. Then it will work fine.
Iceoryx is build per default as shared lib. But for tools like gcov or the adress-sanitizer we need to build static-libs.

The documentation needs to be adapted to make that more clear.

**Comment by marthtz** [comment]
Ok, I figured it's not a bug in the code but more of missing documentation thing.
As iceoryx is dynamically linked by default this is not compatible with gcov. Hence, the build arg `build-static` to allow static build that works with gcov. 

Beside updating the documentation, wouldn't it be good to automatically enable `build-static` when `--coverage` is used or at least check for it?

**Comment by marthtz** [comment]
@dkroenke should I re-label it to documentation?
