### ISSUE TITLE
Support in rmw_iceoryx

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#511]
## Brief feature description

We should support the https://github.com/ros2/rmw_iceoryx project so that is always compatible with the latest iceoryx version.

## Detailed information

- 1. [x] fix rmw_iceoryx so that it is running with the latest stable version v0.17 (so that it is at least running again) https://github.com/ros2/rmw_iceoryx/issues/40
- 2. [ ] ~~prepare rmw_iceoryx for v1.0: use the iceoryx C-binding and get it running with iceoryx v0.9 https://github.com/ros2/rmw_iceoryx/issues/41~~
- 3. [x] prepare rmw_iceoryx for v1.0: get it running with master and keep the branch on hold
- 4. [x] merge master branch into rmw_iceoryx as soon as iceoryx is on v1.0

**Comment by mossmaurice** [comment]
@jeising who initially helped to create `rmw_iceoryx` and myself start finishing off this [PR](https://github.com/ros2/rmw_iceoryx/pull/42) in a hackathon this Friday.

**Comment by ZhenshengLee** [comment]
> @jeising who initially helped to create `rmw_iceoryx` and myself will start finishing off this [PR](https://github.com/ros2/rmw_iceoryx/pull/42) in a hackathon this Friday.

Hey, it was me.
Feel free to start from this PR and I will be doing some other things about autoware.

Thanks.

**Comment by mossmaurice** [comment]
rmw_iceoryx was updated for foxy, galactic and rolling (`master` branch).
