### ISSUE TITLE
Enhancing Unit Tests in iceoryx_utils folder.

### ISSUE THREAD

**Issue by chiranjeevimaddi** [eclipse-iceoryx/iceoryx#566]
## Brief feature description
Introduce Module tests for all the folder in iceoryx_utils folder.

## Detailed information
Increase the code coverage.

- [ ] iceoryx/iceoryx_utils/source/concurrent/                 -   @JimmyBch 
- [ ] iceoryx/iceoryx_utils/source/cxx/                             -   @manel94
- [ ] iceoryx/iceoryx_utils/source/file_reader/                 -    @manel94
- [ ] iceoryx/iceoryx_utils/source/error_handling/           -    
- [ ] iceoryx/iceoryx_utils/source/log/                             -   @JimmyBch 
- [ ] iceoryx/iceoryx_utils/source/posix_wrapper/           -    @georgemathewjerrin 
- [ ] iceoryx/iceoryx_utils/source/relocatable_pointer/   - 
- [ ] iceoryx/iceoryx_utils/source/units/                          -

**Comment by budrus** [comment]
Closing this as there was no feedback
