### ISSUE TITLE
example multi publisher, subscriber -> missing some data

### ISSUE THREAD

**Issue by RamakrishnanOSS** [eclipse-iceoryx/iceoryx#575]
## Required information

**Operating system:**
Ubuntu 20.04 LTS

**Compiler version:**
E.g. GCC 9.3.0

**Observed result or behaviour:**
The multi-subscriber always miss the two "counter 0" data sent from the publisher.
Counter Instance sending: id 1 counter 0
Counter Instance sending: id 2 counter 0

**Expected result or behaviour:**
Multi-subscriber shall receive all the data sent by the publisher.

**Conditions where it occurred / Performed steps:**
Ran the applications in the following order.
1. iox-roudi
2. iox-multi-subscriber
3. iox-multi-publisher

**Comment by elBoberido** [comment]
@RamakrishnanOSS the reason for this is the internal discovery loop which runs every 50ms. Soon, there will be an option to offer/subscribe on creation of the publisher/subscriber which will eliminate this latency. See the open task in #408

**Comment by mossmaurice** [comment]
See also #301 for a detailed explanation.

**Comment by budrus** [comment]
@RamakrishnanOSS With the latest 0.90 release or the current master you should also be able to solve it by enabling the history functionality. This will allow the subscriber to get historical data on subscribe. You can enable it with the `historyCapacity` in the PublisherOptions and `historyRequest` in the SubscriberOptions. If your publisher sends before the discovery loop does the connections the subscriber will not get the sample but it is stored in the history cache when this is configured

**Comment by budrus** [comment]
@RamakrishnanOSS. On it's way lord commander #584

**Comment by budrus** [comment]
@RamakrishnanOSS PR was merged to master. You can give it another try
