### ISSUE TITLE
Add generic QNX toolchain files

### ISSUE THREAD

**Issue by marthtz** [eclipse-iceoryx/iceoryx#609]
As mentioned in the `installation.md` the easiest way to build iceoryx on QNX is to use the build script and providing a toolchain file.

Question is if we want to add some kind of generic toolchain file(s) for QNX to get people started.  See example file in associated PR.

Edit 2021-03-19:  In yesterday's dev meeting ([minutes](https://github.com/eclipse-iceoryx/iceoryx/wiki/2021-03-18-Eclipse-iceoryx-developer-meetup)) it was agreed on adding these toolchain files.

**Comment by elBoberido** [comment]
This might be a good source to create a toolchain file
https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-qnx
https://cristianadam.eu/20181202/a-better-qnx-cmake-toolchain-file/
