### ISSUE TITLE
Ensure all objects using Creation are constructed via Creation

### ISSUE THREAD

**Issue by mossmaurice** [eclipse-iceoryx/iceoryx#613]
## Brief feature description

As iceoryx aims to be fully `noexcept` the `DesignPattern::Creation` creates object that would throw an exception in the constructor. However, it doesn't require objects not to be default construct-able.

* [ ] Add type trait
* [ ] Refactor code accordingly

**Comment by mossmaurice** [comment]
UDS done: https://github.com/eclipse-iceoryx/iceoryx/compare/master...ApexAI:iox-%23613-remove-param-less-ctor-because-of-creation-pattern

**Comment by elfenpiff** [comment]
@mossmaurice closed since #1036 is trying to remove the creation pattern because it as several issues.
