### ISSUE TITLE
add [[nodiscard]] keyword to cxx::expected class

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#624]
## Brief feature description

When a method is returning a `cxx::expected` it should never be ignored. The `[[nodiscard]]` keyword ensures that the user performs at least some kind of error handling.

**Comment by mossmaurice** [comment]
As `[[nodiscard]]` is only available from C++17 we might want to use GCC's [` __attribute__((warn_unused_result))`](https://stackoverflow.com/questions/45190740/ways-to-specify-nodiscard-before-c17). However, we need to check the QNX manual if that is supported as well.

**Comment by elfenpiff** [comment]
here i would suggest wrapping this is an IOX_NODISCARD which then selects [[nodiscard]] for mac os and windows, and the attribute for gcc
