### ISSUE TITLE
FileLock requires write access to root owned directory /var/lock/

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#625]
## Required information

**Operating system:**
Gentoo, Archlinux

**Observed result or behaviour:**
`/var/lock/` is only accessible by root but the `FileLock` requires access to it. We should switch the `FileLock` directory to `/tmp` since everyone is allowed to write data here.

**Comment by elBoberido** [comment]
I don't know if that's possible for QNX. We have limited write access on those images
