### ISSUE TITLE
Tests on Raspberry Pi 4 failing

### ISSUE THREAD

**Issue by dkroenke** [eclipse-iceoryx/iceoryx#63]
## Required information

**Operating system:**
Raspbian Buster (32-Bit)
Linux armv7l GNU/Linux

**Compiler version:**
E.g. GCC 8.3.0

**Observed result or behaviour:**
Multiple Tests on Raspberry Pi 4 are failing.

**Expected result or behaviour:**
All tests are green

**Conditions where it occurred / Performed steps:**
checkout iceoryx master
execute  "./tools/iceoryx_build_test.sh test"
ececute "build/utils/utils/utils_moduletests" manually

**Test Logs:**

iceoryx_posh:
[ RUN      ] ShmCreatorDeathTest.AllocatingTooMuchMemoryLeadsToExitWithSIGBUS
/home/pi/dev/iceoryx/iceoryx_posh/test/integrationtests/test_shm_sigbus_handler.cpp:43: Failure
Death test: iox::runtime::SharedMemoryCreator<iox::roudi::MiddlewareShm> sut(badconfig)
    Result: failed to die.
 Error msg:
[  DEATH   ] Reserving 111604128 bytes in the shared memory [/iceoryx_mgmt]
[  DEATH   ] [ Reserving shared memory successful ] 
[  DEATH   ] 2020-03-17 08:54:59.689 [ Info  ]: Roudi registered management segment 0xffffffffb0121000 with size 111604128 to id 1
[  DEATH   ] Reserving 107374188800 bytes in the shared memory [/pi]
[  DEATH   ] [ Reserving shared memory successful ] 
[  DEATH   ] 2020-03-17 08:54:59.690 [ Info  ]: Roudi registered payload segment 0xffffffffb6fe5000 with size 107374188800 to id 2
[  DEATH   ] 
Reserving 111597024 bytes in the shared memory [/iceoryx_mgmt]
[ Reserving shared memory successful ] 
2020-03-17 08:55:00.066 [ Info  ]: Roudi registered management segment 0xffffffffb0123000 with size 111597024 to id 1
Reserving 1088 bytes in the shared memory [/pi]
[ Reserving shared memory successful ] 
2020-03-17 08:55:00.066 [ Info  ]: Roudi registered payload segment 0xffffffffb6fe6000 with size 1088 to id 2
[  FAILED  ] ShmCreatorDeathTest.AllocatingTooMuchMemoryLeadsToExitWithSIGBUS (750 ms)

iceoryx_utils:
[ RUN      ] relativeptrtests/0.ConstrTests
/home/pi/dev/iceoryx/iceoryx_utils/test/moduletests/test_relative_pointer.cpp:127: Failure
Expected equality of these values:
  rp.getId()
    Which is: 2
  1
/home/pi/dev/iceoryx/iceoryx_utils/test/moduletests/test_relative_pointer.cpp:143: Failure
Expected equality of these values:
  rp.getId()
    Which is: 2
  1
/home/pi/dev/iceoryx/iceoryx_utils/test/moduletests/test_relative_pointer.cpp:152: Failure
Expected equality of these values:
  rp.getId()
    Which is: 2
  1
[  FAILED  ] relativeptrtests/0.ConstrTests, where TypeParam = unsigned char (2 ms)

[ RUN      ] relativeptrtests/1.ConstrTests
/home/pi/dev/iceoryx/iceoryx_utils/test/moduletests/test_relative_pointer.cpp:127: Failure
Expected equality of these values:
  rp.getId()
    Which is: 2
  1
/home/pi/dev/iceoryx/iceoryx_utils/test/moduletests/test_relative_pointer.cpp:143: Failure
Expected equality of these values:
  rp.getId()
    Which is: 2
  1
/home/pi/dev/iceoryx/iceoryx_utils/test/moduletests/test_relative_pointer.cpp:152: Failure
Expected equality of these values:
  rp.getId()
    Which is: 2
  1
[  FAILED  ] relativeptrtests/1.ConstrTests, where TypeParam = signed char (1 ms)

[ RUN      ] relativeptrtests/2.ConstrTests
/home/pi/dev/iceoryx/iceoryx_utils/test/moduletests/test_relative_pointer.cpp:127: Failure
Expected equality of these values:
  rp.getId()
    Which is: 2
  1
/home/pi/dev/iceoryx/iceoryx_utils/test/moduletests/test_relative_pointer.cpp:143: Failure
Expected equality of these values:
  rp.getId()
    Which is: 2
  1
/home/pi/dev/iceoryx/iceoryx_utils/test/moduletests/test_relative_pointer.cpp:152: Failure
Expected equality of these values:
  rp.getId()
    Which is: 2
  1
[  FAILED  ] relativeptrtests/2.ConstrTests, where TypeParam = double (1 ms)

[ RUN      ] RelocatablePointer_test.relocation
/home/pi/dev/iceoryx/iceoryx_utils/test/moduletests/test_relocatable_ptr.cpp:78: Failure
Expected equality of these values:
  base2 - base1
    Which is: -1024
  BLOCK_SIZE
    Which is: 1024
[  FAILED  ] RelocatablePointer_test.relocation (1 ms)
[----------] 1 test from RelocatablePointer_test (1 ms total)

[ RUN      ] Duration_test.divideDuration
/home/pi/dev/iceoryx/iceoryx_utils/test/moduletests/test_unit_duration.cpp:202: Failure
The difference between result.seconds<double>() and 8.666666666666666 is 1.7763568394002505e-15, which exceeds doubleEpsilon, where
result.seconds<double>() evaluates to 8.6666666666666679,
8.666666666666666 evaluates to 8.6666666666666661, and
doubleEpsilon evaluates to 2.2204460492503131e-16.
[  FAILED  ] Duration_test.divideDuration (0 ms)

**Comment by budrus** [comment]
Closing this as we do not officially support 32 bit
