### ISSUE TITLE
Propagate and handle errors in dds gateway

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#636]
## Brief feature description

In `iox_to_dds.inl` and `dds_to_iox.inl` methods which are returning an `cxx::expected` are called but the error case is dismissed with `IOX_DISCARD_RESULT`. Either the `cxx::expected` is propagated to the user so that they can handle it or it has to be handled internally.

When this issue is closed the `IOX_DISCARD_RESULT` has to be gone and whenever the gateway is unable to work the user should be notified via the API.

**Comment by mossmaurice** [comment]
Moved to https://github.com/eclipse-iceoryx/iceoryx-gateway-dds/issues/3
