### ISSUE TITLE
Failing register/unregisterProcess in roudi.cpp not handled

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#637]
## Brief feature description

In `roudi.cpp` the methods `registerProcess`/`unregisterProcess` are called but the `cxx::expected` which contains any possible error is dismissed with `IOX_DISCARD_RESULT`. This means it is possible that a process cannot be registered in roudi but this is no where handled and the user is never informed!

When this issue is closed `IOX_DISCARD_RESULT` has to be removed and the user has to be informed about any error via the API.

**Comment by elBoberido** [comment]
Well, this is not quite correct. While the return value of `registerProcess` is not checked, the application is informed if it cannot be registered with two exceptions:
- the process list is full
- the application was build with an incompatible version
In both cases the error is at least logged to the console. But it would be better to also send a response via the message queue.

**Comment by mossmaurice** [comment]
I'd vote for adding this point to #611 and close this issue here.

**Comment by mossmaurice** [comment]
Added the point to #611
