### ISSUE TITLE
Cleanup or Remove ObjectPool

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#66]
## Brief feature description

The object pool is in a very early stage and should be refactored/cleaned up or it should be removed. At the moment it is used nowhere.

## Steps

1. If ObjectPool is not needed - remove it. If needed, perform the rest of the steps
2. follow up every todo and fix it.
3. move implementation from header (hpp) into inline (inl) file
4. cleanup unit tests (small unit tests with one or two EXPECT_*) with an behavior driven approach.

**Comment by mossmaurice** [comment]
@elfenpiff What is the current status? How much effort is this?

**Comment by dkroenke** [comment]
This is linked to #488 where an uninitialized_array is used, please clarify first if the Objectpool is maybe obsolete.

**Comment by ithier** [comment]
I use this in the gateway implementation as a place for the gateway to create publishers/subscribers/data readers/data writers when doing dynamic discovery.
See here: https://github.com/eclipse-iceoryx/iceoryx/blob/master/iceoryx_posh/include/iceoryx_posh/gateway/channel.hpp#L82

We would either need another solution for this or to not support dynamic topic discovery if we wanted to remove the object pool.

**Comment by elBoberido** [comment]
I think something like the `ObjectPool` is needed. Maybe with some refactoring and consolidation what we created after the `ObjectPool`.

**Comment by budrus** [comment]
@elfenpiff What do you think, how should we continue here?
