### ISSUE TITLE
False positive in leak sanitizer (caused by type duplications in tests)

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#666]
## Required information

**Observed result or behaviour:**

When the two tests in the PR https://github.com/eclipse-iceoryx/iceoryx/pull/663  (`test_concurrent_trigger_queue.cpp:143ff`) are commented in the clang-sanitize check for the utils moduletests fails.

**Comment by elBoberido** [comment]
it seems #667 fixes the issue
