### ISSUE TITLE
std:: converter methods to cxx::converter from utils

### ISSUE THREAD

**Issue by nihalchari** [eclipse-iceoryx/iceoryx#669]
## Brief feature description

- [ ] replace std::to_string() with cxx::covert::toString()
- [ ] replace std::stoull() with cxx::convert::fromString()

**Comment by elBoberido** [comment]
@nihalchari could you please write at least on sentence in the feature description to make it clear why this is done. Just for documentation purposes.

Btw. could this be put into #260?

**Comment by nihalchari** [comment]
@elBoberido  yes this can be put into #260 , hence i will close this issue
