### ISSUE TITLE
New tag for the release_1.0 branch for ROS 2 Rolling

### ISSUE THREAD

**Issue by clalancette** [eclipse-iceoryx/iceoryx#712]
It looks like there is one fix on the release_1.0 branch for iceoryx since the last tag (0.99.7). Could we please have a new tag so we can get those fixes released into the binary Debian packages for Rolling? Thanks.

**Comment by elBoberido** [comment]
@clalancette we plan to have our 1.0 release on Thursday. Would that be sufficient for you or do you need it earlier?

**Comment by elBoberido** [comment]
@clalancette done with the release of 1.0.0 aka Almond
