### ISSUE TITLE
Shell script which list the dependencies / uses of the STL

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#765]
## Brief feature description

We require a simple script which list all uses of the STL inside the production code (not the tests).

**Comment by elBoberido** [comment]
Can you elaborate in one or two sentences why this is needed? My mind reading skills degraded lately ;)

**Comment by elfenpiff** [comment]
@elBoberido it is required so that we know what we have to rewrite from the STL or what we have to certify inside the STL.

**Comment by elBoberido** [comment]
@elfenpiff sure, but please add it to the issue description. We have a template with brief and detailed section. Please add at least a little context and not just `do stuff`.
