### ISSUE TITLE
Change unique pointer function_ref usage for custom deleter

### ISSUE THREAD

**Issue by MatthiasKillat** [eclipse-iceoryx/iceoryx#814]
It is only safe to use a `function_ref` in the deleter if it points to a free function or noncapturing lambda (since the lifetime is guaranteed). The API however allows generic callables, which can lead to misuse.

We can
1) use function or a similar mechanism to allow generic callables up to some size 
or
2) make the API fool-proof, disallowing the cases where the lifetime cannot be guaranteed

Option one is considered preferable.

**Comment by elBoberido** [comment]
Can you please specify which custom deleter you mean?

**Comment by MatthiasKillat** [comment]
There is only one `function_ref<void(T* const)> m_deleter;`.

**Comment by elBoberido** [comment]
Ok, now I understandd you. You meant the `m_deleter` in `unique_ptr`

**Comment by MatthiasKillat** [comment]
From my point of view the `unique_ptr` should own everything that is needed to execute the deleter if we have e.g. a lambda capturing by value. If  the user specifies capturing by reference or indirectly wants to rely on the lifetime of an object for the deleter she can still do so (capture by reference) but has to explicitly do so.

As of now, if we capture by reference and the lambda goes out of scope (but the referenced object persists), it would be broken and likely crash since the lambda we reference is gone. In other words: we either have to use only function pointers (limiting functionality) or owning function wrappers (which `function_ref`is not).

**Comment by elfenpiff** [comment]
This is also addressed in issue #1143 and the linked PR #1348
