### ISSUE TITLE
Centralized or automated version number

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#837]
## Brief feature description

At the moment we have to adjust all version numbers occurrences by hand. It would be better if we had only one place where we setup the version number. Otherwise a reviewer has the problem that they require the knowledge of all version occurrences to spot missing changes.

## Detailed information

Either it is possible to have a single `VERSION` file and every other file which requires a version parses that version file to acquire the current version. This could be extremely simple if the `VERSION` file contains only the version number and would be the ideal solution when its feasible.

An alternative but not so good solution would be a `releaseme.sh` script which parses `VERSION` and adjusts the version number in a files. But this would add have the disadvantage:
- that still some files can be missed when they are not listed in the script
- every release touches a lot of files.

**Comment by elfenpiff** [comment]
FYI: @elBoberido @dkroenke

**Comment by elBoberido** [comment]
The first approach with a `VERSION` file is unfortunately not possible. We already had this but needed to move away from this for the ROS 2 builds. They are not build by using the whole repo but each module by itself. Therefore we cannot refer to a common version file outside of the modules for this. Additionally the version must also be set in the `package.xml` file.
I think the script is the best solution for this. We could also add the option to create tags and release branches. With this we would also ensure to have a consistent naming scheme for this.
