### ISSUE TITLE
Create a dynamic ServiceDescription 

### ISSUE THREAD

**Issue by vortex314** [eclipse-iceoryx/iceoryx#844]
Trying to test the software, I struggle wit a bizar issue to create dynamically a ServiceDescription 
How can I initialiize event ( IdString_t) with the content of eventName (std::string ) 
```
  for (int i = 0; i < 1000; i++) {
      string eventName = "event";
      eventName += to_string(i);
      const IdString_t event;
    ServiceDescription serviceDescription(AnyServiceString, event,AnyInstanceString);
    iox::popo::Subscriber<Buffer<256>> subscriber(serviceDescription);
}
```
Looks like IdString_t can only be initialized by constant char strings, I guess for hash calculation during compile time ? 
Tried several ways, but none compile.

**Comment by vortex314** [comment]
Ok, solved it.
```
 for (int i = 0; i < 100; i++) {
    string ev = "event";
    ev += to_string(i);
    IdString_t evx;
    evx.unsafe_assign(ev.c_str());
    ServiceDescription serviceDescription(AnyServiceString, evx,
                                          AnyInstanceString);
```

**Comment by elBoberido** [comment]
@vortex314 other possibilities would be
```cpp
IdString_t evx(TruncateToCapacity, ev);
```
or
```cpp
evx.unsafe_assign(ev);
```
This is to remind the user that the assignment might fail if the underlying fixed string is too small or that it will be truncated.
