### ISSUE TITLE
Sending data to event groups

### ISSUE THREAD

**Issue by Indra5196** [eclipse-iceoryx/iceoryx#873]
## Brief feature description

Is it possible to publish data to an `Event Group` using an Event Group Id? Such that one message from a Publisher is delivered to all subscribers subscribed to the publisher, present in a particular group defined by a group ID?

In the current examples what we have using waitset, Subscribers are attached to the waitset in an Event group using a group Id. Now, whenever any subscriber in that group receives data, the Waitset is triggered.

**Comment by elBoberido** [comment]
What do you mean with Event Group Id? I guess it's not what we have in the `capro::ServiceDescription`, right?

**Comment by Indra5196** [comment]
> What do you mean with Event Group Id? I guess it's not what we have in the `capro::ServiceDescription`, right?

No, we dont have this in `ServiceDescription` as of now.
In SOME/IP protocol, we have such a feature, that we can send to an Event Group using its Event Group ID.

**Comment by elBoberido** [comment]
Maybe this is something we can talk about in the developer meetup?

**Comment by Indra5196** [comment]
Yea sure

**Comment by budrus** [comment]
My information: 
1. In SOME/IP you can group several events of a service with an EventGroup
2. You can subscribe to EventGroups, which means you subscribe with one message to several events
3. AFAIK the events can have different data types 
4. AFAIK you can only send and receive data for a single event 

Do you think EventGroups only have events that have the same type @Indra5196 ?

**Comment by mossmaurice** [comment]
@Indra5196 @hemalbavishi Closing this issue, feel free to re-open if you have further questions.
