### ISSUE TITLE
[Question] Does lock file path matter (or, can it be replaced by whatever I want?)

### ISSUE THREAD

**Issue by MiaoDX** [eclipse-iceoryx/iceoryx#875]
## Required information

**Operating system:**
Customized Rcar H3 board with QNX 7.0

**Compiler version:**
QNX 7.0

**Observed result or behaviour:**
I failed to set the lock path to `/var/lock/` or `/tmp/` (error message as below), but one custom path such as `/opt/Free_eMMC2/icelock/` which is not owned by root is okay.

![image](https://user-images.githubusercontent.com/8840792/124920562-0447e180-e02a-11eb-8d7f-2aa1d69381ae.png)

So, if the lock path is not `/tmp/`, will it hurt the performance?

**Expected result or behaviour:**
None

**Conditions where it occurred / Performed steps:**
None

**Comment by elBoberido** [comment]
It will not hurt performance, since it is only used to prevent to start RouDi twice. You just have to be sure that you don't have two iox-roudi binaries compiled with two different lock-file paths. In this case they will interfere with one another since they want to manage the same resources.

**Comment by MiaoDX** [comment]
OK, got it, thx~ Finally, I can use iceoryx on QNX ٩(๑•ㅂ•)۶ 缪东旭 ***@***.*** 签名由 网易邮箱大师 定制 On 07/08/2021 21:43, elBoberido wrote: It will not hurt performance, since it is only used to prevent to start RouDi twice. You just have to be sure that you don't have two iox-roudi binaries compiled with two different lock-file paths. In this case they will interfere with one another since they want to manage the same resources. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by elBoberido** [comment]
Issue will be closed. Feel free to open it again it you still have related questions.
