### ISSUE TITLE
Not able to build with Clang + libc++ in Ubuntu

### ISSUE THREAD

**Issue by t0ny-peng** [eclipse-iceoryx/iceoryx#878]
## Required information

**Operating system:**

Ubuntu 18.04 (ADE)

**Compiler version:**
Clang 6.0 w/ libc++

**Observed result or behaviour:**

Hi @dkroenke. I'm trying to build Iceoryx with Clang w/ libc++. Here's the command I used:
```shell
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++

cmake ../iceoryx_meta \
  -DCMAKE_CXX_FLAGS='-stdlib=libc++' \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DBUILD_ALL=OFF -DBUILD_STRICT=OFF \
  -DCMAKE_INSTALL_PREFIX=/tmp/iceoryx/install \
  -DBUILD_SHARED_LIBS=ON \
  -DBUILD_TEST=ON \
  -DCOVERAGE=OFF \
  -DROUDI_ENVIRONMENT=ON \
  -DEXAMPLES=ON \
  -DTOML_CONFIG=ON \
  -DBUILD_DOC=OFF \
  -DDDS_GATEWAY=OFF \
  -DBINDING_C=ON \
  -DINTROSPECTION=ON \
  -DONE_TO_MANY_ONLY=OFF \
  -DSANITIZE=OFF \
  -DTEST_WITH_ADDITIONAL_USER=OFF
```

As you can see on the second line I specify the CMake variable `CMAKE_CXX_FLAGS`, value of which should be added to the option of clang in order to use `libc++`(cause the default on Ubuntu is `libstdc++`). However, the linker failed when linking the test object file with googletest being built [here](https://github.com/eclipse-iceoryx/iceoryx/blob/815f4124b230fb642a8234a0225b707a544a1dff/cmake/googletest/CMakeLists.txt#L49). The reason is that Googletest is built by manually calling `cmake` in the underlying google test folder, therefore `CMAKE_CXX_FLAGS` isn't passed correctly. The googletest objects are still using `libstdc++`. 

Can we call `ExternalProject_Add` directly in [tests.cmake](https://github.com/eclipse-iceoryx/iceoryx/blob/41bc24ddacba85e9f6202c5676c4b8f140719f5b/iceoryx_meta/tests.cmake#L19) so that the parent's `CMAKE_CXX_FLAGS` is honored by googletest?

**Expected result or behaviour:**

Googletest should receive the global variable `CMAKE_CXX_FLAGS` fed to Iceoryx

**Conditions where it occurred / Performed steps:**

Use the command above to build Iceoryx and call `nm` on the googletest objects. You'll see some symbold with `__cxx`

**Comment by dkroenke** [comment]
@t0ny-peng 
Thanks for your input, and I can confirm that compile flags are not passed correctly to the Googletest CMake file.
We've put the Googletest build into an own CMake to have a clear separation between building dependencies and the tests itself. Mixing both together is of course possible but would may make the CMake files quite large.

An alternative would be to introduce a "extra cmake flags" variable in the "external" Googletest build that could contain all user-defined build flags and pass them to the Googletest build. 

With that, `CMAKE_CXX_FLAGS` would be applied for Googletest and it can be extended in future.
What do you think?
@elBoberido FYI

**Comment by elBoberido** [comment]
@dkroenke that would work. I just don't know it there are other important build flags. I just tried adding `"-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}"` to the gtest cmake step and it seems to be sufficient.

**Comment by t0ny-peng** [comment]
@elBoberido @dkroenke The flag I want to pass to googletest is `-DCMAKE_CXX_FLAGS='-stdlib=libc++'`. If googletest is designed to be in its separate build rather than being part of Iceoryx build, then I can use shell environment variable to pass this variable to all underlying builds. 

https://cmake.org/cmake/help/latest/manual/cmake-env-variables.7.html#manual:cmake-env-variables(7)

**Comment by elBoberido** [comment]
@t0ny-peng I think that would also be possible but we can easily integrate it into the googletest build so that the flags are respected

**Comment by t0ny-peng** [comment]
@elBoberido Don't worry. The environment variable works in my case. I'm just not sure if passing the variable is the correct way to go since there'll be other cases which need other CMake options.

Thanks for your help. I'll closing this ticket since it's not urgently needed.
