### ISSUE TITLE
MacOS tests that use EXPECT_DEATH stuck

### ISSUE THREAD

**Issue by r7vme** [eclipse-iceoryx/iceoryx#898]
## Required information

Jobs that failed
https://github.com/eclipse-iceoryx/iceoryx/runs/3250456083
https://github.com/eclipse-iceoryx/iceoryx/runs/3249546327
https://github.com/eclipse-iceoryx/iceoryx/runs/3242681619

**Operating system:**
macos-10.14 (and macos-latest) (github actions machines)

**Compiler version:**
Apple clang version 12.0.0 (clang-1200.0.32.29) Target: x86_64-apple-darwin19.6.0 Thread model: posix InstalledDir: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Observed result or behaviour:**
On MacOS seems we hit deadlock or some other glitches (e.g. described [here](https://github.com/google/googletest/blob/master/docs/advanced.md#caveats)) in tests that use EXPECT_DEATH

e.g. jobs above stuck on
* RouDiEnvironment_test.StartingRouDiTwiceLeadsToError (2x)
* BindingC_Runtime_test.RuntimeNameIsNullptr

**Expected result or behaviour:**
What do you expect to happen?

No stuck tests

**Conditions where it occurred / Performed steps:**
Describe how one can reproduce the bug.

Rerun CI at least 3-5 times, if macos job is running 30+ minutes it means it stuck (6h timeout from github)

## Related

 #1422

**Comment by elBoberido** [comment]
The problem is not the death tests per se but the forking after there are other threads are already running, which is the case when RouDiEnvironment is used. Luckily, many of the death tests don't really need a running RouDi

**Comment by budrus** [comment]
Discussion in developer meeting: Replace the EXPECT_DEATH with something based on exceptions or an extended version of our error handler. 
@elfenpiff to create an issue to continue the error handler discussion

**Comment by elfenpiff** [comment]
Created issue #1032 when the error handling concept is implemented death tests should be obsolete.

**Comment by elBoberido** [comment]
With the merge of #1879 most of the `EXPECT_DEATH` are replaced. The remaining ones need a suppression for the leak sanitizer when used with `EXPECT_FATAL_FAILURE`
