### ISSUE TITLE
Add Custom clang-tidy rules

### ISSUE THREAD

**Issue by dkroenke** [eclipse-iceoryx/iceoryx#902]
## Brief feature description

From: https://github.com/eclipse-iceoryx/iceoryx/pull/895#discussion_r685994441

The given ruleset by Clang-Tidy 10 and above cannot cover certain usecases needed from iceoryx:
- Check if all functions have `noexcept` keyword
- Check if Literal suffixes are present and correct.

## Actions

- [x] Write custom clang-tidy rules (First version available here: https://github.com/mossmaurice/llvm-project/tree/add-custom-noexcept-all-the-things-rule) @mossmaurice 
- [ ] fork llvm repo and integrate the custom rules in iceoryx CI @dkroenke 
- [ ] roll out the new rulesets

**Comment by mossmaurice** [comment]
Created a PR #916 applying the [custom noexcept all the things](https://github.com/mossmaurice/llvm-project/tree/add-custom-noexcept-all-the-things-rule) rule.

Open points:
* Currently mistakenly detected as C++ code
  * `./iceoryx_binding_c/**/*.h`
  * `.iceoryx_hoofs/platform/*`

The clang tidy rule checks this:
```
  if (!getLangOpts().CPlusPlus) {
    return;
  }
```

@dkroenke Could you have a look at how we can enable the custom rule in the CI? Thanks!
