### ISSUE TITLE
Minor RouDi cleanups

### ISSUE THREAD

**Issue by mossmaurice** [eclipse-iceoryx/iceoryx#91]
## Brief feature description

* Leftovers from #70 and #78 

## Detailed information

* Deprecate old RouDi c'tors
* Take care of `@todo` in RouDi files

**Comment by mossmaurice** [comment]
Additionally `main(int argc, char* argv[])` in roudi_main.cpp shall be modified to `return roudi.run()`

Maybe you can do that in #360 @marthtz  and close this issue here?

**Comment by mossmaurice** [comment]
Open points:
  - [ ] Implement RouDiMemoryManager_Test::StreamOperatorTranslationIsCorrect

**Comment by budrus** [comment]
> Open points:
> 
>     * [ ]  Implement RouDiMemoryManager_Test::StreamOperatorTranslationIsCorrect
> 
> 
> @budrus I'll create a new issue to track this left-over. Would call in add "RouDi test coverage", ok?

Will be addressed in #454
