### ISSUE TITLE
Provide clean-only parameter in build script

### ISSUE THREAD

**Issue by mossmaurice** [eclipse-iceoryx/iceoryx#920]
## Brief feature description

@neillangmead41 requested a `clean-only` option in  `./tools/iceoryx_build_test.sh`

## Detailed information

* Adapt `./tools/iceoryx_build_test.sh` accordingly

**Comment by elBoberido** [comment]
@mossmaurice what's the use case for this parameter? We already have quite a lot of parameter to tweak the build and I fear we soon need some tests for the build script to ensure we do not break some combinations if we continue to add more parameter

**Comment by mossmaurice** [comment]
@neillangmead41 would like to avoid a `rm -rf` inside his CI scripts. In general I agree with him that most build scripts provide a `clean-only` option, but I don't have hard feelings on this.

@neillangmead41 Would it be possible if you stick with `rm -rf`?

**Comment by elBoberido** [comment]
@mossmaurice @neillangmead41 yeah, that's what the `clean` parameter does ;)

I had the impression you wanted something like "build this only if it is not yet built"

**Comment by mossmaurice** [comment]
> @mossmaurice @neillangmead41 yeah, that's what the `clean` parameter does ;)

Nope, the `clean` param also starts a build so we could think about renaming to `rebuild` ;)

**Comment by elBoberido** [comment]
@mossmaurice okay, now I understand. In this case it makes sense since one does not specify the build folder. One last question. Why is it important to remove the build directory?

**Comment by elBoberido** [comment]
@mossmaurice how about introducing a `no-build` option? This would achieve the same as a `clean-only` but you could also do the following
```console
tools/iceoryx_build_test.sh clean no-build
// do some other stuff
tools/iceoryx_build_test.sh
// so some other stuff
tools/iceoryx_build_test.sh doxygen no-build
```

Do you have time to implement this?

**Comment by elBoberido** [comment]
@neillangmead41 since this is now implemented, I hope you can accomplish your task
