### ISSUE TITLE
Handle nullptr callbacks correctly in WaitSet and Listener

### ISSUE THREAD

**Issue by dkroenke** [eclipse-iceoryx/iceoryx#932]
## Brief description

When checking the WaitSet and Listener tests with ASAN on gcc an error is thrown that a nullptr is de-referenced when a nullptr is passed as callback function to functions like `iox_ws_attach_subscriber_event` or `iox_listener_attach_subscriber_event` in the C-Binding.

In the WaitSet it should be possible for the users to use nullptr callback arguments if they want to wait in a loop.

Reference Links:
https://github.com/eclipse-iceoryx/iceoryx/pull/918#discussion_r716790474
https://github.com/eclipse-iceoryx/iceoryx/pull/918#discussion_r718865631

- [ ] Enable in CI the ASAN check with latest gcc compiler
- [ ] Refactor WaitSet and Listener to accept (or disallow) nullptr arguments
- [ ] Test explicitly against this

**Comment by elBoberido** [comment]
@dkroenke I noticed that the tasks are not checked. Are they all done or this this issue need to be reopened?
