### ISSUE TITLE
Apply the workaround for the VectorCAST tool error

### ISSUE THREAD

**Issue by dongilchang** [eclipse-iceoryx/iceoryx#934]
### Motivation
Apex.AI uses the [VectorCAST](https://www.vectorcast.com/vc/index.html) to measure the code coverage of iceoryx.

While the VectorCAST tool processes [68 line of test_cxx_newtype.cpp](https://github.com/eclipse-iceoryx/iceoryx/blob/master/iceoryx_hoofs/test/moduletests/test_cxx_newtype.cpp#L68) to measure the code coverage, the error is detected by the VectorCAST tool.

The root cause seems to come from the front end of the compiler.
It cannot process the multi-line in the raw string format in `EXPECT_FALSE` macro of CPP code.

### Workaround

The workaround is to insert the pointer of the raw string.

```cpp
TEST(NewType, DISABLED_NoComparableDoesNotCompile)
{
    const char* p = R"(
        Sut<NewType<int, newtype::ConstructByValueCopy>> a(123), b(456);
        if ( a == b ) {}
    )";
    EXPECT_FALSE(compileTest.verify(p));
}
```

**Comment by elfenpiff** [comment]
@dongilchang I created a PR with your proposal. It should be merged soon.
