### ISSUE TITLE
Not able to compile for QNX

### ISSUE THREAD

**Issue by Indra5196** [eclipse-iceoryx/iceoryx#939]
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Compiler version:**
QCC 5.4.0

I am trying to build Iceoryx for QNX by sourcing QNX SDP 7.0 in my terminal, through the provided script and the toolchain file for x86_64. But I am getting the following error
`/home/indramani/iceoryx/iceoryx_hoofs/platform/qnx/source/grp.cpp:21:53: error: 'getgrouplist' was not declared in this scope`

**Comment by dkroenke** [comment]
@Indra5196 @huangzhixin
Was one of you able to test my proposal?

**Comment by huangzhixin** [comment]
> @Indra5196 @huangzhixin Was one of you able to test my proposal?

Hi, I just had a try, it does not work. I updated to the latest master branch and did similar changes as you.
![image](https://user-images.githubusercontent.com/8335475/140200276-0016d1b7-ecdc-4984-9c15-1bec300173da.png)
The following is the build log :
[log.txt](https://github.com/eclipse-iceoryx/iceoryx/files/7470959/log.txt)

**Comment by stonebbq1** [comment]
this work done. qnx_sdp70_common.cmake
SET(CMAKE_CXX_FLAGS_DEBUG "-std=c++14")
SET(CMAKE_CXX_FLAGS_RELEASE "-std=c++14")

**Comment by budrus** [comment]
@Indra5196 @huangzhixin Do you have any updates? There is no problem on our side. Maybe you can try what @stonebbq1 proposes

**Comment by dkroenke** [comment]
I will close this issue for now if there are any objections, feel free to reopen it.
