### ISSUE TITLE
iox-roudi report error when running in docker

### ISSUE THREAD

**Issue by yooouxin** [eclipse-iceoryx/iceoryx#946]
## Required information

**Operating system:**
docker Ubuntu 18.04 LTS

**Compiler version:**
GCC 9.4

**Observed result or behaviour:**
when I run iox-roudi in docker, it report a error,how to fix it?
```
root@3818a587b62e:~# iox-roudi
2021-10-19 02:37:22.268 [ Info  ]: No config file provided and also not found at '/etc/iceoryx/roudi_co
nfig.toml'. Falling back to built-in config.
Log level set to: [Warning]
SharedMemory still there, doing an unlink of /iceoryx_mgmt
Reserving 60126248 bytes in the shared memory [/iceoryx_mgmt]
While setting the acquired shared memory to zero a fatal SIGBUS signal appeared caused by memset. The s
hared memory object with the following properties [ name = /iceoryx_mgmt, sizeInBytes = 60126248, acces
s mode = AccessMode::READ_WRITE, ownership = OwnerShip::MINE, baseAddressHint = (nil), permissions = 0
] maybe requires more memory than it is currently available in the system.
```

**Comment by elfenpiff** [comment]
@yooouxin To answer your question I require a little bit more details:
1. Did you follow the https://github.com/eclipse-iceoryx/iceoryx/tree/master/iceoryx_examples/icedocker example?
2. How does your setup look like. Do you have only one roudi instance or are there running multiple ones in different docker containers?
3. Can you please run `rm -rf /dev/shm/*` as root and then start `iox-roudi` again. Does the problem persist after this? If not then the remainings of a killed roudi instance seemed to be the cause of the issue.
4. Could you please send the output of `cat /proc/meminfo` from the machine where `iox-roudi` fails?

It seems that your docker container does not have enough memory. If this would be the case then you may have to create a custom mempools for roudi, (see: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/configuration-guide.md). But with 60Mb this seems unlikely. Another idea would be that there are running multiple roudi instances in your iceoryx docker setup when there should only run one.
