### ISSUE TITLE
[Warning]: Application XXXX not responding (last response 1559 milliseconds ago) --> removing it

### ISSUE THREAD

**Issue by LidarADAS** [eclipse-iceoryx/iceoryx#952]
Hi , 

I am using iceoryx-v0.17.0.2 on Linux ARM64, and when there are many nodes who write big data(4Mb), I will get this ERROR after some time. 

**Some processes are killed with console output:**

`Mempool [m_chunkSize = 4194368, numberOfChunks = 10, used_chunks = 10 ] has no more space left
MemoryManager: unable to acquire a chunk with a payload size of 4000120
The following mempools are available:
  MemPool [ ChunkSize = 192, PayloadSize = 128, ChunkCount = 10000 ]
  MemPool [ ChunkSize = 1088, PayloadSize = 1024, ChunkCount = 5000 ]
  MemPool [ ChunkSize = 16448, PayloadSize = 16384, ChunkCount = 1000 ]
  MemPool [ ChunkSize = 131136, PayloadSize = 131072, ChunkCount = 200 ]
  MemPool [ ChunkSize = 524352, PayloadSize = 524288, ChunkCount = 50 ]
  MemPool [ ChunkSize = 1048640, PayloadSize = 1048576, ChunkCount = 30 ]
  MemPool [ ChunkSize = 4194368, PayloadSize = 4194304, ChunkCount = 10 ]
Senderport [ service = ### Lidar2, instance = FrontRight, event = Counter ] is unable to acquire a chunk of with payload size 4000120
POSH__SENDERPORT_ALLOCATE_FAILED

ICEORYX ERROR!`

**And iox-roudi will get this output:**

[Warning]: Application XXXX not responding (last response 1559 milliseconds ago) --> removing it

**I wonder how to stop processes from being automatically terminated.**

**Comment by lix19937** [comment]
the same issue i come across  in ros2 galactic version   

```
RouDi is ready for clients
2022-01-01 11:21:41.200 [Warning]: Application iceoryx_rt_50741_1641007283175063436 not responding (last response 4583 milliseconds ago) --> removing it
```

**Comment by elBoberido** [comment]
Do you have more information? It is either related to #2193 or your application indeed terminated abnormally and roudi is just cleaning up the resources.
