### ISSUE TITLE
Extend cxx::optional ctor for inplace construction

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#967]
## Brief feature description

At the moment it is impossible to create an object inside of an optional on construction when move and copy is deleted and the constructor requires more then zero arguments. One has to always create the optional and then call emplace.

It would be so much cooler if we would could perfectly forward all those argument to the underlying constructor. The solution would look somehow like:

```cpp
struct Emplace_t {};
constexpr Emplace_t Emplace{};

template<typename T>
class optional<T> {
  template<typename... Targs>
  optional(Emplace_t, Targs&&... args); 
```

And could be used like:
```cpp
cxx::optional<MyComplexObject> optionalComplexObject(cxx::Emplace, 1, "blafu", 2.0f, whateverVariable);
```

With this we could also delete the copy and move constructor for values inside the optional and maybe even reduce the amount of code and tests.

**Comment by elBoberido** [comment]
@elfenpiff the ignorant question is why not have this by default?
