### ISSUE TITLE
Add `.expect` to expected and optional

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#996]
## Brief feature description

Implement a generic functional interface and let the classes `optional` and `expected` inherit from it. This reduces code duplication in the implementation and test cases.

### Generic Functional Interface

Introduce a generic functional interface from which nullable classes can inherit. The advantage would be that methods like
* `and_then`
* `or_else`
* `value_or`
* `expect`
* ...

Need to be implemented and tested only once and every nullable user type can be enriched with this interface with minimal code chances. This would reduce a lot of code duplication in the implementation of `optional`, `expected` etc and other classes could be enriched and extended quickly with this interface.

Furthermore we would gain the advantage to quickly introduce other functional methods to those classes without touching them directly.

### .expect method

Add a method `.expect` to the functional interface which requires the underlying class to have a certain result otherwise it will terminate.
Coming from a PR suggestion: https://github.com/eclipse-iceoryx/iceoryx/pull/994#discussion_r770530769

### Example

Bad:
```cpp
m_semaphore{std::move(Semaphore::create(CreateUnnamedSingleProcessSemaphore, 0U)
                                .or_else([](auto) {
                                    std::cerr << "Unable to create semaphore for signal watcher" << std::endl;
                                    constexpr bool UNABLE_TO_CREATE_SEMAPHORE_FOR_SIGNAL_WATCHER = false;
                                    cxx::Ensures(UNABLE_TO_CREATE_SEMAPHORE_FOR_SIGNAL_WATCHER);
                                })
```
Cool & nifty:
```cpp
Semaphore::create(...).expect("Unable to create semaphore for signal watcher"); // with expects(...) doing exactly what you did
```

**Comment by elBoberido** [comment]
@elfenpiff we could have the same for the `cxx::optional`. What do you think?

**Comment by elfenpiff** [comment]
@elBoberido I like it!

**Comment by elBoberido** [comment]
@elfenpiff the Rust `Option` and `Result` call this just `expect`, without the `s`. Maybe we should do the same?
