### ISSUE TITLE
Remove `internal::CaptureStderr();´ from all tests

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx#998]
## Brief feature description

This makes debugging error on the CI quite hard since it suppresses the output when the leak sanitizer detects a leak or the error handler calls `terminate`. Just outputting the console output on test failure is not enough, since either the test does not fail with the leak sanitizer or the test is already aborted when terminate is called. 

## Detailed information

When the tests are too verbose on the console we need to fix the root cause instead of hiding the symptoms. There is for example `Logger::SetLogLevelForScope` to temporary increase the log level to e.g. `ERROR` or `WARNING`.

**Comment by elfenpiff** [comment]
@elBoberido I support it but only when the outcome is that a successful unit test, even when is testing catastrophic failure, is quiet.
When we can achieve this then we definitely should pursue it.

**Comment by elBoberido** [comment]
@elfenpiff even if not, it's internal API and we should not use it
